TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(S1D15G10_SUPPORT)_SRC += hardware/lcd/s1d15g10/s1d15g10.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
