TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DMX_FXSLOT_SUPPORT)_SRC += \
			services/dmx-fxslot/dmx-fxslot.c \
			services/dmx-fxslot/dmx-fxslot-ecmd.c \

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
