TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DNS_SUPPORT)_SRC += services/dns/dns_net.c services/dns/resolv.c services/dns/dns_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
