TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DMX_EFFECT_SUPPORT)_SRC += \
			services/dmx-effect/dmx-effect.c \
			services/dmx-effect/dmx-effect-ecmd.c \

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
