TOPDIR ?= ../..
include $(TOPDIR)/.config

$(APP_SAMPLE_SUPPORT)_SRC += services/appsample/appsample.c
$(APP_SAMPLE_SUPPORT)_ECMD_SRC += services/appsample/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
