TARGET = libsensormodul.a
TOPDIR = ..
SRC = \
	sensormodul.c \
	kty81.c \
	lcd.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
