TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DNS_SUPPORT)_SRC += protocols/dns/dns_net.c protocols/dns/resolv.c protocols/dns/dns_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
