TOPDIR ?= ../..
include $(TOPDIR)/.config

$(NMEA_SUPPORT)_SRC += protocols/nmea/nmea.c
$(NMEA_SUPPORT)_ECMD_SRC += protocols/nmea/nmea_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
