TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ENC28J60_SUPPORT)_SRC += hardware/ethernet/enc28j60.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
