TOPDIR ?= ../..
include $(TOPDIR)/.config

SRC += core/queue/queue.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

