TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DHCP_SUPPORT)_SRC += protocols/dhcp/dhcp.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
