TOPDIR ?= ../..
include $(TOPDIR)/.config

$(GUI_SUPPORT)_SRC += core/gui/font.c 

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
