TARGET = libyport.a
TOPDIR = ..
SRC = \
	yport.c \
	yport_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
