TARGET = libyport.a
TOPDIR = ..
SRC = \
	yport.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
