TOPDIR ?= ..
include $(TOPDIR)/.config

$(YPORT_SUPPORT)_SRC += yport/yport.c yport/yport_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
