TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DOORBELL_SUPPORT)_SRC += services/doorbell/doorbell.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
