#! /bin/sh
#
# Copyright (c) 2009 by Stefan Siegl <stesie@brokenpipe.de>
# Copyright (c) 2011 by Maximilian Güntner <maximilian.guentner@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# For more information on the GPL, please go to:
# http://www.gnu.org/copyleft/gpl.html
#
tmp=$(mktemp)
authorsTmp=$(mktemp)
#Only show licenses incompatible to the GPLv3
onlyShowincompatible=false

if [ $# -gt 0 ]; then
  files="$*"
  if [ ! -z `echo $files | grep "\-o"` ] ; then
     files=`echo $files | sed -e 's/-o//g'`
     onlyShowincompatible=true;
  fi
fi
#no files passed to the script or just -o
if [ -z $files ]; then
  files="`find . -type f -name "*.[ch]"`"
fi
i=0;
for f in $files; do
  head -n 50 "$f" | tr -d '\n' | sed -e 's/dnl/ /g' -e 's/[^A-Za-z0-9 ]//g' |
    sed -e 's/  / /g' > "$tmp"
  grep -E -I -h -r -o "([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})" $f > authorsTmp
  git shortlog -e -s $f | grep -E -I -o "([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})" >> authorsTmp
  authors="`sort -u authorsTmp`"
  license="unknown"

  #cat "$tmp"
  if grep -qe 'GNU General Public License' -e 'GNU GPL' "$tmp"; then
    if grep -qe '[Vv]ersion 2' -e 'GPL v2' "$tmp"; then
      if grep -qe 'any later version' -e 'jeder späteren Version' -e 'or later' "$tmp"; then
	license="GPLv2+"
	if $onlyShowincompatible == true; then
	   continue;
	fi
      elif grep -qe 'GPL v3' -e 'or [Vv]ersion 3' "$tmp"; then
	license="GPLv2 or GPLv3"
	if $onlyShowincompatible == true; then
	   continue;
	fi
      elif grep -qe 'license GPLv2 or LGPLv21' "$tmp"; then
	license="GPLv2 or LGPLv21"
	if $onlyShowincompatible == true; then
	   continue;
	fi
      else
      	license="GPLv2 (only)"
      fi
    elif grep -qe '[Vv]ersion 3' "$tmp"; then
      license="GPLv3"
      if $onlyShowincompatible == true; then
	   continue;
      fi
    fi
  elif grep -qe 'Redistribution and use in source and binary forms with or without modification are permitted provided' "$tmp"; then
    license="BSD"
    if $onlyShowincompatible == true; then
       continue;
    fi
  elif grep -qe 'without restriction including without limitation the rights to use copy modify merge' "$tmp"; then
    license="MIT"
    if $onlyShowincompatible == true; then
       continue;
    fi
  elif grep -qe 'in the public domain' "$tmp"; then
    license="gemeinfrei"
    if $onlyShowincompatible == true; then
       continue;
    fi
  fi
  #if the files has no authors (like corrupt email address in git)
  if [ `echo $authors | wc -w` -eq 0 ]; then
    echo "$i,$f,$license,author unknown"
  else
    for a in $authors; do
      echo "$i,$f,$license,$a"
    done
  fi
  let i++
done

rm -f "$tmp"
rm -f "$authorsTmp"
