TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ELTAKOMS_SUPPORT)_SRC += protocols/eltakoms/eltakoms.c
$(ELTAKOMS_SUPPORT)_ECMD_SRC += protocols/eltakoms/eltakoms_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
