TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ADC_SUPPORT)_ECMD_SRC += hardware/adc/adc.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
