TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(PS2_SUPPORT)_SRC += hardware/input/ps2/ps2.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
