TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(PROTO_ASK_SUPPORT)_SRC += protocols/radio/ask/ask.c

$(PROTO_2272_SUPPORT)_ECMD_SRC += protocols/radio/ask/ask_2272_ecmd.c
$(PROTO_1527_SUPPORT)_ECMD_SRC += protocols/radio/ask/ask_1527_ecmd.c
$(PROTO_TEVION_SUPPORT)_ECMD_SRC += protocols/radio/ask/ask_tevion_ecmd.c
$(PROTO_INTERTECHNO_SUPPORT)_ECMD_SRC += protocols/radio/ask/ask_intertechno_ecmd.c
$(PROTO_INTERTECHNO_SL_SUPPORT)_ECMD_SRC += protocols/radio/ask/ask_intertechno_sl_ecmd.c
$(PROTO_OASEFMMASTER_SUPPORT)_ECMD_SRC += protocols/radio/ask/ask_oasefmmaster_ecmd.c
$(PROTO_SMOKEDETECTOR_SUPPORT)_ECMD_SRC += protocols/radio/ask/ask_smokedetector_ecmd.c


##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

