TARGET = libmdns_sd.a
TOPDIR = ..
SRC = \
	mdns_sd.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
