TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WOL_SUPPORT)_SRC += services/wol/wol.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
