TOPDIR ?= ../..
include $(TOPDIR)/.config

$(IOUDP_PROTOCOL_SUPPORT)_SRC += protocols/udpIO/udpio_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
