TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SIP_SUPPORT)_SRC += protocols/sip/sip.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
