TARGET = libfs20.a
TOPDIR = ..
SRC = \
	fs20.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
