TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SRF05_SUPPORT)_SRC += hardware/ultrasonic/srf05.c
$(ULTRASONIC_SUPPORT)_ECMD_SRC += hardware/ultrasonic/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
