TOPDIR ?= ../..
include $(TOPDIR)/.config

$(BOOTP_SUPPORT)_SRC += protocols/bootp/bootp_net.c protocols/bootp/bootp.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
