TARGET = libmodbus.a
TOPDIR = ..
SRC = \
	modbus.c \
	modbus_client.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk

modbus_client.c: modbus_client_cb.c
