TARGET = libmodbus.a
TOPDIR = ..
SRC = \
	modbus.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
