TARGET = libmcuf.a
TOPDIR = ..
SRC = \
        ../pinning.c \
	mcuf.c \
	mcuf_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
