TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WS2801_SUPPORT)_SRC += protocols/ws2801/ws2801.c protocols/ws2801/ws2801_net.c
$(WS2801_SUPPORT)_ECMD_SRC += protocols/ws2801/ws2801_ecmd.c

# $(DMX_SUPPORT)_ECMD_SRC += \
# 	protocols/ws2801/ecmd.c
##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
