TOPDIR ?= ..
include $(TOPDIR)/.config

$(DNS_SUPPORT)_SRC += dns/dns_net.c dns/resolv.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
