TARGET = libdns.a
TOPDIR = ..
SRC = \
	resolv.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
