TOPDIR ?= ..
include $(TOPDIR)/.config

$(KTY_SUPPORT)_SRC += kty/kty81.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
