TARGET = libkty.a
TOPDIR = ..
SRC = \
	kty81.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
