/*
 * scheduler/scheduler.c
 *
 * Copyright (c) 2013-2015 by Michael Brakemeier <michael@brakemeier.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * For more information on the GPL, please go to:
 * http://www.gnu.org/copyleft/gpl.html
 */

#include "config.h"

#include "scheduler.h"

#include <avr/pgmspace.h>

#ifdef SCHEDULER_DYNAMIC_SUPPORT
/*
 * All the dynamic timer control blocks one array (in RAM)
 */
dynamic_timer_cb_t scheduler_dynamic_timers[CONF_SCHEDULER_NUM_DYNAMIC_TIMERS];

/*
 * Max. number of static timers in timer array, generated by meta_magic_scheduler.m4.
 */
const uint8_t scheduler_dynamic_timer_max = CONF_SCHEDULER_NUM_DYNAMIC_TIMERS;

#endif /* SCHEDULER_DYNAMIC_SUPPORT */

/**
 * The scheduler loop.
 */
void
scheduler_dispatch_timer(void)
{
  uint8_t i;

  /* invoke all runnable static timers with a delay counter of zero */
  for(i = 0; i < scheduler_static_timer_max; i++)
  {
    // check for a valid timer ready to run
    if(((scheduler_static_timers_control[i].state & TIMER_RUNNABLE) == TIMER_RUNNABLE)
        && (scheduler_static_timers_control[i].delay == 0))
    {
      // call timer
      timer_t timer_func = (timer_t)pgm_read_word(&(scheduler_static_timers[i].timer));

      // set flags
      scheduler_static_timers_control[i].state &= (uint8_t)~TIMER_RUNNABLE;
      scheduler_static_timers_control[i].state |= TIMER_RUNNING;

      (*timer_func)();

      // reset delay
      scheduler_static_timers_control[i].delay =
          (uint16_t)pgm_read_word(&(scheduler_static_timers[i].interval));

      // set back to runnable
      scheduler_static_timers_control[i].state &= (uint8_t)~TIMER_RUNNING;
      scheduler_static_timers_control[i].state |= TIMER_RUNNABLE;
    }
  }

#ifdef SCHEDULER_DYNAMIC_SUPPORT
  for(i = 0; i < scheduler_dynamic_timer_max; i++)
  {
    // check for a valid timer ready to run
    if(((scheduler_dynamic_timers[i].state & TIMER_RUNNABLE) == TIMER_RUNNABLE)
        && (scheduler_dynamic_timers[i].delay == 0))
    {
      // call timer
      scheduler_dynamic_timers[i].state &= (uint8_t)~TIMER_RUNNABLE;
      scheduler_dynamic_timers[i].state |= TIMER_RUNNING;

      (*scheduler_dynamic_timers[i].timer)();

      if ((scheduler_dynamic_timers[i].state & TIMER_ONESHOT) == TIMER_ONESHOT)
      {
        // auto-delete one-shot timer
        scheduler_dynamic_timers[i].delay = SCHEDULER_INTERVAL_MAX;
        scheduler_dynamic_timers[i].state = TIMER_DELETED;

      }
      else if ((scheduler_dynamic_timers[i].state != TIMER_DELETED) &&
          ((scheduler_dynamic_timers[i].state & TIMER_SUSPENDED) != TIMER_SUSPENDED))
      {
        // common dynamic timer - reset/restart values
        scheduler_dynamic_timers[i].delay = scheduler_static_timers[i].interval;

        // set back to runnable
        scheduler_dynamic_timers[i].state &= (uint8_t)~TIMER_RUNNING;
        scheduler_dynamic_timers[i].state |= TIMER_RUNNABLE;
      }
      else
      {
        // always reset RUNNING state
        scheduler_dynamic_timers[i].state &= (uint8_t)~TIMER_RUNNING;
      }
    }
  }
#endif /* SCHEDULER_DYNAMIC_SUPPORT */

  return;
}


/*
  -- Ethersex META --
  header(core/scheduler/scheduler.h)
  periodic_milliticks_header(core/scheduler/scheduler.h)
  periodic_milliticks_isr(scheduler_tick())
*/
