TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MYSQL_SUPPORT)_SRC += protocols/mysql/mysql.c protocols/mysql/mysql_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

