TOPDIR ?= ../..
include $(TOPDIR)/.config

$(CAN_SUPPORT)_SRC += hardware/can/can.c \
		hardware/can/mcp2515.c \
		hardware/can/fifo.c

#$(CAN_SUPPORT)_SRC += hardware/can/can_example.c
		
##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
