TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MCP2515_SUPPORT)_SRC += hardware/can/can_mcp2515.c

$(MCP2515_EXAMPLE)_SRC += hardware/can/can_example.c
		
##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
