TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SYSLOG_SUPPORT)_SRC += protocols/syslog/syslog_net.c protocols/syslog/syslog.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
