TARGET = libnamed_pin.a
TOPDIR = ..
SRC = \
	named_pin.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
