# 
# np_simple.awk
#
BEGIN {
  print "/*"
  print " * This file has been automatically generated by np_simple.awk"
  print " */"
  print
  print "#include <avr/io.h>"
  print 
  print "void"
  print "named_pin_init(void)"
  print "{"
}

{
  if ($2 == 1) {
    # The pin is an input pin.
    print "  DDR" substr($1, 2, 1) " &= ~_BV("$1");"

    if ($3 == 0) {
      # Inverted input pin, enable pull-up resistor.
      print "  PORT" substr($1, 2, 1) " |= _BV("$1"); "
    }
  }
  else {
    # Output pin.
    print "  DDR" substr($1, 2, 1) " |= _BV("$1");"
  }
}

END {
  print "}"
}
