TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(ECMD_BLUETOOTH_SUPPORT)_SRC += protocols/ecmd/via_bluetooth/ecmd_bt.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
