TOPDIR ?= ..
include $(TOPDIR)/.config

$(SNMP_SUPPORT)_SRC += snmp/snmp_net.c snmp/snmp.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk

