TARGET = libsnmp.a
TOPDIR = ..
SRC = \
	snmp_net.c \
	snmp.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk

