TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ONEWIRE_SUPPORT)_SRC += hardware/onewire/onewire.c
$(ONEWIRE_SUPPORT)_ECMD_SRC += hardware/onewire/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
