TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ONEWIRE_SUPPORT)_SRC += hardware/onewire/onewire.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
