TOPDIR ?= ../..
include $(TOPDIR)/.config

$(TLC5620_SUPPORT)_ECMD_SRC += hardware/dac/tlc5620.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
