TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MQ135_SUPPORT)_SRC += protocols/mq135/mq135.c
$(MQ135_SUPPORT)_ECMD_SRC += protocols/mq135/mq135_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
