TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SRAM_SUPPORT)_SRC += hardware/sram/sram.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
