TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SNMP_SUPPORT)_SRC += protocols/snmp/snmp_net.c protocols/snmp/snmp.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

