# 
# np_simple.awk
#
BEGIN {
  print "/*"
  print " * This file has been automatically generated by np_simple.awk"
  print " */"
  print
  print "#include <avr/io.h>"
  print "#include \"config.h\""
  print 
  print "void"
  print "np_simple_init(void)"
  print "{"
}

/^[\s#]*$/ {next;}

{
  if ($2 == 1 || $2 == "INPUT") {
    # The pin is an input pin.
    print "  DDR" substr($1, 2, 1) " &= ~_BV("$1");"

    if ($3 == 1 || $3 == "HIGH") {
      # Inverted input pin, enable pull-up resistor.
      print "  PORT" substr($1, 2, 1) " |= _BV("$1"); "
    }
  }
  else {
    # Output pin.
    print "  DDR" substr($1, 2, 1) " |= _BV("$1");"
  }
}

END {
  print "}"
}
