TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(ECMD_SENDER_SUPPORT)_SRC += protocols/ecmd/sender/ecmd_sender_net.c
$(UECMD_SENDER_SUPPORT)_SRC += protocols/ecmd/sender/uecmd_sender_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
