TOPDIR ?= ../..
include $(TOPDIR)/.config

$(STELLA_SUPPORT)_SRC += \
	services/stella/stella_pwm.c \
	services/stella/stella_net.c \
	services/stella/stella_protocol.c \
	services/stella/stella.c \
	services/stella/stella_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
