TARGET = libcron_static.a
TOPDIR = ..
SRC = \
	cron_static.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
