TARGET = libtetrirape.a
TOPDIR = ..
SRC = \
	crack.c \
	tetrirape.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
