#ifndef STELLA_H
#define STELLA_H

enum stella_commands
{
  STELLA_SET_COLOR_0,
  STELLA_SET_COLOR_1,
  STELLA_SET_COLOR_2,
  STELLA_SET_COLOR_3,
  STELLA_SET_COLOR_4,
  STELLA_SET_COLOR_5,
  STELLA_SET_COLOR_6,
  STELLA_SET_COLOR_7,
  STELLA_FADE_COLOR_0,
  STELLA_FADE_COLOR_1,
  STELLA_FADE_COLOR_2,
  STELLA_FADE_COLOR_3,
  STELLA_FADE_COLOR_4,
  STELLA_FADE_COLOR_5,
  STELLA_FADE_COLOR_6,
  STELLA_FADE_COLOR_7,
  STELLA_FLASH_COLOR_0,
  STELLA_FLASH_COLOR_1,
  STELLA_FLASH_COLOR_2,
  STELLA_FLASH_COLOR_3,
  STELLA_FLASH_COLOR_4,
  STELLA_FLASH_COLOR_5,
  STELLA_FLASH_COLOR_6,
  STELLA_FLASH_COLOR_7,
  STELLA_SELECT_FADE_FUNC,
  STELLA_FADE_STEP,
  STELLA_ACK_RESPONSE,
  STELLA_UNICAST_RESPONSE,
  STELLA_BROADCAST_RESPONSE
};

#endif // STELLA_H
