TOPDIR ?= ../..
include $(TOPDIR)/.config

$(UDP_ECHO_NET_SUPPORT)_SRC += services/echo/udp_echo_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
