TOPDIR ?= ../..
include $(TOPDIR)/.config

$(PSB2186_SUPPORT)_SRC += hardware/isdn/psb2186.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

