TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DALI_SUPPORT)_SRC += protocols/dali/dali.c
$(DALI_SUPPORT)_ECMD_SRC += protocols/dali/dali_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
