TARGET = libps2.a
TOPDIR = ..
SRC = \
	ps2.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
