TOPDIR ?= ../..
include $(TOPDIR)/.config

$(PROJECTOR_SANYO_Z700_SUPPORT)_ECMD_SRC += services/projectors/sanyoZ700/ecmd.c
$(PROJECTOR_SANYO_Z700_SUPPORT)_SRC += \
	services/projectors/sanyoZ700/sanyoz700.c

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
