TARGET = libi2c.a
TOPDIR = ..
SRC = \
	i2c.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
