TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(ECMD_SERIAL_I2C_SUPPORT)_SRC += protocols/ecmd/via_i2c/ecmd_i2c.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
