TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SHT_SUPPORT)_SRC += hardware/sht/sht.c
$(SHT_SUPPORT)_ECMD_SRC += hardware/sht/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
