TOPDIR ?= ..
include $(TOPDIR)/.config

$(I2C_SLAVE_SUPPORT)_SRC += hardware/i2c/slave/i2c_slave.c 
##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
