TARGET = libbootp.a
TOPDIR = ..
SRC = \
	bootp_net.c \
	bootp.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
