TOPDIR ?= ..
include $(TOPDIR)/.config

$(BOOTP_SUPPORT)_SRC +=	bootp/bootp_net.c bootp/bootp.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
