/*
 * Copyright (c) 2017 Erik Kunze <ethersex@erik-kunze.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * For more information on the GPL, please go to:
 * http://www.gnu.org/copyleft/gpl.html
 */

#ifndef __GLCD_MONO_H
#define __GLCD_MONO_H

#undef noinline
#include "libs/u8g2lib/u8g2.h"

typedef u8g2_t glcd_t;

#define glcd_get_width()                  u8g2_GetDisplayWidth(&glcd)
#define glcd_get_height()                 u8g2_GetDisplayHeight(&glcd)

#define glcd_send_buffer()                u8g2_SendBuffer(&glcd)
#define glcd_clear_buffer()               u8g2_ClearBuffer(&glcd)
#define glcd_first_page()                 u8g2_FirstPage(&glcd)
#define glcd_next_page()                  u8g2_NextPage(&glcd)

#define glcd_set_draw_color(...)          u8g2_SetDrawColor(&glcd, __VA_ARGS__)
#define glcd_get_draw_color()             u8g2_GetDrawColor(&glcd)
#define glcd_draw_pixel(...)              u8g2_DrawPixel(&glcd, __VA_ARGS__)

#define glcd_draw_line(...)               u8g2_DrawLine(&glcd, __VA_ARGS__)
#define glcd_draw_h_line(...)             u8g2_DrawHLine(&glcd, __VA_ARGS__)
#define glcd_draw_v_line(...)             u8g2_DrawVLine(&glcd, __VA_ARGS__)
#define glcd_draw_hv_line(...)            u8g2_DrawHVLine(&glcd, __VA_ARGS__)

#define glcd_clear_screen()               u8g2_ClearDisplay(&glcd)
#define glcd_draw_frame(...)              u8g2_DrawFrame(&glcd, __VA_ARGS__)
#define glcd_draw_r_frame(...)            u8g2_DrawRFrame(&glcd, __VA_ARGS__)
#define glcd_draw_box(...)                u8g2_DrawBox(&glcd, __VA_ARGS__)
#define glcd_draw__r_box(...)             u8g2_DrawRBox(&glcd, __VA_ARGS__)

#define glcd_draw_disc(...)               u8g2_DrawDisc(&glcd, __VA_ARGS__)
#define glcd_draw_circle(...)             u8g2_DrawCircle(&glcd, __VA_ARGS__)
#define glcd_draw_triangle(...)           u8g2_DrawTriangle(&glcd, __VA_ARGS__)
#define glcd_draw_ellipse(...)            u8g2_DrawEllipse(&glcd, __VA_ARGS__)
#define glcd_draw_filled_ellipse(...)     u8g2_DrawFilledEllipse(&glcd, __VA_ARGS__)

#define GLCD_BITMAP_MODE_TRANSPARENT      1
#define GLCD_BITMAP_MODE_SOLID            0
#define glcd_set_bitmap_mode(mode)        u8g2_SetBitmapMode(&glcd, mode)
#define glcd_draw_bitmap(...)             u8g2_DrawBitmap(&glcd, __VA_ARGS__)
#define glcd_draw_xbm(...)                u8g2_DrawXBM(&glcd, __VA_ARGS__)
#define glcd_draw_xbmp(...)               u8g2_DrawXBMP(&glcd, __VA_ARGS__)

// printf "%s %-33s %s\n" $(sed '/^const uint8_t/!d;s/const uint8_t \([^ ]*\)\[.*/#define \U\1\E\t\t\L\1/;s/U8G2/GLCD/' u8g2_fonts.c|sort)
#define GLCD_FONT_10X20_ME                u8g2_font_10x20_me
#define GLCD_FONT_10X20_MF                u8g2_font_10x20_mf
#define GLCD_FONT_10X20_MN                u8g2_font_10x20_mn
#define GLCD_FONT_10X20_MR                u8g2_font_10x20_mr
#define GLCD_FONT_10X20_T_ARABIC          u8g2_font_10x20_t_arabic
#define GLCD_FONT_10X20_T_CYRILLIC        u8g2_font_10x20_t_cyrillic
#define GLCD_FONT_10X20_TE                u8g2_font_10x20_te
#define GLCD_FONT_10X20_TF                u8g2_font_10x20_tf
#define GLCD_FONT_10X20_T_GREEK           u8g2_font_10x20_t_greek
#define GLCD_FONT_10X20_TN                u8g2_font_10x20_tn
#define GLCD_FONT_10X20_TR                u8g2_font_10x20_tr
#define GLCD_FONT_4X6_MF                  u8g2_font_4x6_mf
#define GLCD_FONT_4X6_MN                  u8g2_font_4x6_mn
#define GLCD_FONT_4X6_MR                  u8g2_font_4x6_mr
#define GLCD_FONT_4X6_T_CYRILLIC          u8g2_font_4x6_t_cyrillic
#define GLCD_FONT_4X6_TF                  u8g2_font_4x6_tf
#define GLCD_FONT_4X6_TN                  u8g2_font_4x6_tn
#define GLCD_FONT_4X6_TR                  u8g2_font_4x6_tr
#define GLCD_FONT_5X7_MF                  u8g2_font_5x7_mf
#define GLCD_FONT_5X7_MN                  u8g2_font_5x7_mn
#define GLCD_FONT_5X7_MR                  u8g2_font_5x7_mr
#define GLCD_FONT_5X7_T_CYRILLIC          u8g2_font_5x7_t_cyrillic
#define GLCD_FONT_5X7_TF                  u8g2_font_5x7_tf
#define GLCD_FONT_5X7_TN                  u8g2_font_5x7_tn
#define GLCD_FONT_5X7_TR                  u8g2_font_5x7_tr
#define GLCD_FONT_5X8_MF                  u8g2_font_5x8_mf
#define GLCD_FONT_5X8_MN                  u8g2_font_5x8_mn
#define GLCD_FONT_5X8_MR                  u8g2_font_5x8_mr
#define GLCD_FONT_5X8_T_CYRILLIC          u8g2_font_5x8_t_cyrillic
#define GLCD_FONT_5X8_TF                  u8g2_font_5x8_tf
#define GLCD_FONT_5X8_TN                  u8g2_font_5x8_tn
#define GLCD_FONT_5X8_TR                  u8g2_font_5x8_tr
#define GLCD_FONT_6X10_MF                 u8g2_font_6x10_mf
#define GLCD_FONT_6X10_MN                 u8g2_font_6x10_mn
#define GLCD_FONT_6X10_MR                 u8g2_font_6x10_mr
#define GLCD_FONT_6X10_TF                 u8g2_font_6x10_tf
#define GLCD_FONT_6X10_TN                 u8g2_font_6x10_tn
#define GLCD_FONT_6X10_TR                 u8g2_font_6x10_tr
#define GLCD_FONT_6X12_ME                 u8g2_font_6x12_me
#define GLCD_FONT_6X12_MF                 u8g2_font_6x12_mf
#define GLCD_FONT_6X12_MN                 u8g2_font_6x12_mn
#define GLCD_FONT_6X12_MR                 u8g2_font_6x12_mr
#define GLCD_FONT_6X12_M_SYMBOLS          u8g2_font_6x12_m_symbols
#define GLCD_FONT_6X12_T_CYRILLIC         u8g2_font_6x12_t_cyrillic
#define GLCD_FONT_6X12_TE                 u8g2_font_6x12_te
#define GLCD_FONT_6X12_TF                 u8g2_font_6x12_tf
#define GLCD_FONT_6X12_TN                 u8g2_font_6x12_tn
#define GLCD_FONT_6X12_TR                 u8g2_font_6x12_tr
#define GLCD_FONT_6X12_T_SYMBOLS          u8g2_font_6x12_t_symbols
#define GLCD_FONT_6X13B_MF                u8g2_font_6x13B_mf
#define GLCD_FONT_6X13B_MN                u8g2_font_6x13B_mn
#define GLCD_FONT_6X13B_MR                u8g2_font_6x13B_mr
#define GLCD_FONT_6X13B_T_CYRILLIC        u8g2_font_6x13B_t_cyrillic
#define GLCD_FONT_6X13B_TF                u8g2_font_6x13B_tf
#define GLCD_FONT_6X13B_T_HEBREW          u8g2_font_6x13B_t_hebrew
#define GLCD_FONT_6X13B_TN                u8g2_font_6x13B_tn
#define GLCD_FONT_6X13B_TR                u8g2_font_6x13B_tr
#define GLCD_FONT_6X13_ME                 u8g2_font_6x13_me
#define GLCD_FONT_6X13_MF                 u8g2_font_6x13_mf
#define GLCD_FONT_6X13_MN                 u8g2_font_6x13_mn
#define GLCD_FONT_6X13_MR                 u8g2_font_6x13_mr
#define GLCD_FONT_6X13O_MF                u8g2_font_6x13O_mf
#define GLCD_FONT_6X13O_MN                u8g2_font_6x13O_mn
#define GLCD_FONT_6X13O_MR                u8g2_font_6x13O_mr
#define GLCD_FONT_6X13O_TF                u8g2_font_6x13O_tf
#define GLCD_FONT_6X13O_TN                u8g2_font_6x13O_tn
#define GLCD_FONT_6X13O_TR                u8g2_font_6x13O_tr
#define GLCD_FONT_6X13_T_CYRILLIC         u8g2_font_6x13_t_cyrillic
#define GLCD_FONT_6X13_TE                 u8g2_font_6x13_te
#define GLCD_FONT_6X13_TF                 u8g2_font_6x13_tf
#define GLCD_FONT_6X13_T_HEBREW           u8g2_font_6x13_t_hebrew
#define GLCD_FONT_6X13_TN                 u8g2_font_6x13_tn
#define GLCD_FONT_6X13_TR                 u8g2_font_6x13_tr
#define GLCD_FONT_7SEGMENTS_26X42_MN      u8g2_font_7Segments_26x42_mn
#define GLCD_FONT_7X13B_MF                u8g2_font_7x13B_mf
#define GLCD_FONT_7X13B_MN                u8g2_font_7x13B_mn
#define GLCD_FONT_7X13B_MR                u8g2_font_7x13B_mr
#define GLCD_FONT_7X13B_TF                u8g2_font_7x13B_tf
#define GLCD_FONT_7X13B_TN                u8g2_font_7x13B_tn
#define GLCD_FONT_7X13B_TR                u8g2_font_7x13B_tr
#define GLCD_FONT_7X13_ME                 u8g2_font_7x13_me
#define GLCD_FONT_7X13_MF                 u8g2_font_7x13_mf
#define GLCD_FONT_7X13_MN                 u8g2_font_7x13_mn
#define GLCD_FONT_7X13_MR                 u8g2_font_7x13_mr
#define GLCD_FONT_7X13_M_SYMBOLS          u8g2_font_7x13_m_symbols
#define GLCD_FONT_7X13O_MF                u8g2_font_7x13O_mf
#define GLCD_FONT_7X13O_MN                u8g2_font_7x13O_mn
#define GLCD_FONT_7X13O_MR                u8g2_font_7x13O_mr
#define GLCD_FONT_7X13O_TF                u8g2_font_7x13O_tf
#define GLCD_FONT_7X13O_TN                u8g2_font_7x13O_tn
#define GLCD_FONT_7X13O_TR                u8g2_font_7x13O_tr
#define GLCD_FONT_7X13_T_CYRILLIC         u8g2_font_7x13_t_cyrillic
#define GLCD_FONT_7X13_TE                 u8g2_font_7x13_te
#define GLCD_FONT_7X13_TF                 u8g2_font_7x13_tf
#define GLCD_FONT_7X13_TN                 u8g2_font_7x13_tn
#define GLCD_FONT_7X13_TR                 u8g2_font_7x13_tr
#define GLCD_FONT_7X13_T_SYMBOLS          u8g2_font_7x13_t_symbols
#define GLCD_FONT_7X14B_MF                u8g2_font_7x14B_mf
#define GLCD_FONT_7X14B_MN                u8g2_font_7x14B_mn
#define GLCD_FONT_7X14B_MR                u8g2_font_7x14B_mr
#define GLCD_FONT_7X14B_TF                u8g2_font_7x14B_tf
#define GLCD_FONT_7X14B_TN                u8g2_font_7x14B_tn
#define GLCD_FONT_7X14B_TR                u8g2_font_7x14B_tr
#define GLCD_FONT_7X14_MF                 u8g2_font_7x14_mf
#define GLCD_FONT_7X14_MN                 u8g2_font_7x14_mn
#define GLCD_FONT_7X14_MR                 u8g2_font_7x14_mr
#define GLCD_FONT_7X14_TF                 u8g2_font_7x14_tf
#define GLCD_FONT_7X14_TN                 u8g2_font_7x14_tn
#define GLCD_FONT_7X14_TR                 u8g2_font_7x14_tr
#define GLCD_FONT_8X13B_MF                u8g2_font_8x13B_mf
#define GLCD_FONT_8X13B_MN                u8g2_font_8x13B_mn
#define GLCD_FONT_8X13B_MR                u8g2_font_8x13B_mr
#define GLCD_FONT_8X13B_TF                u8g2_font_8x13B_tf
#define GLCD_FONT_8X13B_TN                u8g2_font_8x13B_tn
#define GLCD_FONT_8X13B_TR                u8g2_font_8x13B_tr
#define GLCD_FONT_8X13_ME                 u8g2_font_8x13_me
#define GLCD_FONT_8X13_MF                 u8g2_font_8x13_mf
#define GLCD_FONT_8X13_MN                 u8g2_font_8x13_mn
#define GLCD_FONT_8X13_MR                 u8g2_font_8x13_mr
#define GLCD_FONT_8X13_M_SYMBOLS          u8g2_font_8x13_m_symbols
#define GLCD_FONT_8X13O_MF                u8g2_font_8x13O_mf
#define GLCD_FONT_8X13O_MN                u8g2_font_8x13O_mn
#define GLCD_FONT_8X13O_MR                u8g2_font_8x13O_mr
#define GLCD_FONT_8X13O_TF                u8g2_font_8x13O_tf
#define GLCD_FONT_8X13O_TN                u8g2_font_8x13O_tn
#define GLCD_FONT_8X13O_TR                u8g2_font_8x13O_tr
#define GLCD_FONT_8X13_T_CYRILLIC         u8g2_font_8x13_t_cyrillic
#define GLCD_FONT_8X13_TE                 u8g2_font_8x13_te
#define GLCD_FONT_8X13_TF                 u8g2_font_8x13_tf
#define GLCD_FONT_8X13_TN                 u8g2_font_8x13_tn
#define GLCD_FONT_8X13_TR                 u8g2_font_8x13_tr
#define GLCD_FONT_8X13_T_SYMBOLS          u8g2_font_8x13_t_symbols
#define GLCD_FONT_9X15B_MF                u8g2_font_9x15B_mf
#define GLCD_FONT_9X15B_MN                u8g2_font_9x15B_mn
#define GLCD_FONT_9X15B_MR                u8g2_font_9x15B_mr
#define GLCD_FONT_9X15B_TF                u8g2_font_9x15B_tf
#define GLCD_FONT_9X15B_TN                u8g2_font_9x15B_tn
#define GLCD_FONT_9X15B_TR                u8g2_font_9x15B_tr
#define GLCD_FONT_9X15_ME                 u8g2_font_9x15_me
#define GLCD_FONT_9X15_MF                 u8g2_font_9x15_mf
#define GLCD_FONT_9X15_MN                 u8g2_font_9x15_mn
#define GLCD_FONT_9X15_MR                 u8g2_font_9x15_mr
#define GLCD_FONT_9X15_M_SYMBOLS          u8g2_font_9x15_m_symbols
#define GLCD_FONT_9X15_T_CYRILLIC         u8g2_font_9x15_t_cyrillic
#define GLCD_FONT_9X15_TE                 u8g2_font_9x15_te
#define GLCD_FONT_9X15_TF                 u8g2_font_9x15_tf
#define GLCD_FONT_9X15_TN                 u8g2_font_9x15_tn
#define GLCD_FONT_9X15_TR                 u8g2_font_9x15_tr
#define GLCD_FONT_9X15_T_SYMBOLS          u8g2_font_9x15_t_symbols
#define GLCD_FONT_9X18B_MF                u8g2_font_9x18B_mf
#define GLCD_FONT_9X18B_MN                u8g2_font_9x18B_mn
#define GLCD_FONT_9X18B_MR                u8g2_font_9x18B_mr
#define GLCD_FONT_9X18B_TF                u8g2_font_9x18B_tf
#define GLCD_FONT_9X18B_TN                u8g2_font_9x18B_tn
#define GLCD_FONT_9X18B_TR                u8g2_font_9x18B_tr
#define GLCD_FONT_9X18_MF                 u8g2_font_9x18_mf
#define GLCD_FONT_9X18_MN                 u8g2_font_9x18_mn
#define GLCD_FONT_9X18_MR                 u8g2_font_9x18_mr
#define GLCD_FONT_9X18_TF                 u8g2_font_9x18_tf
#define GLCD_FONT_9X18_TN                 u8g2_font_9x18_tn
#define GLCD_FONT_9X18_TR                 u8g2_font_9x18_tr
#define GLCD_FONT_ADVENTURER_T_ALL        u8g2_font_adventurer_t_all
#define GLCD_FONT_ADVENTURER_TF           u8g2_font_adventurer_tf
#define GLCD_FONT_ADVENTURER_TR           u8g2_font_adventurer_tr
#define GLCD_FONT_AMSTRAD_CPC_EXTENDED_8F u8g2_font_amstrad_cpc_extended_8f
#define GLCD_FONT_AMSTRAD_CPC_EXTENDED_8N u8g2_font_amstrad_cpc_extended_8n
#define GLCD_FONT_AMSTRAD_CPC_EXTENDED_8R u8g2_font_amstrad_cpc_extended_8r
#define GLCD_FONT_AMSTRAD_CPC_EXTENDED_8U u8g2_font_amstrad_cpc_extended_8u
#define GLCD_FONT_ARTOSSANS8_8N           u8g2_font_artossans8_8n
#define GLCD_FONT_ARTOSSANS8_8R           u8g2_font_artossans8_8r
#define GLCD_FONT_ARTOSSANS8_8U           u8g2_font_artossans8_8u
#define GLCD_FONT_ARTOSSERIF8_8N          u8g2_font_artosserif8_8n
#define GLCD_FONT_ARTOSSERIF8_8R          u8g2_font_artosserif8_8r
#define GLCD_FONT_ARTOSSERIF8_8U          u8g2_font_artosserif8_8u
#define GLCD_FONT_ASTRAGAL_NBP_TF         u8g2_font_astragal_nbp_tf
#define GLCD_FONT_ASTRAGAL_NBP_TN         u8g2_font_astragal_nbp_tn
#define GLCD_FONT_ASTRAGAL_NBP_TR         u8g2_font_astragal_nbp_tr
#define GLCD_FONT_B10_B_T_JAPANESE1       u8g2_font_b10_b_t_japanese1
#define GLCD_FONT_B10_B_T_JAPANESE2       u8g2_font_b10_b_t_japanese2
#define GLCD_FONT_B10_T_JAPANESE1         u8g2_font_b10_t_japanese1
#define GLCD_FONT_B10_T_JAPANESE2         u8g2_font_b10_t_japanese2
#define GLCD_FONT_B12_B_T_JAPANESE1       u8g2_font_b12_b_t_japanese1
#define GLCD_FONT_B12_B_T_JAPANESE2       u8g2_font_b12_b_t_japanese2
#define GLCD_FONT_B12_B_T_JAPANESE3       u8g2_font_b12_b_t_japanese3
#define GLCD_FONT_B12_T_JAPANESE1         u8g2_font_b12_t_japanese1
#define GLCD_FONT_B12_T_JAPANESE2         u8g2_font_b12_t_japanese2
#define GLCD_FONT_B12_T_JAPANESE3         u8g2_font_b12_t_japanese3
#define GLCD_FONT_B16_B_T_JAPANESE1       u8g2_font_b16_b_t_japanese1
#define GLCD_FONT_B16_B_T_JAPANESE2       u8g2_font_b16_b_t_japanese2
#define GLCD_FONT_B16_B_T_JAPANESE3       u8g2_font_b16_b_t_japanese3
#define GLCD_FONT_B16_T_JAPANESE1         u8g2_font_b16_t_japanese1
#define GLCD_FONT_B16_T_JAPANESE2         u8g2_font_b16_t_japanese2
#define GLCD_FONT_B16_T_JAPANESE3         u8g2_font_b16_t_japanese3
#define GLCD_FONT_BABY_TF                 u8g2_font_baby_tf
#define GLCD_FONT_BABY_TN                 u8g2_font_baby_tn
#define GLCD_FONT_BABY_TR                 u8g2_font_baby_tr
#define GLCD_FONT_BALTHASAR_REGULAR_NBP_TF u8g2_font_balthasar_regular_nbp_tf
#define GLCD_FONT_BALTHASAR_REGULAR_NBP_TN u8g2_font_balthasar_regular_nbp_tn
#define GLCD_FONT_BALTHASAR_REGULAR_NBP_TR u8g2_font_balthasar_regular_nbp_tr
#define GLCD_FONT_BALTHASAR_TITLING_NBP_TF u8g2_font_balthasar_titling_nbp_tf
#define GLCD_FONT_BALTHASAR_TITLING_NBP_TN u8g2_font_balthasar_titling_nbp_tn
#define GLCD_FONT_BALTHASAR_TITLING_NBP_TR u8g2_font_balthasar_titling_nbp_tr
#define GLCD_FONT_BATTERY19_TN            u8g2_font_battery19_tn
#define GLCD_FONT_BAUHAUS2015_TN          u8g2_font_bauhaus2015_tn
#define GLCD_FONT_BAUHAUS2015_TR          u8g2_font_bauhaus2015_tr
#define GLCD_FONT_BBSESQUE_TE             u8g2_font_BBSesque_te
#define GLCD_FONT_BBSESQUE_TF             u8g2_font_BBSesque_tf
#define GLCD_FONT_BBSESQUE_TR             u8g2_font_BBSesque_tr
#define GLCD_FONT_BEANSTALK_MEL_TN        u8g2_font_beanstalk_mel_tn
#define GLCD_FONT_BEANSTALK_MEL_TR        u8g2_font_beanstalk_mel_tr
#define GLCD_FONT_BITCASUAL_T_ALL         u8g2_font_bitcasual_t_all
#define GLCD_FONT_BITCASUAL_TF            u8g2_font_bitcasual_tf
#define GLCD_FONT_BITCASUAL_TN            u8g2_font_bitcasual_tn
#define GLCD_FONT_BITCASUAL_TR            u8g2_font_bitcasual_tr
#define GLCD_FONT_BITCASUAL_TU            u8g2_font_bitcasual_tu
#define GLCD_FONT_BITTYPEWRITER_TE        u8g2_font_BitTypeWriter_te
#define GLCD_FONT_BITTYPEWRITER_TR        u8g2_font_BitTypeWriter_tr
#define GLCD_FONT_BLIPFEST_07_TN          u8g2_font_blipfest_07_tn
#define GLCD_FONT_BLIPFEST_07_TR          u8g2_font_blipfest_07_tr
#define GLCD_FONT_BORN2BSPORTYSLAB_T_ALL  u8g2_font_Born2bSportySlab_t_all
#define GLCD_FONT_BORN2BSPORTYSLAB_TE     u8g2_font_Born2bSportySlab_te
#define GLCD_FONT_BORN2BSPORTYSLAB_TF     u8g2_font_Born2bSportySlab_tf
#define GLCD_FONT_BORN2BSPORTYSLAB_TR     u8g2_font_Born2bSportySlab_tr
#define GLCD_FONT_BORN2BSPORTYV2_TE       u8g2_font_Born2bSportyV2_te
#define GLCD_FONT_BORN2BSPORTYV2_TF       u8g2_font_Born2bSportyV2_tf
#define GLCD_FONT_BORN2BSPORTYV2_TR       u8g2_font_Born2bSportyV2_tr
#define GLCD_FONT_BRACKETEDBABIES_TR      u8g2_font_bracketedbabies_tr
#define GLCD_FONT_BUBBLE_TN               u8g2_font_bubble_tn
#define GLCD_FONT_BUBBLE_TR               u8g2_font_bubble_tr
#define GLCD_FONT_CALIBRATION_GOTHIC_NBP_T_ALL u8g2_font_calibration_gothic_nbp_t_all
#define GLCD_FONT_CALIBRATION_GOTHIC_NBP_TF u8g2_font_calibration_gothic_nbp_tf
#define GLCD_FONT_CALIBRATION_GOTHIC_NBP_TN u8g2_font_calibration_gothic_nbp_tn
#define GLCD_FONT_CALIBRATION_GOTHIC_NBP_TR u8g2_font_calibration_gothic_nbp_tr
#define GLCD_FONT_CARDIMON_PIXEL_TF       u8g2_font_cardimon_pixel_tf
#define GLCD_FONT_CARDIMON_PIXEL_TN       u8g2_font_cardimon_pixel_tn
#define GLCD_FONT_CARDIMON_PIXEL_TR       u8g2_font_cardimon_pixel_tr
#define GLCD_FONT_CELIBATEMONK_TR         u8g2_font_celibatemonk_tr
#define GLCD_FONT_CHIKITA_TF              u8g2_font_chikita_tf
#define GLCD_FONT_CHIKITA_TN              u8g2_font_chikita_tn
#define GLCD_FONT_CHIKITA_TR              u8g2_font_chikita_tr
#define GLCD_FONT_CHROMA48MEDIUM8_8N      u8g2_font_chroma48medium8_8n
#define GLCD_FONT_CHROMA48MEDIUM8_8R      u8g2_font_chroma48medium8_8r
#define GLCD_FONT_CHROMA48MEDIUM8_8U      u8g2_font_chroma48medium8_8u
#define GLCD_FONT_COURB08_TF              u8g2_font_courB08_tf
#define GLCD_FONT_COURB08_TN              u8g2_font_courB08_tn
#define GLCD_FONT_COURB08_TR              u8g2_font_courB08_tr
#define GLCD_FONT_COURB10_TF              u8g2_font_courB10_tf
#define GLCD_FONT_COURB10_TN              u8g2_font_courB10_tn
#define GLCD_FONT_COURB10_TR              u8g2_font_courB10_tr
#define GLCD_FONT_COURB12_TF              u8g2_font_courB12_tf
#define GLCD_FONT_COURB12_TN              u8g2_font_courB12_tn
#define GLCD_FONT_COURB12_TR              u8g2_font_courB12_tr
#define GLCD_FONT_COURB14_TF              u8g2_font_courB14_tf
#define GLCD_FONT_COURB14_TN              u8g2_font_courB14_tn
#define GLCD_FONT_COURB14_TR              u8g2_font_courB14_tr
#define GLCD_FONT_COURB18_TF              u8g2_font_courB18_tf
#define GLCD_FONT_COURB18_TN              u8g2_font_courB18_tn
#define GLCD_FONT_COURB18_TR              u8g2_font_courB18_tr
#define GLCD_FONT_COURB24_TF              u8g2_font_courB24_tf
#define GLCD_FONT_COURB24_TN              u8g2_font_courB24_tn
#define GLCD_FONT_COURB24_TR              u8g2_font_courB24_tr
#define GLCD_FONT_COURR08_TF              u8g2_font_courR08_tf
#define GLCD_FONT_COURR08_TN              u8g2_font_courR08_tn
#define GLCD_FONT_COURR08_TR              u8g2_font_courR08_tr
#define GLCD_FONT_COURR10_TF              u8g2_font_courR10_tf
#define GLCD_FONT_COURR10_TN              u8g2_font_courR10_tn
#define GLCD_FONT_COURR10_TR              u8g2_font_courR10_tr
#define GLCD_FONT_COURR12_TF              u8g2_font_courR12_tf
#define GLCD_FONT_COURR12_TN              u8g2_font_courR12_tn
#define GLCD_FONT_COURR12_TR              u8g2_font_courR12_tr
#define GLCD_FONT_COURR14_TF              u8g2_font_courR14_tf
#define GLCD_FONT_COURR14_TN              u8g2_font_courR14_tn
#define GLCD_FONT_COURR14_TR              u8g2_font_courR14_tr
#define GLCD_FONT_COURR18_TF              u8g2_font_courR18_tf
#define GLCD_FONT_COURR18_TN              u8g2_font_courR18_tn
#define GLCD_FONT_COURR18_TR              u8g2_font_courR18_tr
#define GLCD_FONT_COURR24_TF              u8g2_font_courR24_tf
#define GLCD_FONT_COURR24_TN              u8g2_font_courR24_tn
#define GLCD_FONT_COURR24_TR              u8g2_font_courR24_tr
#define GLCD_FONT_CROX1CB_MF              u8g2_font_crox1cb_mf
#define GLCD_FONT_CROX1CB_MN              u8g2_font_crox1cb_mn
#define GLCD_FONT_CROX1CB_MR              u8g2_font_crox1cb_mr
#define GLCD_FONT_CROX1CB_TF              u8g2_font_crox1cb_tf
#define GLCD_FONT_CROX1CB_TN              u8g2_font_crox1cb_tn
#define GLCD_FONT_CROX1CB_TR              u8g2_font_crox1cb_tr
#define GLCD_FONT_CROX1C_MF               u8g2_font_crox1c_mf
#define GLCD_FONT_CROX1C_MN               u8g2_font_crox1c_mn
#define GLCD_FONT_CROX1C_MR               u8g2_font_crox1c_mr
#define GLCD_FONT_CROX1C_TF               u8g2_font_crox1c_tf
#define GLCD_FONT_CROX1C_TN               u8g2_font_crox1c_tn
#define GLCD_FONT_CROX1C_TR               u8g2_font_crox1c_tr
#define GLCD_FONT_CROX1HB_TF              u8g2_font_crox1hb_tf
#define GLCD_FONT_CROX1HB_TN              u8g2_font_crox1hb_tn
#define GLCD_FONT_CROX1HB_TR              u8g2_font_crox1hb_tr
#define GLCD_FONT_CROX1H_TF               u8g2_font_crox1h_tf
#define GLCD_FONT_CROX1H_TN               u8g2_font_crox1h_tn
#define GLCD_FONT_CROX1H_TR               u8g2_font_crox1h_tr
#define GLCD_FONT_CROX1TB_TF              u8g2_font_crox1tb_tf
#define GLCD_FONT_CROX1TB_TN              u8g2_font_crox1tb_tn
#define GLCD_FONT_CROX1TB_TR              u8g2_font_crox1tb_tr
#define GLCD_FONT_CROX1T_TF               u8g2_font_crox1t_tf
#define GLCD_FONT_CROX1T_TN               u8g2_font_crox1t_tn
#define GLCD_FONT_CROX1T_TR               u8g2_font_crox1t_tr
#define GLCD_FONT_CROX2CB_MF              u8g2_font_crox2cb_mf
#define GLCD_FONT_CROX2CB_MN              u8g2_font_crox2cb_mn
#define GLCD_FONT_CROX2CB_MR              u8g2_font_crox2cb_mr
#define GLCD_FONT_CROX2CB_TF              u8g2_font_crox2cb_tf
#define GLCD_FONT_CROX2CB_TN              u8g2_font_crox2cb_tn
#define GLCD_FONT_CROX2CB_TR              u8g2_font_crox2cb_tr
#define GLCD_FONT_CROX2C_MF               u8g2_font_crox2c_mf
#define GLCD_FONT_CROX2C_MN               u8g2_font_crox2c_mn
#define GLCD_FONT_CROX2C_MR               u8g2_font_crox2c_mr
#define GLCD_FONT_CROX2C_TF               u8g2_font_crox2c_tf
#define GLCD_FONT_CROX2C_TN               u8g2_font_crox2c_tn
#define GLCD_FONT_CROX2C_TR               u8g2_font_crox2c_tr
#define GLCD_FONT_CROX2HB_TF              u8g2_font_crox2hb_tf
#define GLCD_FONT_CROX2HB_TN              u8g2_font_crox2hb_tn
#define GLCD_FONT_CROX2HB_TR              u8g2_font_crox2hb_tr
#define GLCD_FONT_CROX2H_TF               u8g2_font_crox2h_tf
#define GLCD_FONT_CROX2H_TN               u8g2_font_crox2h_tn
#define GLCD_FONT_CROX2H_TR               u8g2_font_crox2h_tr
#define GLCD_FONT_CROX2TB_TF              u8g2_font_crox2tb_tf
#define GLCD_FONT_CROX2TB_TN              u8g2_font_crox2tb_tn
#define GLCD_FONT_CROX2TB_TR              u8g2_font_crox2tb_tr
#define GLCD_FONT_CROX2T_TF               u8g2_font_crox2t_tf
#define GLCD_FONT_CROX2T_TN               u8g2_font_crox2t_tn
#define GLCD_FONT_CROX2T_TR               u8g2_font_crox2t_tr
#define GLCD_FONT_CROX3CB_MF              u8g2_font_crox3cb_mf
#define GLCD_FONT_CROX3CB_MN              u8g2_font_crox3cb_mn
#define GLCD_FONT_CROX3CB_MR              u8g2_font_crox3cb_mr
#define GLCD_FONT_CROX3CB_TF              u8g2_font_crox3cb_tf
#define GLCD_FONT_CROX3CB_TN              u8g2_font_crox3cb_tn
#define GLCD_FONT_CROX3CB_TR              u8g2_font_crox3cb_tr
#define GLCD_FONT_CROX3C_MF               u8g2_font_crox3c_mf
#define GLCD_FONT_CROX3C_MN               u8g2_font_crox3c_mn
#define GLCD_FONT_CROX3C_MR               u8g2_font_crox3c_mr
#define GLCD_FONT_CROX3C_TF               u8g2_font_crox3c_tf
#define GLCD_FONT_CROX3C_TN               u8g2_font_crox3c_tn
#define GLCD_FONT_CROX3C_TR               u8g2_font_crox3c_tr
#define GLCD_FONT_CROX3HB_TF              u8g2_font_crox3hb_tf
#define GLCD_FONT_CROX3HB_TN              u8g2_font_crox3hb_tn
#define GLCD_FONT_CROX3HB_TR              u8g2_font_crox3hb_tr
#define GLCD_FONT_CROX3H_TF               u8g2_font_crox3h_tf
#define GLCD_FONT_CROX3H_TN               u8g2_font_crox3h_tn
#define GLCD_FONT_CROX3H_TR               u8g2_font_crox3h_tr
#define GLCD_FONT_CROX3TB_TF              u8g2_font_crox3tb_tf
#define GLCD_FONT_CROX3TB_TN              u8g2_font_crox3tb_tn
#define GLCD_FONT_CROX3TB_TR              u8g2_font_crox3tb_tr
#define GLCD_FONT_CROX3T_TF               u8g2_font_crox3t_tf
#define GLCD_FONT_CROX3T_TN               u8g2_font_crox3t_tn
#define GLCD_FONT_CROX3T_TR               u8g2_font_crox3t_tr
#define GLCD_FONT_CROX4HB_TF              u8g2_font_crox4hb_tf
#define GLCD_FONT_CROX4HB_TN              u8g2_font_crox4hb_tn
#define GLCD_FONT_CROX4HB_TR              u8g2_font_crox4hb_tr
#define GLCD_FONT_CROX4H_TF               u8g2_font_crox4h_tf
#define GLCD_FONT_CROX4H_TN               u8g2_font_crox4h_tn
#define GLCD_FONT_CROX4H_TR               u8g2_font_crox4h_tr
#define GLCD_FONT_CROX4TB_TF              u8g2_font_crox4tb_tf
#define GLCD_FONT_CROX4TB_TN              u8g2_font_crox4tb_tn
#define GLCD_FONT_CROX4TB_TR              u8g2_font_crox4tb_tr
#define GLCD_FONT_CROX4T_TF               u8g2_font_crox4t_tf
#define GLCD_FONT_CROX4T_TN               u8g2_font_crox4t_tn
#define GLCD_FONT_CROX4T_TR               u8g2_font_crox4t_tr
#define GLCD_FONT_CROX5HB_TF              u8g2_font_crox5hb_tf
#define GLCD_FONT_CROX5HB_TN              u8g2_font_crox5hb_tn
#define GLCD_FONT_CROX5HB_TR              u8g2_font_crox5hb_tr
#define GLCD_FONT_CROX5H_TF               u8g2_font_crox5h_tf
#define GLCD_FONT_CROX5H_TN               u8g2_font_crox5h_tn
#define GLCD_FONT_CROX5H_TR               u8g2_font_crox5h_tr
#define GLCD_FONT_CROX5TB_TF              u8g2_font_crox5tb_tf
#define GLCD_FONT_CROX5TB_TN              u8g2_font_crox5tb_tn
#define GLCD_FONT_CROX5TB_TR              u8g2_font_crox5tb_tr
#define GLCD_FONT_CROX5T_TF               u8g2_font_crox5t_tf
#define GLCD_FONT_CROX5T_TN               u8g2_font_crox5t_tn
#define GLCD_FONT_CROX5T_TR               u8g2_font_crox5t_tr
#define GLCD_FONT_CU12_HE                 u8g2_font_cu12_he
#define GLCD_FONT_CU12_HF                 u8g2_font_cu12_hf
#define GLCD_FONT_CU12_HN                 u8g2_font_cu12_hn
#define GLCD_FONT_CU12_HR                 u8g2_font_cu12_hr
#define GLCD_FONT_CU12_H_SYMBOLS          u8g2_font_cu12_h_symbols
#define GLCD_FONT_CU12_ME                 u8g2_font_cu12_me
#define GLCD_FONT_CU12_MF                 u8g2_font_cu12_mf
#define GLCD_FONT_CU12_MN                 u8g2_font_cu12_mn
#define GLCD_FONT_CU12_MR                 u8g2_font_cu12_mr
#define GLCD_FONT_CU12_T_ARABIC           u8g2_font_cu12_t_arabic
#define GLCD_FONT_CU12_T_CYRILLIC         u8g2_font_cu12_t_cyrillic
#define GLCD_FONT_CU12_TE                 u8g2_font_cu12_te
#define GLCD_FONT_CU12_TF                 u8g2_font_cu12_tf
#define GLCD_FONT_CU12_T_GREEK            u8g2_font_cu12_t_greek
#define GLCD_FONT_CU12_T_HEBREW           u8g2_font_cu12_t_hebrew
#define GLCD_FONT_CU12_TN                 u8g2_font_cu12_tn
#define GLCD_FONT_CU12_TR                 u8g2_font_cu12_tr
#define GLCD_FONT_CU12_T_SYMBOLS          u8g2_font_cu12_t_symbols
#define GLCD_FONT_CU12_T_TIBETAN          u8g2_font_cu12_t_tibetan
#define GLCD_FONT_CUBE_MEL_TN             u8g2_font_cube_mel_tn
#define GLCD_FONT_CUBE_MEL_TR             u8g2_font_cube_mel_tr
#define GLCD_FONT_CUPCAKEMETOYOURLEADER_TN u8g2_font_cupcakemetoyourleader_tn
#define GLCD_FONT_CUPCAKEMETOYOURLEADER_TR u8g2_font_cupcakemetoyourleader_tr
#define GLCD_FONT_CUPCAKEMETOYOURLEADER_TU u8g2_font_cupcakemetoyourleader_tu
#define GLCD_FONT_CURSIVEPIXEL_TR         u8g2_font_CursivePixel_tr
#define GLCD_FONT_CURSOR_TF               u8g2_font_cursor_tf
#define GLCD_FONT_CURSOR_TR               u8g2_font_cursor_tr
#define GLCD_FONT_DIODESEMIMONO_TR        u8g2_font_diodesemimono_tr
#define GLCD_FONT_DISRESPECTFULTEENAGER_TU u8g2_font_disrespectfulteenager_tu
#define GLCD_FONT_EMOTICONS21_TR          u8g2_font_emoticons21_tr
#define GLCD_FONT_ENGRISH_TF              u8g2_font_Engrish_tf
#define GLCD_FONT_ENGRISH_TR              u8g2_font_Engrish_tr
#define GLCD_FONT_ETL14THAI_T             u8g2_font_etl14thai_t
#define GLCD_FONT_ETL16THAI_T             u8g2_font_etl16thai_t
#define GLCD_FONT_ETL24THAI_T             u8g2_font_etl24thai_t
#define GLCD_FONT_F10_B_T_JAPANESE1       u8g2_font_f10_b_t_japanese1
#define GLCD_FONT_F10_B_T_JAPANESE2       u8g2_font_f10_b_t_japanese2
#define GLCD_FONT_F10_T_JAPANESE1         u8g2_font_f10_t_japanese1
#define GLCD_FONT_F10_T_JAPANESE2         u8g2_font_f10_t_japanese2
#define GLCD_FONT_F12_B_T_JAPANESE1       u8g2_font_f12_b_t_japanese1
#define GLCD_FONT_F12_B_T_JAPANESE2       u8g2_font_f12_b_t_japanese2
#define GLCD_FONT_F12_T_JAPANESE1         u8g2_font_f12_t_japanese1
#define GLCD_FONT_F12_T_JAPANESE2         u8g2_font_f12_t_japanese2
#define GLCD_FONT_F16_B_T_JAPANESE1       u8g2_font_f16_b_t_japanese1
#define GLCD_FONT_F16_B_T_JAPANESE2       u8g2_font_f16_b_t_japanese2
#define GLCD_FONT_F16_T_JAPANESE1         u8g2_font_f16_t_japanese1
#define GLCD_FONT_F16_T_JAPANESE2         u8g2_font_f16_t_japanese2
#define GLCD_FONT_FANCYPIXELS_TF          u8g2_font_fancypixels_tf
#define GLCD_FONT_FANCYPIXELS_TR          u8g2_font_fancypixels_tr
#define GLCD_FONT_FEWTURE_TF              u8g2_font_fewture_tf
#define GLCD_FONT_FEWTURE_TN              u8g2_font_fewture_tn
#define GLCD_FONT_FEWTURE_TR              u8g2_font_fewture_tr
#define GLCD_FONT_FINDERSKEEPERS_TF       u8g2_font_finderskeepers_tf
#define GLCD_FONT_FINDERSKEEPERS_TN       u8g2_font_finderskeepers_tn
#define GLCD_FONT_FINDERSKEEPERS_TR       u8g2_font_finderskeepers_tr
#define GLCD_FONT_FREEDOOMR10_MU          u8g2_font_freedoomr10_mu
#define GLCD_FONT_FREEDOOMR10_TU          u8g2_font_freedoomr10_tu
#define GLCD_FONT_FREEDOOMR25_MN          u8g2_font_freedoomr25_mn
#define GLCD_FONT_FREEDOOMR25_TN          u8g2_font_freedoomr25_tn
#define GLCD_FONT_FRIKATIV_T_ALL          u8g2_font_frikativ_t_all
#define GLCD_FONT_FRIKATIV_TF             u8g2_font_frikativ_tf
#define GLCD_FONT_FRIKATIV_TR             u8g2_font_frikativ_tr
#define GLCD_FONT_FUB11_TF                u8g2_font_fub11_tf
#define GLCD_FONT_FUB11_TN                u8g2_font_fub11_tn
#define GLCD_FONT_FUB11_TR                u8g2_font_fub11_tr
#define GLCD_FONT_FUB11_T_SYMBOL          u8g2_font_fub11_t_symbol
#define GLCD_FONT_FUB14_TF                u8g2_font_fub14_tf
#define GLCD_FONT_FUB14_TN                u8g2_font_fub14_tn
#define GLCD_FONT_FUB14_TR                u8g2_font_fub14_tr
#define GLCD_FONT_FUB14_T_SYMBOL          u8g2_font_fub14_t_symbol
#define GLCD_FONT_FUB17_TF                u8g2_font_fub17_tf
#define GLCD_FONT_FUB17_TN                u8g2_font_fub17_tn
#define GLCD_FONT_FUB17_TR                u8g2_font_fub17_tr
#define GLCD_FONT_FUB17_T_SYMBOL          u8g2_font_fub17_t_symbol
#define GLCD_FONT_FUB20_TF                u8g2_font_fub20_tf
#define GLCD_FONT_FUB20_TN                u8g2_font_fub20_tn
#define GLCD_FONT_FUB20_TR                u8g2_font_fub20_tr
#define GLCD_FONT_FUB20_T_SYMBOL          u8g2_font_fub20_t_symbol
#define GLCD_FONT_FUB25_TF                u8g2_font_fub25_tf
#define GLCD_FONT_FUB25_TN                u8g2_font_fub25_tn
#define GLCD_FONT_FUB25_TR                u8g2_font_fub25_tr
#define GLCD_FONT_FUB25_T_SYMBOL          u8g2_font_fub25_t_symbol
#define GLCD_FONT_FUB30_TF                u8g2_font_fub30_tf
#define GLCD_FONT_FUB30_TN                u8g2_font_fub30_tn
#define GLCD_FONT_FUB30_TR                u8g2_font_fub30_tr
#define GLCD_FONT_FUB30_T_SYMBOL          u8g2_font_fub30_t_symbol
#define GLCD_FONT_FUB35_TF                u8g2_font_fub35_tf
#define GLCD_FONT_FUB35_TN                u8g2_font_fub35_tn
#define GLCD_FONT_FUB35_TR                u8g2_font_fub35_tr
#define GLCD_FONT_FUB35_T_SYMBOL          u8g2_font_fub35_t_symbol
#define GLCD_FONT_FUB42_TF                u8g2_font_fub42_tf
#define GLCD_FONT_FUB42_TN                u8g2_font_fub42_tn
#define GLCD_FONT_FUB42_TR                u8g2_font_fub42_tr
#define GLCD_FONT_FUB42_T_SYMBOL          u8g2_font_fub42_t_symbol
#define GLCD_FONT_FUB49_TN                u8g2_font_fub49_tn
#define GLCD_FONT_FUB49_T_SYMBOL          u8g2_font_fub49_t_symbol
#define GLCD_FONT_FUR11_TF                u8g2_font_fur11_tf
#define GLCD_FONT_FUR11_TN                u8g2_font_fur11_tn
#define GLCD_FONT_FUR11_TR                u8g2_font_fur11_tr
#define GLCD_FONT_FUR11_T_SYMBOL          u8g2_font_fur11_t_symbol
#define GLCD_FONT_FUR14_TF                u8g2_font_fur14_tf
#define GLCD_FONT_FUR14_TN                u8g2_font_fur14_tn
#define GLCD_FONT_FUR14_TR                u8g2_font_fur14_tr
#define GLCD_FONT_FUR14_T_SYMBOL          u8g2_font_fur14_t_symbol
#define GLCD_FONT_FUR17_TF                u8g2_font_fur17_tf
#define GLCD_FONT_FUR17_TN                u8g2_font_fur17_tn
#define GLCD_FONT_FUR17_TR                u8g2_font_fur17_tr
#define GLCD_FONT_FUR17_T_SYMBOL          u8g2_font_fur17_t_symbol
#define GLCD_FONT_FUR20_TF                u8g2_font_fur20_tf
#define GLCD_FONT_FUR20_TN                u8g2_font_fur20_tn
#define GLCD_FONT_FUR20_TR                u8g2_font_fur20_tr
#define GLCD_FONT_FUR20_T_SYMBOL          u8g2_font_fur20_t_symbol
#define GLCD_FONT_FUR25_TF                u8g2_font_fur25_tf
#define GLCD_FONT_FUR25_TN                u8g2_font_fur25_tn
#define GLCD_FONT_FUR25_TR                u8g2_font_fur25_tr
#define GLCD_FONT_FUR25_T_SYMBOL          u8g2_font_fur25_t_symbol
#define GLCD_FONT_FUR30_TF                u8g2_font_fur30_tf
#define GLCD_FONT_FUR30_TN                u8g2_font_fur30_tn
#define GLCD_FONT_FUR30_TR                u8g2_font_fur30_tr
#define GLCD_FONT_FUR30_T_SYMBOL          u8g2_font_fur30_t_symbol
#define GLCD_FONT_FUR35_TF                u8g2_font_fur35_tf
#define GLCD_FONT_FUR35_TN                u8g2_font_fur35_tn
#define GLCD_FONT_FUR35_TR                u8g2_font_fur35_tr
#define GLCD_FONT_FUR35_T_SYMBOL          u8g2_font_fur35_t_symbol
#define GLCD_FONT_FUR42_TF                u8g2_font_fur42_tf
#define GLCD_FONT_FUR42_TN                u8g2_font_fur42_tn
#define GLCD_FONT_FUR42_TR                u8g2_font_fur42_tr
#define GLCD_FONT_FUR42_T_SYMBOL          u8g2_font_fur42_t_symbol
#define GLCD_FONT_FUR49_TN                u8g2_font_fur49_tn
#define GLCD_FONT_FUR49_T_SYMBOL          u8g2_font_fur49_t_symbol
#define GLCD_FONT_GANJ_NAMEH_SANS10_T_ALL u8g2_font_ganj_nameh_sans10_t_all
#define GLCD_FONT_GANJ_NAMEH_SANS12_T_ALL u8g2_font_ganj_nameh_sans12_t_all
#define GLCD_FONT_GANJ_NAMEH_SANS14_T_ALL u8g2_font_ganj_nameh_sans14_t_all
#define GLCD_FONT_GANJ_NAMEH_SANS16_T_ALL u8g2_font_ganj_nameh_sans16_t_all
#define GLCD_FONT_GB16ST_T_1              u8g2_font_gb16st_t_1
#define GLCD_FONT_GB16ST_T_2              u8g2_font_gb16st_t_2
#define GLCD_FONT_GB16ST_T_3              u8g2_font_gb16st_t_3
#define GLCD_FONT_GB24ST_T_1              u8g2_font_gb24st_t_1
#define GLCD_FONT_GB24ST_T_2              u8g2_font_gb24st_t_2
#define GLCD_FONT_GB24ST_T_3              u8g2_font_gb24st_t_3
#define GLCD_FONT_GEORGIA7PX_TE           u8g2_font_Georgia7px_te
#define GLCD_FONT_GEORGIA7PX_TF           u8g2_font_Georgia7px_tf
#define GLCD_FONT_GEORGIA7PX_TR           u8g2_font_Georgia7px_tr
#define GLCD_FONT_GLASSTOWN_NBP_T_ALL     u8g2_font_glasstown_nbp_t_all
#define GLCD_FONT_GLASSTOWN_NBP_TF        u8g2_font_glasstown_nbp_tf
#define GLCD_FONT_GLASSTOWN_NBP_TN        u8g2_font_glasstown_nbp_tn
#define GLCD_FONT_GLASSTOWN_NBP_TR        u8g2_font_glasstown_nbp_tr
#define GLCD_FONT_GUILDENSTERN_NBP_T_ALL  u8g2_font_guildenstern_nbp_t_all
#define GLCD_FONT_GUILDENSTERN_NBP_TF     u8g2_font_guildenstern_nbp_tf
#define GLCD_FONT_GUILDENSTERN_NBP_TN     u8g2_font_guildenstern_nbp_tn
#define GLCD_FONT_GUILDENSTERN_NBP_TR     u8g2_font_guildenstern_nbp_tr
#define GLCD_FONT_HABSBURGCHANCERY_T_ALL  u8g2_font_habsburgchancery_t_all
#define GLCD_FONT_HABSBURGCHANCERY_TF     u8g2_font_habsburgchancery_tf
#define GLCD_FONT_HABSBURGCHANCERY_TN     u8g2_font_habsburgchancery_tn
#define GLCD_FONT_HABSBURGCHANCERY_TR     u8g2_font_habsburgchancery_tr
#define GLCD_FONT_HALFTONE_TF             u8g2_font_halftone_tf
#define GLCD_FONT_HALFTONE_TN             u8g2_font_halftone_tn
#define GLCD_FONT_HALFTONE_TR             u8g2_font_halftone_tr
#define GLCD_FONT_HAXRCORP4089_T_CYRILLIC u8g2_font_haxrcorp4089_t_cyrillic
#define GLCD_FONT_HAXRCORP4089_TN         u8g2_font_haxrcorp4089_tn
#define GLCD_FONT_HAXRCORP4089_TR         u8g2_font_haxrcorp4089_tr
#define GLCD_FONT_HEAVYBOTTOM_TR          u8g2_font_heavybottom_tr
#define GLCD_FONT_HELVB08_TE              u8g2_font_helvB08_te
#define GLCD_FONT_HELVB08_TF              u8g2_font_helvB08_tf
#define GLCD_FONT_HELVB08_TN              u8g2_font_helvB08_tn
#define GLCD_FONT_HELVB08_TR              u8g2_font_helvB08_tr
#define GLCD_FONT_HELVB10_TE              u8g2_font_helvB10_te
#define GLCD_FONT_HELVB10_TF              u8g2_font_helvB10_tf
#define GLCD_FONT_HELVB10_TN              u8g2_font_helvB10_tn
#define GLCD_FONT_HELVB10_TR              u8g2_font_helvB10_tr
#define GLCD_FONT_HELVB12_TE              u8g2_font_helvB12_te
#define GLCD_FONT_HELVB12_TF              u8g2_font_helvB12_tf
#define GLCD_FONT_HELVB12_TN              u8g2_font_helvB12_tn
#define GLCD_FONT_HELVB12_TR              u8g2_font_helvB12_tr
#define GLCD_FONT_HELVB14_TE              u8g2_font_helvB14_te
#define GLCD_FONT_HELVB14_TF              u8g2_font_helvB14_tf
#define GLCD_FONT_HELVB14_TN              u8g2_font_helvB14_tn
#define GLCD_FONT_HELVB14_TR              u8g2_font_helvB14_tr
#define GLCD_FONT_HELVB18_TE              u8g2_font_helvB18_te
#define GLCD_FONT_HELVB18_TF              u8g2_font_helvB18_tf
#define GLCD_FONT_HELVB18_TN              u8g2_font_helvB18_tn
#define GLCD_FONT_HELVB18_TR              u8g2_font_helvB18_tr
#define GLCD_FONT_HELVB24_TE              u8g2_font_helvB24_te
#define GLCD_FONT_HELVB24_TF              u8g2_font_helvB24_tf
#define GLCD_FONT_HELVB24_TN              u8g2_font_helvB24_tn
#define GLCD_FONT_HELVB24_TR              u8g2_font_helvB24_tr
#define GLCD_FONT_HELVETIPIXELOUTLINE_TE  u8g2_font_HelvetiPixelOutline_te
#define GLCD_FONT_HELVETIPIXELOUTLINE_TR  u8g2_font_HelvetiPixelOutline_tr
#define GLCD_FONT_HELVETIPIXEL_TR         u8g2_font_HelvetiPixel_tr
#define GLCD_FONT_HELVR08_TE              u8g2_font_helvR08_te
#define GLCD_FONT_HELVR08_TF              u8g2_font_helvR08_tf
#define GLCD_FONT_HELVR08_TN              u8g2_font_helvR08_tn
#define GLCD_FONT_HELVR08_TR              u8g2_font_helvR08_tr
#define GLCD_FONT_HELVR10_TE              u8g2_font_helvR10_te
#define GLCD_FONT_HELVR10_TF              u8g2_font_helvR10_tf
#define GLCD_FONT_HELVR10_TN              u8g2_font_helvR10_tn
#define GLCD_FONT_HELVR10_TR              u8g2_font_helvR10_tr
#define GLCD_FONT_HELVR12_TE              u8g2_font_helvR12_te
#define GLCD_FONT_HELVR12_TF              u8g2_font_helvR12_tf
#define GLCD_FONT_HELVR12_TN              u8g2_font_helvR12_tn
#define GLCD_FONT_HELVR12_TR              u8g2_font_helvR12_tr
#define GLCD_FONT_HELVR14_TE              u8g2_font_helvR14_te
#define GLCD_FONT_HELVR14_TF              u8g2_font_helvR14_tf
#define GLCD_FONT_HELVR14_TN              u8g2_font_helvR14_tn
#define GLCD_FONT_HELVR14_TR              u8g2_font_helvR14_tr
#define GLCD_FONT_HELVR18_TE              u8g2_font_helvR18_te
#define GLCD_FONT_HELVR18_TF              u8g2_font_helvR18_tf
#define GLCD_FONT_HELVR18_TN              u8g2_font_helvR18_tn
#define GLCD_FONT_HELVR18_TR              u8g2_font_helvR18_tr
#define GLCD_FONT_HELVR24_TE              u8g2_font_helvR24_te
#define GLCD_FONT_HELVR24_TF              u8g2_font_helvR24_tf
#define GLCD_FONT_HELVR24_TN              u8g2_font_helvR24_tn
#define GLCD_FONT_HELVR24_TR              u8g2_font_helvR24_tr
#define GLCD_FONT_ICONQUADPIX_M_ALL       u8g2_font_iconquadpix_m_all
#define GLCD_FONT_IMPACTBITS_TR           u8g2_font_ImpactBits_tr
#define GLCD_FONT_INB16_MF                u8g2_font_inb16_mf
#define GLCD_FONT_INB16_MN                u8g2_font_inb16_mn
#define GLCD_FONT_INB16_MR                u8g2_font_inb16_mr
#define GLCD_FONT_INB19_MF                u8g2_font_inb19_mf
#define GLCD_FONT_INB19_MN                u8g2_font_inb19_mn
#define GLCD_FONT_INB19_MR                u8g2_font_inb19_mr
#define GLCD_FONT_INB21_MF                u8g2_font_inb21_mf
#define GLCD_FONT_INB21_MN                u8g2_font_inb21_mn
#define GLCD_FONT_INB21_MR                u8g2_font_inb21_mr
#define GLCD_FONT_INB24_MF                u8g2_font_inb24_mf
#define GLCD_FONT_INB24_MN                u8g2_font_inb24_mn
#define GLCD_FONT_INB24_MR                u8g2_font_inb24_mr
#define GLCD_FONT_INB27_MF                u8g2_font_inb27_mf
#define GLCD_FONT_INB27_MN                u8g2_font_inb27_mn
#define GLCD_FONT_INB27_MR                u8g2_font_inb27_mr
#define GLCD_FONT_INB30_MF                u8g2_font_inb30_mf
#define GLCD_FONT_INB30_MN                u8g2_font_inb30_mn
#define GLCD_FONT_INB30_MR                u8g2_font_inb30_mr
#define GLCD_FONT_INB33_MF                u8g2_font_inb33_mf
#define GLCD_FONT_INB33_MN                u8g2_font_inb33_mn
#define GLCD_FONT_INB33_MR                u8g2_font_inb33_mr
#define GLCD_FONT_INB38_MF                u8g2_font_inb38_mf
#define GLCD_FONT_INB38_MN                u8g2_font_inb38_mn
#define GLCD_FONT_INB38_MR                u8g2_font_inb38_mr
#define GLCD_FONT_INB42_MF                u8g2_font_inb42_mf
#define GLCD_FONT_INB42_MN                u8g2_font_inb42_mn
#define GLCD_FONT_INB42_MR                u8g2_font_inb42_mr
#define GLCD_FONT_INB46_MF                u8g2_font_inb46_mf
#define GLCD_FONT_INB46_MN                u8g2_font_inb46_mn
#define GLCD_FONT_INB46_MR                u8g2_font_inb46_mr
#define GLCD_FONT_INB49_MF                u8g2_font_inb49_mf
#define GLCD_FONT_INB49_MN                u8g2_font_inb49_mn
#define GLCD_FONT_INB49_MR                u8g2_font_inb49_mr
#define GLCD_FONT_INB53_MF                u8g2_font_inb53_mf
#define GLCD_FONT_INB53_MN                u8g2_font_inb53_mn
#define GLCD_FONT_INB53_MR                u8g2_font_inb53_mr
#define GLCD_FONT_INB57_MN                u8g2_font_inb57_mn
#define GLCD_FONT_INB63_MN                u8g2_font_inb63_mn
#define GLCD_FONT_INR16_MF                u8g2_font_inr16_mf
#define GLCD_FONT_INR16_MN                u8g2_font_inr16_mn
#define GLCD_FONT_INR16_MR                u8g2_font_inr16_mr
#define GLCD_FONT_INR19_MF                u8g2_font_inr19_mf
#define GLCD_FONT_INR19_MN                u8g2_font_inr19_mn
#define GLCD_FONT_INR19_MR                u8g2_font_inr19_mr
#define GLCD_FONT_INR21_MF                u8g2_font_inr21_mf
#define GLCD_FONT_INR21_MN                u8g2_font_inr21_mn
#define GLCD_FONT_INR21_MR                u8g2_font_inr21_mr
#define GLCD_FONT_INR24_MF                u8g2_font_inr24_mf
#define GLCD_FONT_INR24_MN                u8g2_font_inr24_mn
#define GLCD_FONT_INR24_MR                u8g2_font_inr24_mr
#define GLCD_FONT_INR24_T_CYRILLIC        u8g2_font_inr24_t_cyrillic
#define GLCD_FONT_INR27_MF                u8g2_font_inr27_mf
#define GLCD_FONT_INR27_MN                u8g2_font_inr27_mn
#define GLCD_FONT_INR27_MR                u8g2_font_inr27_mr
#define GLCD_FONT_INR27_T_CYRILLIC        u8g2_font_inr27_t_cyrillic
#define GLCD_FONT_INR30_MF                u8g2_font_inr30_mf
#define GLCD_FONT_INR30_MN                u8g2_font_inr30_mn
#define GLCD_FONT_INR30_MR                u8g2_font_inr30_mr
#define GLCD_FONT_INR30_T_CYRILLIC        u8g2_font_inr30_t_cyrillic
#define GLCD_FONT_INR33_MF                u8g2_font_inr33_mf
#define GLCD_FONT_INR33_MN                u8g2_font_inr33_mn
#define GLCD_FONT_INR33_MR                u8g2_font_inr33_mr
#define GLCD_FONT_INR33_T_CYRILLIC        u8g2_font_inr33_t_cyrillic
#define GLCD_FONT_INR38_MF                u8g2_font_inr38_mf
#define GLCD_FONT_INR38_MN                u8g2_font_inr38_mn
#define GLCD_FONT_INR38_MR                u8g2_font_inr38_mr
#define GLCD_FONT_INR38_T_CYRILLIC        u8g2_font_inr38_t_cyrillic
#define GLCD_FONT_INR42_MF                u8g2_font_inr42_mf
#define GLCD_FONT_INR42_MN                u8g2_font_inr42_mn
#define GLCD_FONT_INR42_MR                u8g2_font_inr42_mr
#define GLCD_FONT_INR42_T_CYRILLIC        u8g2_font_inr42_t_cyrillic
#define GLCD_FONT_INR46_MF                u8g2_font_inr46_mf
#define GLCD_FONT_INR46_MN                u8g2_font_inr46_mn
#define GLCD_FONT_INR46_MR                u8g2_font_inr46_mr
#define GLCD_FONT_INR46_T_CYRILLIC        u8g2_font_inr46_t_cyrillic
#define GLCD_FONT_INR49_MF                u8g2_font_inr49_mf
#define GLCD_FONT_INR49_MN                u8g2_font_inr49_mn
#define GLCD_FONT_INR49_MR                u8g2_font_inr49_mr
#define GLCD_FONT_INR49_T_CYRILLIC        u8g2_font_inr49_t_cyrillic
#define GLCD_FONT_INR53_MF                u8g2_font_inr53_mf
#define GLCD_FONT_INR53_MN                u8g2_font_inr53_mn
#define GLCD_FONT_INR53_MR                u8g2_font_inr53_mr
#define GLCD_FONT_INR53_T_CYRILLIC        u8g2_font_inr53_t_cyrillic
#define GLCD_FONT_INR57_MN                u8g2_font_inr57_mn
#define GLCD_FONT_INR62_MN                u8g2_font_inr62_mn
#define GLCD_FONT_IPAANDRUSLCD_TE         u8g2_font_IPAandRUSLCD_te
#define GLCD_FONT_IPAANDRUSLCD_TF         u8g2_font_IPAandRUSLCD_tf
#define GLCD_FONT_IPAANDRUSLCD_TR         u8g2_font_IPAandRUSLCD_tr
#define GLCD_FONT_IRANIAN_SANS_10_T_ALL   u8g2_font_iranian_sans_10_t_all
#define GLCD_FONT_IRANIAN_SANS_12_T_ALL   u8g2_font_iranian_sans_12_t_all
#define GLCD_FONT_IRANIAN_SANS_14_T_ALL   u8g2_font_iranian_sans_14_t_all
#define GLCD_FONT_IRANIAN_SANS_16_T_ALL   u8g2_font_iranian_sans_16_t_all
#define GLCD_FONT_IRANIAN_SANS_8_T_ALL    u8g2_font_iranian_sans_8_t_all
#define GLCD_FONT_JINXEDWIZARDS_TR        u8g2_font_jinxedwizards_tr
#define GLCD_FONT_KOLEEKO_TF              u8g2_font_koleeko_tf
#define GLCD_FONT_KOLEEKO_TN              u8g2_font_koleeko_tn
#define GLCD_FONT_KOLEEKO_TR              u8g2_font_koleeko_tr
#define GLCD_FONT_KOLEEKO_TU              u8g2_font_koleeko_tu
#define GLCD_FONT_LASTAPPRENTICEBOLD_TR   u8g2_font_lastapprenticebold_tr
#define GLCD_FONT_LASTAPPRENTICETHIN_TR   u8g2_font_lastapprenticethin_tr
#define GLCD_FONT_LASTPRIESTESS_TR        u8g2_font_lastpriestess_tr
#define GLCD_FONT_LASTPRIESTESS_TU        u8g2_font_lastpriestess_tu
#define GLCD_FONT_LOGISOSO16_TF           u8g2_font_logisoso16_tf
#define GLCD_FONT_LOGISOSO16_TN           u8g2_font_logisoso16_tn
#define GLCD_FONT_LOGISOSO16_TR           u8g2_font_logisoso16_tr
#define GLCD_FONT_LOGISOSO18_TF           u8g2_font_logisoso18_tf
#define GLCD_FONT_LOGISOSO18_TN           u8g2_font_logisoso18_tn
#define GLCD_FONT_LOGISOSO18_TR           u8g2_font_logisoso18_tr
#define GLCD_FONT_LOGISOSO20_TF           u8g2_font_logisoso20_tf
#define GLCD_FONT_LOGISOSO20_TN           u8g2_font_logisoso20_tn
#define GLCD_FONT_LOGISOSO20_TR           u8g2_font_logisoso20_tr
#define GLCD_FONT_LOGISOSO22_TF           u8g2_font_logisoso22_tf
#define GLCD_FONT_LOGISOSO22_TN           u8g2_font_logisoso22_tn
#define GLCD_FONT_LOGISOSO22_TR           u8g2_font_logisoso22_tr
#define GLCD_FONT_LOGISOSO24_TF           u8g2_font_logisoso24_tf
#define GLCD_FONT_LOGISOSO24_TN           u8g2_font_logisoso24_tn
#define GLCD_FONT_LOGISOSO24_TR           u8g2_font_logisoso24_tr
#define GLCD_FONT_LOGISOSO26_TF           u8g2_font_logisoso26_tf
#define GLCD_FONT_LOGISOSO26_TN           u8g2_font_logisoso26_tn
#define GLCD_FONT_LOGISOSO26_TR           u8g2_font_logisoso26_tr
#define GLCD_FONT_LOGISOSO28_TF           u8g2_font_logisoso28_tf
#define GLCD_FONT_LOGISOSO28_TN           u8g2_font_logisoso28_tn
#define GLCD_FONT_LOGISOSO28_TR           u8g2_font_logisoso28_tr
#define GLCD_FONT_LOGISOSO30_TF           u8g2_font_logisoso30_tf
#define GLCD_FONT_LOGISOSO30_TN           u8g2_font_logisoso30_tn
#define GLCD_FONT_LOGISOSO30_TR           u8g2_font_logisoso30_tr
#define GLCD_FONT_LOGISOSO32_TF           u8g2_font_logisoso32_tf
#define GLCD_FONT_LOGISOSO32_TN           u8g2_font_logisoso32_tn
#define GLCD_FONT_LOGISOSO32_TR           u8g2_font_logisoso32_tr
#define GLCD_FONT_LOGISOSO34_TF           u8g2_font_logisoso34_tf
#define GLCD_FONT_LOGISOSO34_TN           u8g2_font_logisoso34_tn
#define GLCD_FONT_LOGISOSO34_TR           u8g2_font_logisoso34_tr
#define GLCD_FONT_LOGISOSO38_TF           u8g2_font_logisoso38_tf
#define GLCD_FONT_LOGISOSO38_TN           u8g2_font_logisoso38_tn
#define GLCD_FONT_LOGISOSO38_TR           u8g2_font_logisoso38_tr
#define GLCD_FONT_LOGISOSO42_TF           u8g2_font_logisoso42_tf
#define GLCD_FONT_LOGISOSO42_TN           u8g2_font_logisoso42_tn
#define GLCD_FONT_LOGISOSO42_TR           u8g2_font_logisoso42_tr
#define GLCD_FONT_LOGISOSO46_TF           u8g2_font_logisoso46_tf
#define GLCD_FONT_LOGISOSO46_TN           u8g2_font_logisoso46_tn
#define GLCD_FONT_LOGISOSO46_TR           u8g2_font_logisoso46_tr
#define GLCD_FONT_LOGISOSO50_TF           u8g2_font_logisoso50_tf
#define GLCD_FONT_LOGISOSO50_TN           u8g2_font_logisoso50_tn
#define GLCD_FONT_LOGISOSO50_TR           u8g2_font_logisoso50_tr
#define GLCD_FONT_LOGISOSO54_TF           u8g2_font_logisoso54_tf
#define GLCD_FONT_LOGISOSO54_TN           u8g2_font_logisoso54_tn
#define GLCD_FONT_LOGISOSO54_TR           u8g2_font_logisoso54_tr
#define GLCD_FONT_LOGISOSO58_TF           u8g2_font_logisoso58_tf
#define GLCD_FONT_LOGISOSO58_TN           u8g2_font_logisoso58_tn
#define GLCD_FONT_LOGISOSO58_TR           u8g2_font_logisoso58_tr
#define GLCD_FONT_LOGISOSO62_TN           u8g2_font_logisoso62_tn
#define GLCD_FONT_LOGISOSO78_TN           u8g2_font_logisoso78_tn
#define GLCD_FONT_LOGISOSO92_TN           u8g2_font_logisoso92_tn
#define GLCD_FONT_LUCASARTS_SCUMM_SUBTITLE_O_TF u8g2_font_lucasarts_scumm_subtitle_o_tf
#define GLCD_FONT_LUCASARTS_SCUMM_SUBTITLE_O_TN u8g2_font_lucasarts_scumm_subtitle_o_tn
#define GLCD_FONT_LUCASARTS_SCUMM_SUBTITLE_O_TR u8g2_font_lucasarts_scumm_subtitle_o_tr
#define GLCD_FONT_LUCASARTS_SCUMM_SUBTITLE_R_TF u8g2_font_lucasarts_scumm_subtitle_r_tf
#define GLCD_FONT_LUCASARTS_SCUMM_SUBTITLE_R_TN u8g2_font_lucasarts_scumm_subtitle_r_tn
#define GLCD_FONT_LUCASARTS_SCUMM_SUBTITLE_R_TR u8g2_font_lucasarts_scumm_subtitle_r_tr
#define GLCD_FONT_LUCASFONT_ALTERNATE_TF  u8g2_font_lucasfont_alternate_tf
#define GLCD_FONT_LUCASFONT_ALTERNATE_TN  u8g2_font_lucasfont_alternate_tn
#define GLCD_FONT_LUCASFONT_ALTERNATE_TR  u8g2_font_lucasfont_alternate_tr
#define GLCD_FONT_M2ICON_5_TF             u8g2_font_m2icon_5_tf
#define GLCD_FONT_M2ICON_7_TF             u8g2_font_m2icon_7_tf
#define GLCD_FONT_M2ICON_9_TF             u8g2_font_m2icon_9_tf
#define GLCD_FONT_MADEMOISELLE_MEL_TN     u8g2_font_mademoiselle_mel_tn
#define GLCD_FONT_MADEMOISELLE_MEL_TR     u8g2_font_mademoiselle_mel_tr
#define GLCD_FONT_MANIAC_TE               u8g2_font_maniac_te
#define GLCD_FONT_MANIAC_TF               u8g2_font_maniac_tf
#define GLCD_FONT_MANIAC_TN               u8g2_font_maniac_tn
#define GLCD_FONT_MANIAC_TR               u8g2_font_maniac_tr
#define GLCD_FONT_MERCUTIO_BASIC_NBP_T_ALL u8g2_font_mercutio_basic_nbp_t_all
#define GLCD_FONT_MERCUTIO_BASIC_NBP_TF   u8g2_font_mercutio_basic_nbp_tf
#define GLCD_FONT_MERCUTIO_BASIC_NBP_TN   u8g2_font_mercutio_basic_nbp_tn
#define GLCD_FONT_MERCUTIO_BASIC_NBP_TR   u8g2_font_mercutio_basic_nbp_tr
#define GLCD_FONT_MERCUTIO_SC_NBP_T_ALL   u8g2_font_mercutio_sc_nbp_t_all
#define GLCD_FONT_MERCUTIO_SC_NBP_TF      u8g2_font_mercutio_sc_nbp_tf
#define GLCD_FONT_MERCUTIO_SC_NBP_TN      u8g2_font_mercutio_sc_nbp_tn
#define GLCD_FONT_MERCUTIO_SC_NBP_TR      u8g2_font_mercutio_sc_nbp_tr
#define GLCD_FONT_MICHAELMOUSE_TU         u8g2_font_michaelmouse_tu
#define GLCD_FONT_MICRO_MN                u8g2_font_micro_mn
#define GLCD_FONT_MICRO_MR                u8g2_font_micro_mr
#define GLCD_FONT_MICRO_TN                u8g2_font_micro_tn
#define GLCD_FONT_MICRO_TR                u8g2_font_micro_tr
#define GLCD_FONT_MIRANDA_NBP_TF          u8g2_font_miranda_nbp_tf
#define GLCD_FONT_MIRANDA_NBP_TN          u8g2_font_miranda_nbp_tn
#define GLCD_FONT_MIRANDA_NBP_TR          u8g2_font_miranda_nbp_tr
#define GLCD_FONT_MISSINGPLANET_T_ALL     u8g2_font_missingplanet_t_all
#define GLCD_FONT_MISSINGPLANET_TF        u8g2_font_missingplanet_tf
#define GLCD_FONT_MISSINGPLANET_TN        u8g2_font_missingplanet_tn
#define GLCD_FONT_MISSINGPLANET_TR        u8g2_font_missingplanet_tr
#define GLCD_FONT_MOZART_NBP_H_ALL        u8g2_font_mozart_nbp_h_all
#define GLCD_FONT_MOZART_NBP_T_ALL        u8g2_font_mozart_nbp_t_all
#define GLCD_FONT_MOZART_NBP_TF           u8g2_font_mozart_nbp_tf
#define GLCD_FONT_MOZART_NBP_TN           u8g2_font_mozart_nbp_tn
#define GLCD_FONT_MOZART_NBP_TR           u8g2_font_mozart_nbp_tr
#define GLCD_FONT_NCENB08_TE              u8g2_font_ncenB08_te
#define GLCD_FONT_NCENB08_TF              u8g2_font_ncenB08_tf
#define GLCD_FONT_NCENB08_TN              u8g2_font_ncenB08_tn
#define GLCD_FONT_NCENB08_TR              u8g2_font_ncenB08_tr
#define GLCD_FONT_NCENB10_TE              u8g2_font_ncenB10_te
#define GLCD_FONT_NCENB10_TF              u8g2_font_ncenB10_tf
#define GLCD_FONT_NCENB10_TN              u8g2_font_ncenB10_tn
#define GLCD_FONT_NCENB10_TR              u8g2_font_ncenB10_tr
#define GLCD_FONT_NCENB12_TE              u8g2_font_ncenB12_te
#define GLCD_FONT_NCENB12_TF              u8g2_font_ncenB12_tf
#define GLCD_FONT_NCENB12_TN              u8g2_font_ncenB12_tn
#define GLCD_FONT_NCENB12_TR              u8g2_font_ncenB12_tr
#define GLCD_FONT_NCENB14_TE              u8g2_font_ncenB14_te
#define GLCD_FONT_NCENB14_TF              u8g2_font_ncenB14_tf
#define GLCD_FONT_NCENB14_TN              u8g2_font_ncenB14_tn
#define GLCD_FONT_NCENB14_TR              u8g2_font_ncenB14_tr
#define GLCD_FONT_NCENB18_TE              u8g2_font_ncenB18_te
#define GLCD_FONT_NCENB18_TF              u8g2_font_ncenB18_tf
#define GLCD_FONT_NCENB18_TN              u8g2_font_ncenB18_tn
#define GLCD_FONT_NCENB18_TR              u8g2_font_ncenB18_tr
#define GLCD_FONT_NCENB24_TE              u8g2_font_ncenB24_te
#define GLCD_FONT_NCENB24_TF              u8g2_font_ncenB24_tf
#define GLCD_FONT_NCENB24_TN              u8g2_font_ncenB24_tn
#define GLCD_FONT_NCENB24_TR              u8g2_font_ncenB24_tr
#define GLCD_FONT_NCENR08_TE              u8g2_font_ncenR08_te
#define GLCD_FONT_NCENR08_TF              u8g2_font_ncenR08_tf
#define GLCD_FONT_NCENR08_TN              u8g2_font_ncenR08_tn
#define GLCD_FONT_NCENR08_TR              u8g2_font_ncenR08_tr
#define GLCD_FONT_NCENR10_TE              u8g2_font_ncenR10_te
#define GLCD_FONT_NCENR10_TF              u8g2_font_ncenR10_tf
#define GLCD_FONT_NCENR10_TN              u8g2_font_ncenR10_tn
#define GLCD_FONT_NCENR10_TR              u8g2_font_ncenR10_tr
#define GLCD_FONT_NCENR12_TE              u8g2_font_ncenR12_te
#define GLCD_FONT_NCENR12_TF              u8g2_font_ncenR12_tf
#define GLCD_FONT_NCENR12_TN              u8g2_font_ncenR12_tn
#define GLCD_FONT_NCENR12_TR              u8g2_font_ncenR12_tr
#define GLCD_FONT_NCENR14_TE              u8g2_font_ncenR14_te
#define GLCD_FONT_NCENR14_TF              u8g2_font_ncenR14_tf
#define GLCD_FONT_NCENR14_TN              u8g2_font_ncenR14_tn
#define GLCD_FONT_NCENR14_TR              u8g2_font_ncenR14_tr
#define GLCD_FONT_NCENR18_TE              u8g2_font_ncenR18_te
#define GLCD_FONT_NCENR18_TF              u8g2_font_ncenR18_tf
#define GLCD_FONT_NCENR18_TN              u8g2_font_ncenR18_tn
#define GLCD_FONT_NCENR18_TR              u8g2_font_ncenR18_tr
#define GLCD_FONT_NCENR24_TE              u8g2_font_ncenR24_te
#define GLCD_FONT_NCENR24_TF              u8g2_font_ncenR24_tf
#define GLCD_FONT_NCENR24_TN              u8g2_font_ncenR24_tn
#define GLCD_FONT_NCENR24_TR              u8g2_font_ncenR24_tr
#define GLCD_FONT_NERHOE_TF               u8g2_font_nerhoe_tf
#define GLCD_FONT_NERHOE_TN               u8g2_font_nerhoe_tn
#define GLCD_FONT_NERHOE_TR               u8g2_font_nerhoe_tr
#define GLCD_FONT_NINE_BY_FIVE_NBP_T_ALL  u8g2_font_nine_by_five_nbp_t_all
#define GLCD_FONT_NINE_BY_FIVE_NBP_TF     u8g2_font_nine_by_five_nbp_tf
#define GLCD_FONT_NINE_BY_FIVE_NBP_TN     u8g2_font_nine_by_five_nbp_tn
#define GLCD_FONT_NINE_BY_FIVE_NBP_TR     u8g2_font_nine_by_five_nbp_tr
#define GLCD_FONT_OLDWIZARD_TF            u8g2_font_oldwizard_tf
#define GLCD_FONT_OLDWIZARD_TN            u8g2_font_oldwizard_tn
#define GLCD_FONT_OLDWIZARD_TR            u8g2_font_oldwizard_tr
#define GLCD_FONT_OLDWIZARD_TU            u8g2_font_oldwizard_tu
#define GLCD_FONT_OPEN_ICONIC_ALL_1X_T    u8g2_font_open_iconic_all_1x_t
#define GLCD_FONT_OPEN_ICONIC_ALL_2X_T    u8g2_font_open_iconic_all_2x_t
#define GLCD_FONT_OPEN_ICONIC_ALL_4X_T    u8g2_font_open_iconic_all_4x_t
#define GLCD_FONT_OPEN_ICONIC_ALL_6X_T    u8g2_font_open_iconic_all_6x_t
#define GLCD_FONT_OPEN_ICONIC_ALL_8X_T    u8g2_font_open_iconic_all_8x_t
#define GLCD_FONT_OPEN_ICONIC_APP_1X_T    u8g2_font_open_iconic_app_1x_t
#define GLCD_FONT_OPEN_ICONIC_APP_2X_T    u8g2_font_open_iconic_app_2x_t
#define GLCD_FONT_OPEN_ICONIC_APP_4X_T    u8g2_font_open_iconic_app_4x_t
#define GLCD_FONT_OPEN_ICONIC_APP_6X_T    u8g2_font_open_iconic_app_6x_t
#define GLCD_FONT_OPEN_ICONIC_APP_8X_T    u8g2_font_open_iconic_app_8x_t
#define GLCD_FONT_OPEN_ICONIC_ARROW_1X_T  u8g2_font_open_iconic_arrow_1x_t
#define GLCD_FONT_OPEN_ICONIC_ARROW_2X_T  u8g2_font_open_iconic_arrow_2x_t
#define GLCD_FONT_OPEN_ICONIC_ARROW_4X_T  u8g2_font_open_iconic_arrow_4x_t
#define GLCD_FONT_OPEN_ICONIC_ARROW_6X_T  u8g2_font_open_iconic_arrow_6x_t
#define GLCD_FONT_OPEN_ICONIC_ARROW_8X_T  u8g2_font_open_iconic_arrow_8x_t
#define GLCD_FONT_OPEN_ICONIC_CHECK_1X_T  u8g2_font_open_iconic_check_1x_t
#define GLCD_FONT_OPEN_ICONIC_CHECK_2X_T  u8g2_font_open_iconic_check_2x_t
#define GLCD_FONT_OPEN_ICONIC_CHECK_4X_T  u8g2_font_open_iconic_check_4x_t
#define GLCD_FONT_OPEN_ICONIC_CHECK_6X_T  u8g2_font_open_iconic_check_6x_t
#define GLCD_FONT_OPEN_ICONIC_CHECK_8X_T  u8g2_font_open_iconic_check_8x_t
#define GLCD_FONT_OPEN_ICONIC_EMAIL_1X_T  u8g2_font_open_iconic_email_1x_t
#define GLCD_FONT_OPEN_ICONIC_EMAIL_2X_T  u8g2_font_open_iconic_email_2x_t
#define GLCD_FONT_OPEN_ICONIC_EMAIL_4X_T  u8g2_font_open_iconic_email_4x_t
#define GLCD_FONT_OPEN_ICONIC_EMAIL_6X_T  u8g2_font_open_iconic_email_6x_t
#define GLCD_FONT_OPEN_ICONIC_EMAIL_8X_T  u8g2_font_open_iconic_email_8x_t
#define GLCD_FONT_OPEN_ICONIC_EMBEDDED_1X_T u8g2_font_open_iconic_embedded_1x_t
#define GLCD_FONT_OPEN_ICONIC_EMBEDDED_2X_T u8g2_font_open_iconic_embedded_2x_t
#define GLCD_FONT_OPEN_ICONIC_EMBEDDED_4X_T u8g2_font_open_iconic_embedded_4x_t
#define GLCD_FONT_OPEN_ICONIC_EMBEDDED_6X_T u8g2_font_open_iconic_embedded_6x_t
#define GLCD_FONT_OPEN_ICONIC_EMBEDDED_8X_T u8g2_font_open_iconic_embedded_8x_t
#define GLCD_FONT_OPEN_ICONIC_GUI_1X_T    u8g2_font_open_iconic_gui_1x_t
#define GLCD_FONT_OPEN_ICONIC_GUI_2X_T    u8g2_font_open_iconic_gui_2x_t
#define GLCD_FONT_OPEN_ICONIC_GUI_4X_T    u8g2_font_open_iconic_gui_4x_t
#define GLCD_FONT_OPEN_ICONIC_GUI_6X_T    u8g2_font_open_iconic_gui_6x_t
#define GLCD_FONT_OPEN_ICONIC_GUI_8X_T    u8g2_font_open_iconic_gui_8x_t
#define GLCD_FONT_OPEN_ICONIC_HUMAN_1X_T  u8g2_font_open_iconic_human_1x_t
#define GLCD_FONT_OPEN_ICONIC_HUMAN_2X_T  u8g2_font_open_iconic_human_2x_t
#define GLCD_FONT_OPEN_ICONIC_HUMAN_4X_T  u8g2_font_open_iconic_human_4x_t
#define GLCD_FONT_OPEN_ICONIC_HUMAN_6X_T  u8g2_font_open_iconic_human_6x_t
#define GLCD_FONT_OPEN_ICONIC_HUMAN_8X_T  u8g2_font_open_iconic_human_8x_t
#define GLCD_FONT_OPEN_ICONIC_MIME_1X_T   u8g2_font_open_iconic_mime_1x_t
#define GLCD_FONT_OPEN_ICONIC_MIME_2X_T   u8g2_font_open_iconic_mime_2x_t
#define GLCD_FONT_OPEN_ICONIC_MIME_4X_T   u8g2_font_open_iconic_mime_4x_t
#define GLCD_FONT_OPEN_ICONIC_MIME_6X_T   u8g2_font_open_iconic_mime_6x_t
#define GLCD_FONT_OPEN_ICONIC_MIME_8X_T   u8g2_font_open_iconic_mime_8x_t
#define GLCD_FONT_OPEN_ICONIC_OTHER_1X_T  u8g2_font_open_iconic_other_1x_t
#define GLCD_FONT_OPEN_ICONIC_OTHER_2X_T  u8g2_font_open_iconic_other_2x_t
#define GLCD_FONT_OPEN_ICONIC_OTHER_4X_T  u8g2_font_open_iconic_other_4x_t
#define GLCD_FONT_OPEN_ICONIC_OTHER_6X_T  u8g2_font_open_iconic_other_6x_t
#define GLCD_FONT_OPEN_ICONIC_OTHER_8X_T  u8g2_font_open_iconic_other_8x_t
#define GLCD_FONT_OPEN_ICONIC_PLAY_1X_T   u8g2_font_open_iconic_play_1x_t
#define GLCD_FONT_OPEN_ICONIC_PLAY_2X_T   u8g2_font_open_iconic_play_2x_t
#define GLCD_FONT_OPEN_ICONIC_PLAY_4X_T   u8g2_font_open_iconic_play_4x_t
#define GLCD_FONT_OPEN_ICONIC_PLAY_6X_T   u8g2_font_open_iconic_play_6x_t
#define GLCD_FONT_OPEN_ICONIC_PLAY_8X_T   u8g2_font_open_iconic_play_8x_t
#define GLCD_FONT_OPEN_ICONIC_TEXT_1X_T   u8g2_font_open_iconic_text_1x_t
#define GLCD_FONT_OPEN_ICONIC_TEXT_2X_T   u8g2_font_open_iconic_text_2x_t
#define GLCD_FONT_OPEN_ICONIC_TEXT_4X_T   u8g2_font_open_iconic_text_4x_t
#define GLCD_FONT_OPEN_ICONIC_TEXT_6X_T   u8g2_font_open_iconic_text_6x_t
#define GLCD_FONT_OPEN_ICONIC_TEXT_8X_T   u8g2_font_open_iconic_text_8x_t
#define GLCD_FONT_OPEN_ICONIC_THING_1X_T  u8g2_font_open_iconic_thing_1x_t
#define GLCD_FONT_OPEN_ICONIC_THING_2X_T  u8g2_font_open_iconic_thing_2x_t
#define GLCD_FONT_OPEN_ICONIC_THING_4X_T  u8g2_font_open_iconic_thing_4x_t
#define GLCD_FONT_OPEN_ICONIC_THING_6X_T  u8g2_font_open_iconic_thing_6x_t
#define GLCD_FONT_OPEN_ICONIC_THING_8X_T  u8g2_font_open_iconic_thing_8x_t
#define GLCD_FONT_OPEN_ICONIC_WEATHER_1X_T u8g2_font_open_iconic_weather_1x_t
#define GLCD_FONT_OPEN_ICONIC_WEATHER_2X_T u8g2_font_open_iconic_weather_2x_t
#define GLCD_FONT_OPEN_ICONIC_WEATHER_4X_T u8g2_font_open_iconic_weather_4x_t
#define GLCD_FONT_OPEN_ICONIC_WEATHER_6X_T u8g2_font_open_iconic_weather_6x_t
#define GLCD_FONT_OPEN_ICONIC_WEATHER_8X_T u8g2_font_open_iconic_weather_8x_t
#define GLCD_FONT_OPEN_ICONIC_WWW_1X_T    u8g2_font_open_iconic_www_1x_t
#define GLCD_FONT_OPEN_ICONIC_WWW_2X_T    u8g2_font_open_iconic_www_2x_t
#define GLCD_FONT_OPEN_ICONIC_WWW_4X_T    u8g2_font_open_iconic_www_4x_t
#define GLCD_FONT_OPEN_ICONIC_WWW_6X_T    u8g2_font_open_iconic_www_6x_t
#define GLCD_FONT_OPEN_ICONIC_WWW_8X_T    u8g2_font_open_iconic_www_8x_t
#define GLCD_FONT_ORDINARYBASIS_T_ALL     u8g2_font_ordinarybasis_t_all
#define GLCD_FONT_ORDINARYBASIS_TF        u8g2_font_ordinarybasis_tf
#define GLCD_FONT_ORDINARYBASIS_TN        u8g2_font_ordinarybasis_tn
#define GLCD_FONT_ORDINARYBASIS_TR        u8g2_font_ordinarybasis_tr
#define GLCD_FONT_OSB18_TF                u8g2_font_osb18_tf
#define GLCD_FONT_OSB18_TN                u8g2_font_osb18_tn
#define GLCD_FONT_OSB18_TR                u8g2_font_osb18_tr
#define GLCD_FONT_OSB21_TF                u8g2_font_osb21_tf
#define GLCD_FONT_OSB21_TN                u8g2_font_osb21_tn
#define GLCD_FONT_OSB21_TR                u8g2_font_osb21_tr
#define GLCD_FONT_OSB26_TF                u8g2_font_osb26_tf
#define GLCD_FONT_OSB26_TN                u8g2_font_osb26_tn
#define GLCD_FONT_OSB26_TR                u8g2_font_osb26_tr
#define GLCD_FONT_OSB29_TF                u8g2_font_osb29_tf
#define GLCD_FONT_OSB29_TN                u8g2_font_osb29_tn
#define GLCD_FONT_OSB29_TR                u8g2_font_osb29_tr
#define GLCD_FONT_OSB35_TF                u8g2_font_osb35_tf
#define GLCD_FONT_OSB35_TN                u8g2_font_osb35_tn
#define GLCD_FONT_OSB35_TR                u8g2_font_osb35_tr
#define GLCD_FONT_OSB41_TF                u8g2_font_osb41_tf
#define GLCD_FONT_OSB41_TN                u8g2_font_osb41_tn
#define GLCD_FONT_OSB41_TR                u8g2_font_osb41_tr
#define GLCD_FONT_OSKOOL_TF               u8g2_font_oskool_tf
#define GLCD_FONT_OSKOOL_TN               u8g2_font_oskool_tn
#define GLCD_FONT_OSKOOL_TR               u8g2_font_oskool_tr
#define GLCD_FONT_OSR18_TF                u8g2_font_osr18_tf
#define GLCD_FONT_OSR18_TN                u8g2_font_osr18_tn
#define GLCD_FONT_OSR18_TR                u8g2_font_osr18_tr
#define GLCD_FONT_OSR21_TF                u8g2_font_osr21_tf
#define GLCD_FONT_OSR21_TN                u8g2_font_osr21_tn
#define GLCD_FONT_OSR21_TR                u8g2_font_osr21_tr
#define GLCD_FONT_OSR26_TF                u8g2_font_osr26_tf
#define GLCD_FONT_OSR26_TN                u8g2_font_osr26_tn
#define GLCD_FONT_OSR26_TR                u8g2_font_osr26_tr
#define GLCD_FONT_OSR29_TF                u8g2_font_osr29_tf
#define GLCD_FONT_OSR29_TN                u8g2_font_osr29_tn
#define GLCD_FONT_OSR29_TR                u8g2_font_osr29_tr
#define GLCD_FONT_OSR35_TF                u8g2_font_osr35_tf
#define GLCD_FONT_OSR35_TN                u8g2_font_osr35_tn
#define GLCD_FONT_OSR35_TR                u8g2_font_osr35_tr
#define GLCD_FONT_OSR41_TF                u8g2_font_osr41_tf
#define GLCD_FONT_OSR41_TN                u8g2_font_osr41_tn
#define GLCD_FONT_OSR41_TR                u8g2_font_osr41_tr
#define GLCD_FONT_P01TYPE_TF              u8g2_font_p01type_tf
#define GLCD_FONT_P01TYPE_TN              u8g2_font_p01type_tn
#define GLCD_FONT_P01TYPE_TR              u8g2_font_p01type_tr
#define GLCD_FONT_PCSENIOR_8F             u8g2_font_pcsenior_8f
#define GLCD_FONT_PCSENIOR_8N             u8g2_font_pcsenior_8n
#define GLCD_FONT_PCSENIOR_8R             u8g2_font_pcsenior_8r
#define GLCD_FONT_PCSENIOR_8U             u8g2_font_pcsenior_8u
#define GLCD_FONT_PIECEOFCAKE_MEL_TN      u8g2_font_pieceofcake_mel_tn
#define GLCD_FONT_PIECEOFCAKE_MEL_TR      u8g2_font_pieceofcake_mel_tr
#define GLCD_FONT_PIXELLE_MICRO_TN        u8g2_font_pixelle_micro_tn
#define GLCD_FONT_PIXELLE_MICRO_TR        u8g2_font_pixelle_micro_tr
#define GLCD_FONT_PIXELMORDRED_T_ALL      u8g2_font_pixelmordred_t_all
#define GLCD_FONT_PIXELMORDRED_TF         u8g2_font_pixelmordred_tf
#define GLCD_FONT_PIXELMORDRED_TN         u8g2_font_pixelmordred_tn
#define GLCD_FONT_PIXELMORDRED_TR         u8g2_font_pixelmordred_tr
#define GLCD_FONT_PRESS_MEL_TN            u8g2_font_press_mel_tn
#define GLCD_FONT_PRESS_MEL_TR            u8g2_font_press_mel_tr
#define GLCD_FONT_PRESSSTART2P_8F         u8g2_font_pressstart2p_8f
#define GLCD_FONT_PRESSSTART2P_8N         u8g2_font_pressstart2p_8n
#define GLCD_FONT_PRESSSTART2P_8R         u8g2_font_pressstart2p_8r
#define GLCD_FONT_PRESSSTART2P_8U         u8g2_font_pressstart2p_8u
#define GLCD_FONT_PROFONT10_MF            u8g2_font_profont10_mf
#define GLCD_FONT_PROFONT10_MN            u8g2_font_profont10_mn
#define GLCD_FONT_PROFONT10_MR            u8g2_font_profont10_mr
#define GLCD_FONT_PROFONT10_TF            u8g2_font_profont10_tf
#define GLCD_FONT_PROFONT10_TN            u8g2_font_profont10_tn
#define GLCD_FONT_PROFONT10_TR            u8g2_font_profont10_tr
#define GLCD_FONT_PROFONT11_MF            u8g2_font_profont11_mf
#define GLCD_FONT_PROFONT11_MN            u8g2_font_profont11_mn
#define GLCD_FONT_PROFONT11_MR            u8g2_font_profont11_mr
#define GLCD_FONT_PROFONT11_TF            u8g2_font_profont11_tf
#define GLCD_FONT_PROFONT11_TN            u8g2_font_profont11_tn
#define GLCD_FONT_PROFONT11_TR            u8g2_font_profont11_tr
#define GLCD_FONT_PROFONT12_MF            u8g2_font_profont12_mf
#define GLCD_FONT_PROFONT12_MN            u8g2_font_profont12_mn
#define GLCD_FONT_PROFONT12_MR            u8g2_font_profont12_mr
#define GLCD_FONT_PROFONT12_TF            u8g2_font_profont12_tf
#define GLCD_FONT_PROFONT12_TN            u8g2_font_profont12_tn
#define GLCD_FONT_PROFONT12_TR            u8g2_font_profont12_tr
#define GLCD_FONT_PROFONT15_MF            u8g2_font_profont15_mf
#define GLCD_FONT_PROFONT15_MN            u8g2_font_profont15_mn
#define GLCD_FONT_PROFONT15_MR            u8g2_font_profont15_mr
#define GLCD_FONT_PROFONT15_TF            u8g2_font_profont15_tf
#define GLCD_FONT_PROFONT15_TN            u8g2_font_profont15_tn
#define GLCD_FONT_PROFONT15_TR            u8g2_font_profont15_tr
#define GLCD_FONT_PROFONT17_MF            u8g2_font_profont17_mf
#define GLCD_FONT_PROFONT17_MN            u8g2_font_profont17_mn
#define GLCD_FONT_PROFONT17_MR            u8g2_font_profont17_mr
#define GLCD_FONT_PROFONT17_TF            u8g2_font_profont17_tf
#define GLCD_FONT_PROFONT17_TN            u8g2_font_profont17_tn
#define GLCD_FONT_PROFONT17_TR            u8g2_font_profont17_tr
#define GLCD_FONT_PROFONT22_MF            u8g2_font_profont22_mf
#define GLCD_FONT_PROFONT22_MN            u8g2_font_profont22_mn
#define GLCD_FONT_PROFONT22_MR            u8g2_font_profont22_mr
#define GLCD_FONT_PROFONT22_TF            u8g2_font_profont22_tf
#define GLCD_FONT_PROFONT22_TN            u8g2_font_profont22_tn
#define GLCD_FONT_PROFONT22_TR            u8g2_font_profont22_tr
#define GLCD_FONT_PROFONT29_MF            u8g2_font_profont29_mf
#define GLCD_FONT_PROFONT29_MN            u8g2_font_profont29_mn
#define GLCD_FONT_PROFONT29_MR            u8g2_font_profont29_mr
#define GLCD_FONT_PROFONT29_TF            u8g2_font_profont29_tf
#define GLCD_FONT_PROFONT29_TN            u8g2_font_profont29_tn
#define GLCD_FONT_PROFONT29_TR            u8g2_font_profont29_tr
#define GLCD_FONT_PROSPERO_BOLD_NBP_TF    u8g2_font_prospero_bold_nbp_tf
#define GLCD_FONT_PROSPERO_BOLD_NBP_TN    u8g2_font_prospero_bold_nbp_tn
#define GLCD_FONT_PROSPERO_BOLD_NBP_TR    u8g2_font_prospero_bold_nbp_tr
#define GLCD_FONT_PROSPERO_NBP_TF         u8g2_font_prospero_nbp_tf
#define GLCD_FONT_PROSPERO_NBP_TN         u8g2_font_prospero_nbp_tn
#define GLCD_FONT_PROSPERO_NBP_TR         u8g2_font_prospero_nbp_tr
#define GLCD_FONT_PX437WYSE700A_MF        u8g2_font_px437wyse700a_mf
#define GLCD_FONT_PX437WYSE700A_MN        u8g2_font_px437wyse700a_mn
#define GLCD_FONT_PX437WYSE700A_MR        u8g2_font_px437wyse700a_mr
#define GLCD_FONT_PX437WYSE700A_TF        u8g2_font_px437wyse700a_tf
#define GLCD_FONT_PX437WYSE700A_TN        u8g2_font_px437wyse700a_tn
#define GLCD_FONT_PX437WYSE700A_TR        u8g2_font_px437wyse700a_tr
#define GLCD_FONT_PX437WYSE700B_MF        u8g2_font_px437wyse700b_mf
#define GLCD_FONT_PX437WYSE700B_MN        u8g2_font_px437wyse700b_mn
#define GLCD_FONT_PX437WYSE700B_MR        u8g2_font_px437wyse700b_mr
#define GLCD_FONT_PX437WYSE700B_TF        u8g2_font_px437wyse700b_tf
#define GLCD_FONT_PX437WYSE700B_TN        u8g2_font_px437wyse700b_tn
#define GLCD_FONT_PX437WYSE700B_TR        u8g2_font_px437wyse700b_tr
#define GLCD_FONT_PXPLUSIBMCGA_8F         u8g2_font_pxplusibmcga_8f
#define GLCD_FONT_PXPLUSIBMCGA_8N         u8g2_font_pxplusibmcga_8n
#define GLCD_FONT_PXPLUSIBMCGA_8R         u8g2_font_pxplusibmcga_8r
#define GLCD_FONT_PXPLUSIBMCGA_8U         u8g2_font_pxplusibmcga_8u
#define GLCD_FONT_PXPLUSIBMCGATHIN_8F     u8g2_font_pxplusibmcgathin_8f
#define GLCD_FONT_PXPLUSIBMCGATHIN_8N     u8g2_font_pxplusibmcgathin_8n
#define GLCD_FONT_PXPLUSIBMCGATHIN_8R     u8g2_font_pxplusibmcgathin_8r
#define GLCD_FONT_PXPLUSIBMCGATHIN_8U     u8g2_font_pxplusibmcgathin_8u
#define GLCD_FONT_PXPLUSIBMVGA8_M_ALL     u8g2_font_pxplusibmvga8_m_all
#define GLCD_FONT_PXPLUSIBMVGA8_MF        u8g2_font_pxplusibmvga8_mf
#define GLCD_FONT_PXPLUSIBMVGA8_MN        u8g2_font_pxplusibmvga8_mn
#define GLCD_FONT_PXPLUSIBMVGA8_MR        u8g2_font_pxplusibmvga8_mr
#define GLCD_FONT_PXPLUSIBMVGA8_T_ALL     u8g2_font_pxplusibmvga8_t_all
#define GLCD_FONT_PXPLUSIBMVGA8_TF        u8g2_font_pxplusibmvga8_tf
#define GLCD_FONT_PXPLUSIBMVGA8_TN        u8g2_font_pxplusibmvga8_tn
#define GLCD_FONT_PXPLUSIBMVGA8_TR        u8g2_font_pxplusibmvga8_tr
#define GLCD_FONT_PXPLUSIBMVGA9_M_ALL     u8g2_font_pxplusibmvga9_m_all
#define GLCD_FONT_PXPLUSIBMVGA9_MF        u8g2_font_pxplusibmvga9_mf
#define GLCD_FONT_PXPLUSIBMVGA9_MN        u8g2_font_pxplusibmvga9_mn
#define GLCD_FONT_PXPLUSIBMVGA9_MR        u8g2_font_pxplusibmvga9_mr
#define GLCD_FONT_PXPLUSIBMVGA9_T_ALL     u8g2_font_pxplusibmvga9_t_all
#define GLCD_FONT_PXPLUSIBMVGA9_TF        u8g2_font_pxplusibmvga9_tf
#define GLCD_FONT_PXPLUSIBMVGA9_TN        u8g2_font_pxplusibmvga9_tn
#define GLCD_FONT_PXPLUSIBMVGA9_TR        u8g2_font_pxplusibmvga9_tr
#define GLCD_FONT_PXPLUSTANDYNEWTV_8_ALL  u8g2_font_pxplustandynewtv_8_all
#define GLCD_FONT_PXPLUSTANDYNEWTV_8F     u8g2_font_pxplustandynewtv_8f
#define GLCD_FONT_PXPLUSTANDYNEWTV_8N     u8g2_font_pxplustandynewtv_8n
#define GLCD_FONT_PXPLUSTANDYNEWTV_8R     u8g2_font_pxplustandynewtv_8r
#define GLCD_FONT_PXPLUSTANDYNEWTV_8U     u8g2_font_pxplustandynewtv_8u
#define GLCD_FONT_PXPLUSTANDYNEWTV_T_ALL  u8g2_font_pxplustandynewtv_t_all
#define GLCD_FONT_QUESTGIVER_TR           u8g2_font_questgiver_tr
#define GLCD_FONT_REPRESS_MEL_TN          u8g2_font_repress_mel_tn
#define GLCD_FONT_REPRESS_MEL_TR          u8g2_font_repress_mel_tr
#define GLCD_FONT_ROBOT_DE_NIRO_TF        u8g2_font_robot_de_niro_tf
#define GLCD_FONT_ROBOT_DE_NIRO_TN        u8g2_font_robot_de_niro_tn
#define GLCD_FONT_ROBOT_DE_NIRO_TR        u8g2_font_robot_de_niro_tr
#define GLCD_FONT_ROENTGEN_NBP_H_ALL      u8g2_font_roentgen_nbp_h_all
#define GLCD_FONT_ROENTGEN_NBP_T_ALL      u8g2_font_roentgen_nbp_t_all
#define GLCD_FONT_ROENTGEN_NBP_TF         u8g2_font_roentgen_nbp_tf
#define GLCD_FONT_ROENTGEN_NBP_TN         u8g2_font_roentgen_nbp_tn
#define GLCD_FONT_ROENTGEN_NBP_TR         u8g2_font_roentgen_nbp_tr
#define GLCD_FONT_ROSENCRANTZ_NBP_T_ALL   u8g2_font_rosencrantz_nbp_t_all
#define GLCD_FONT_ROSENCRANTZ_NBP_TF      u8g2_font_rosencrantz_nbp_tf
#define GLCD_FONT_ROSENCRANTZ_NBP_TN      u8g2_font_rosencrantz_nbp_tn
#define GLCD_FONT_ROSENCRANTZ_NBP_TR      u8g2_font_rosencrantz_nbp_tr
#define GLCD_FONT_SAIKYOSANSBOLD8_8N      u8g2_font_saikyosansbold8_8n
#define GLCD_FONT_SAIKYOSANSBOLD8_8U      u8g2_font_saikyosansbold8_8u
#define GLCD_FONT_SAMIM_10_T_ALL          u8g2_font_samim_10_t_all
#define GLCD_FONT_SAMIM_12_T_ALL          u8g2_font_samim_12_t_all
#define GLCD_FONT_SAMIM_14_T_ALL          u8g2_font_samim_14_t_all
#define GLCD_FONT_SAMIM_16_T_ALL          u8g2_font_samim_16_t_all
#define GLCD_FONT_SAMIM_FD_10_T_ALL       u8g2_font_samim_fd_10_t_all
#define GLCD_FONT_SAMIM_FD_12_T_ALL       u8g2_font_samim_fd_12_t_all
#define GLCD_FONT_SAMIM_FD_14_T_ALL       u8g2_font_samim_fd_14_t_all
#define GLCD_FONT_SAMIM_FD_16_T_ALL       u8g2_font_samim_fd_16_t_all
#define GLCD_FONT_SANDYFOREST_TN          u8g2_font_sandyforest_tn
#define GLCD_FONT_SANDYFOREST_TR          u8g2_font_sandyforest_tr
#define GLCD_FONT_SANDYFOREST_TU          u8g2_font_sandyforest_tu
#define GLCD_FONT_SECRETARYHAND_T_ALL     u8g2_font_secretaryhand_t_all
#define GLCD_FONT_SECRETARYHAND_TF        u8g2_font_secretaryhand_tf
#define GLCD_FONT_SECRETARYHAND_TN        u8g2_font_secretaryhand_tn
#define GLCD_FONT_SECRETARYHAND_TR        u8g2_font_secretaryhand_tr
#define GLCD_FONT_SERAPHIMB1_TR           u8g2_font_seraphimb1_tr
#define GLCD_FONT_SHYLOCK_NBP_T_ALL       u8g2_font_shylock_nbp_t_all
#define GLCD_FONT_SHYLOCK_NBP_TF          u8g2_font_shylock_nbp_tf
#define GLCD_FONT_SHYLOCK_NBP_TN          u8g2_font_shylock_nbp_tn
#define GLCD_FONT_SHYLOCK_NBP_TR          u8g2_font_shylock_nbp_tr
#define GLCD_FONT_SIJI_T_6X10             u8g2_font_siji_t_6x10
#define GLCD_FONT_SIRCLIVETHEBOLD_TN      u8g2_font_sirclivethebold_tn
#define GLCD_FONT_SIRCLIVETHEBOLD_TR      u8g2_font_sirclivethebold_tr
#define GLCD_FONT_SIRCLIVE_TN             u8g2_font_sirclive_tn
#define GLCD_FONT_SIRCLIVE_TR             u8g2_font_sirclive_tr
#define GLCD_FONT_SMART_PATROL_NBP_TF     u8g2_font_smart_patrol_nbp_tf
#define GLCD_FONT_SMART_PATROL_NBP_TN     u8g2_font_smart_patrol_nbp_tn
#define GLCD_FONT_SMART_PATROL_NBP_TR     u8g2_font_smart_patrol_nbp_tr
#define GLCD_FONT_SQUIRREL_TN             u8g2_font_squirrel_tn
#define GLCD_FONT_SQUIRREL_TR             u8g2_font_squirrel_tr
#define GLCD_FONT_SQUIRREL_TU             u8g2_font_squirrel_tu
#define GLCD_FONT_STICKER_MEL_TN          u8g2_font_sticker_mel_tn
#define GLCD_FONT_STICKER_MEL_TR          u8g2_font_sticker_mel_tr
#define GLCD_FONT_SYNCHRONIZER_NBP_TF     u8g2_font_synchronizer_nbp_tf
#define GLCD_FONT_SYNCHRONIZER_NBP_TN     u8g2_font_synchronizer_nbp_tn
#define GLCD_FONT_SYNCHRONIZER_NBP_TR     u8g2_font_synchronizer_nbp_tr
#define GLCD_FONT_T0_11B_ME               u8g2_font_t0_11b_me
#define GLCD_FONT_T0_11B_MF               u8g2_font_t0_11b_mf
#define GLCD_FONT_T0_11B_MN               u8g2_font_t0_11b_mn
#define GLCD_FONT_T0_11B_MR               u8g2_font_t0_11b_mr
#define GLCD_FONT_T0_11B_TE               u8g2_font_t0_11b_te
#define GLCD_FONT_T0_11B_TF               u8g2_font_t0_11b_tf
#define GLCD_FONT_T0_11B_TN               u8g2_font_t0_11b_tn
#define GLCD_FONT_T0_11B_TR               u8g2_font_t0_11b_tr
#define GLCD_FONT_T0_11_ME                u8g2_font_t0_11_me
#define GLCD_FONT_T0_11_MF                u8g2_font_t0_11_mf
#define GLCD_FONT_T0_11_MN                u8g2_font_t0_11_mn
#define GLCD_FONT_T0_11_MR                u8g2_font_t0_11_mr
#define GLCD_FONT_T0_11_T_ALL             u8g2_font_t0_11_t_all
#define GLCD_FONT_T0_11_TE                u8g2_font_t0_11_te
#define GLCD_FONT_T0_11_TF                u8g2_font_t0_11_tf
#define GLCD_FONT_T0_11_TN                u8g2_font_t0_11_tn
#define GLCD_FONT_T0_11_TR                u8g2_font_t0_11_tr
#define GLCD_FONT_T0_12B_ME               u8g2_font_t0_12b_me
#define GLCD_FONT_T0_12B_MF               u8g2_font_t0_12b_mf
#define GLCD_FONT_T0_12B_MN               u8g2_font_t0_12b_mn
#define GLCD_FONT_T0_12B_MR               u8g2_font_t0_12b_mr
#define GLCD_FONT_T0_12B_TE               u8g2_font_t0_12b_te
#define GLCD_FONT_T0_12B_TF               u8g2_font_t0_12b_tf
#define GLCD_FONT_T0_12B_TN               u8g2_font_t0_12b_tn
#define GLCD_FONT_T0_12B_TR               u8g2_font_t0_12b_tr
#define GLCD_FONT_T0_12_ME                u8g2_font_t0_12_me
#define GLCD_FONT_T0_12_MF                u8g2_font_t0_12_mf
#define GLCD_FONT_T0_12_MN                u8g2_font_t0_12_mn
#define GLCD_FONT_T0_12_MR                u8g2_font_t0_12_mr
#define GLCD_FONT_T0_12_TE                u8g2_font_t0_12_te
#define GLCD_FONT_T0_12_TF                u8g2_font_t0_12_tf
#define GLCD_FONT_T0_12_TN                u8g2_font_t0_12_tn
#define GLCD_FONT_T0_12_TR                u8g2_font_t0_12_tr
#define GLCD_FONT_T0_13B_ME               u8g2_font_t0_13b_me
#define GLCD_FONT_T0_13B_MF               u8g2_font_t0_13b_mf
#define GLCD_FONT_T0_13B_MN               u8g2_font_t0_13b_mn
#define GLCD_FONT_T0_13B_MR               u8g2_font_t0_13b_mr
#define GLCD_FONT_T0_13B_TE               u8g2_font_t0_13b_te
#define GLCD_FONT_T0_13B_TF               u8g2_font_t0_13b_tf
#define GLCD_FONT_T0_13B_TN               u8g2_font_t0_13b_tn
#define GLCD_FONT_T0_13B_TR               u8g2_font_t0_13b_tr
#define GLCD_FONT_T0_13_ME                u8g2_font_t0_13_me
#define GLCD_FONT_T0_13_MF                u8g2_font_t0_13_mf
#define GLCD_FONT_T0_13_MN                u8g2_font_t0_13_mn
#define GLCD_FONT_T0_13_MR                u8g2_font_t0_13_mr
#define GLCD_FONT_T0_13_TE                u8g2_font_t0_13_te
#define GLCD_FONT_T0_13_TF                u8g2_font_t0_13_tf
#define GLCD_FONT_T0_13_TN                u8g2_font_t0_13_tn
#define GLCD_FONT_T0_13_TR                u8g2_font_t0_13_tr
#define GLCD_FONT_T0_14B_ME               u8g2_font_t0_14b_me
#define GLCD_FONT_T0_14B_MF               u8g2_font_t0_14b_mf
#define GLCD_FONT_T0_14B_MN               u8g2_font_t0_14b_mn
#define GLCD_FONT_T0_14B_MR               u8g2_font_t0_14b_mr
#define GLCD_FONT_T0_14B_TE               u8g2_font_t0_14b_te
#define GLCD_FONT_T0_14B_TF               u8g2_font_t0_14b_tf
#define GLCD_FONT_T0_14B_TN               u8g2_font_t0_14b_tn
#define GLCD_FONT_T0_14B_TR               u8g2_font_t0_14b_tr
#define GLCD_FONT_T0_14_ME                u8g2_font_t0_14_me
#define GLCD_FONT_T0_14_MF                u8g2_font_t0_14_mf
#define GLCD_FONT_T0_14_MN                u8g2_font_t0_14_mn
#define GLCD_FONT_T0_14_MR                u8g2_font_t0_14_mr
#define GLCD_FONT_T0_14_TE                u8g2_font_t0_14_te
#define GLCD_FONT_T0_14_TF                u8g2_font_t0_14_tf
#define GLCD_FONT_T0_14_TN                u8g2_font_t0_14_tn
#define GLCD_FONT_T0_14_TR                u8g2_font_t0_14_tr
#define GLCD_FONT_T0_15B_ME               u8g2_font_t0_15b_me
#define GLCD_FONT_T0_15B_MF               u8g2_font_t0_15b_mf
#define GLCD_FONT_T0_15B_MN               u8g2_font_t0_15b_mn
#define GLCD_FONT_T0_15B_MR               u8g2_font_t0_15b_mr
#define GLCD_FONT_T0_15B_TE               u8g2_font_t0_15b_te
#define GLCD_FONT_T0_15B_TF               u8g2_font_t0_15b_tf
#define GLCD_FONT_T0_15B_TN               u8g2_font_t0_15b_tn
#define GLCD_FONT_T0_15B_TR               u8g2_font_t0_15b_tr
#define GLCD_FONT_T0_15_ME                u8g2_font_t0_15_me
#define GLCD_FONT_T0_15_MF                u8g2_font_t0_15_mf
#define GLCD_FONT_T0_15_MN                u8g2_font_t0_15_mn
#define GLCD_FONT_T0_15_MR                u8g2_font_t0_15_mr
#define GLCD_FONT_T0_15_TE                u8g2_font_t0_15_te
#define GLCD_FONT_T0_15_TF                u8g2_font_t0_15_tf
#define GLCD_FONT_T0_15_TN                u8g2_font_t0_15_tn
#define GLCD_FONT_T0_15_TR                u8g2_font_t0_15_tr
#define GLCD_FONT_T0_16B_ME               u8g2_font_t0_16b_me
#define GLCD_FONT_T0_16B_MF               u8g2_font_t0_16b_mf
#define GLCD_FONT_T0_16B_MN               u8g2_font_t0_16b_mn
#define GLCD_FONT_T0_16B_MR               u8g2_font_t0_16b_mr
#define GLCD_FONT_T0_16B_TE               u8g2_font_t0_16b_te
#define GLCD_FONT_T0_16B_TF               u8g2_font_t0_16b_tf
#define GLCD_FONT_T0_16B_TN               u8g2_font_t0_16b_tn
#define GLCD_FONT_T0_16B_TR               u8g2_font_t0_16b_tr
#define GLCD_FONT_T0_16_ME                u8g2_font_t0_16_me
#define GLCD_FONT_T0_16_MF                u8g2_font_t0_16_mf
#define GLCD_FONT_T0_16_MN                u8g2_font_t0_16_mn
#define GLCD_FONT_T0_16_MR                u8g2_font_t0_16_mr
#define GLCD_FONT_T0_16_TE                u8g2_font_t0_16_te
#define GLCD_FONT_T0_16_TF                u8g2_font_t0_16_tf
#define GLCD_FONT_T0_16_TN                u8g2_font_t0_16_tn
#define GLCD_FONT_T0_16_TR                u8g2_font_t0_16_tr
#define GLCD_FONT_T0_17B_ME               u8g2_font_t0_17b_me
#define GLCD_FONT_T0_17B_MF               u8g2_font_t0_17b_mf
#define GLCD_FONT_T0_17B_MN               u8g2_font_t0_17b_mn
#define GLCD_FONT_T0_17B_MR               u8g2_font_t0_17b_mr
#define GLCD_FONT_T0_17B_TE               u8g2_font_t0_17b_te
#define GLCD_FONT_T0_17B_TF               u8g2_font_t0_17b_tf
#define GLCD_FONT_T0_17B_TN               u8g2_font_t0_17b_tn
#define GLCD_FONT_T0_17B_TR               u8g2_font_t0_17b_tr
#define GLCD_FONT_T0_17_ME                u8g2_font_t0_17_me
#define GLCD_FONT_T0_17_MF                u8g2_font_t0_17_mf
#define GLCD_FONT_T0_17_MN                u8g2_font_t0_17_mn
#define GLCD_FONT_T0_17_MR                u8g2_font_t0_17_mr
#define GLCD_FONT_T0_17_TE                u8g2_font_t0_17_te
#define GLCD_FONT_T0_17_TF                u8g2_font_t0_17_tf
#define GLCD_FONT_T0_17_TN                u8g2_font_t0_17_tn
#define GLCD_FONT_T0_17_TR                u8g2_font_t0_17_tr
#define GLCD_FONT_T0_18B_ME               u8g2_font_t0_18b_me
#define GLCD_FONT_T0_18B_MF               u8g2_font_t0_18b_mf
#define GLCD_FONT_T0_18B_MN               u8g2_font_t0_18b_mn
#define GLCD_FONT_T0_18B_MR               u8g2_font_t0_18b_mr
#define GLCD_FONT_T0_18B_TE               u8g2_font_t0_18b_te
#define GLCD_FONT_T0_18B_TF               u8g2_font_t0_18b_tf
#define GLCD_FONT_T0_18B_TN               u8g2_font_t0_18b_tn
#define GLCD_FONT_T0_18B_TR               u8g2_font_t0_18b_tr
#define GLCD_FONT_T0_18_ME                u8g2_font_t0_18_me
#define GLCD_FONT_T0_18_MF                u8g2_font_t0_18_mf
#define GLCD_FONT_T0_18_MN                u8g2_font_t0_18_mn
#define GLCD_FONT_T0_18_MR                u8g2_font_t0_18_mr
#define GLCD_FONT_T0_18_TE                u8g2_font_t0_18_te
#define GLCD_FONT_T0_18_TF                u8g2_font_t0_18_tf
#define GLCD_FONT_T0_18_TN                u8g2_font_t0_18_tn
#define GLCD_FONT_T0_18_TR                u8g2_font_t0_18_tr
#define GLCD_FONT_T0_22B_ME               u8g2_font_t0_22b_me
#define GLCD_FONT_T0_22B_MF               u8g2_font_t0_22b_mf
#define GLCD_FONT_T0_22B_MN               u8g2_font_t0_22b_mn
#define GLCD_FONT_T0_22B_MR               u8g2_font_t0_22b_mr
#define GLCD_FONT_T0_22B_TE               u8g2_font_t0_22b_te
#define GLCD_FONT_T0_22B_TF               u8g2_font_t0_22b_tf
#define GLCD_FONT_T0_22B_TN               u8g2_font_t0_22b_tn
#define GLCD_FONT_T0_22B_TR               u8g2_font_t0_22b_tr
#define GLCD_FONT_T0_22_ME                u8g2_font_t0_22_me
#define GLCD_FONT_T0_22_MF                u8g2_font_t0_22_mf
#define GLCD_FONT_T0_22_MN                u8g2_font_t0_22_mn
#define GLCD_FONT_T0_22_MR                u8g2_font_t0_22_mr
#define GLCD_FONT_T0_22_TE                u8g2_font_t0_22_te
#define GLCD_FONT_T0_22_TF                u8g2_font_t0_22_tf
#define GLCD_FONT_T0_22_TN                u8g2_font_t0_22_tn
#define GLCD_FONT_T0_22_TR                u8g2_font_t0_22_tr
#define GLCD_FONT_TALLPIX_TR              u8g2_font_tallpix_tr
#define GLCD_FONT_TENFATGUYS_T_ALL        u8g2_font_tenfatguys_t_all
#define GLCD_FONT_TENFATGUYS_TF           u8g2_font_tenfatguys_tf
#define GLCD_FONT_TENFATGUYS_TN           u8g2_font_tenfatguys_tn
#define GLCD_FONT_TENFATGUYS_TR           u8g2_font_tenfatguys_tr
#define GLCD_FONT_TENFATGUYS_TU           u8g2_font_tenfatguys_tu
#define GLCD_FONT_TENSTAMPS_MF            u8g2_font_tenstamps_mf
#define GLCD_FONT_TENSTAMPS_MN            u8g2_font_tenstamps_mn
#define GLCD_FONT_TENSTAMPS_MR            u8g2_font_tenstamps_mr
#define GLCD_FONT_TENSTAMPS_MU            u8g2_font_tenstamps_mu
#define GLCD_FONT_TENTHINGUYS_T_ALL       u8g2_font_tenthinguys_t_all
#define GLCD_FONT_TENTHINGUYS_TF          u8g2_font_tenthinguys_tf
#define GLCD_FONT_TENTHINGUYS_TN          u8g2_font_tenthinguys_tn
#define GLCD_FONT_TENTHINGUYS_TR          u8g2_font_tenthinguys_tr
#define GLCD_FONT_TENTHINGUYS_TU          u8g2_font_tenthinguys_tu
#define GLCD_FONT_TENTHINNERGUYS_T_ALL    u8g2_font_tenthinnerguys_t_all
#define GLCD_FONT_TENTHINNERGUYS_TF       u8g2_font_tenthinnerguys_tf
#define GLCD_FONT_TENTHINNERGUYS_TN       u8g2_font_tenthinnerguys_tn
#define GLCD_FONT_TENTHINNERGUYS_TR       u8g2_font_tenthinnerguys_tr
#define GLCD_FONT_TENTHINNERGUYS_TU       u8g2_font_tenthinnerguys_tu
#define GLCD_FONT_TIMB08_TF               u8g2_font_timB08_tf
#define GLCD_FONT_TIMB08_TN               u8g2_font_timB08_tn
#define GLCD_FONT_TIMB08_TR               u8g2_font_timB08_tr
#define GLCD_FONT_TIMB10_TF               u8g2_font_timB10_tf
#define GLCD_FONT_TIMB10_TN               u8g2_font_timB10_tn
#define GLCD_FONT_TIMB10_TR               u8g2_font_timB10_tr
#define GLCD_FONT_TIMB12_TF               u8g2_font_timB12_tf
#define GLCD_FONT_TIMB12_TN               u8g2_font_timB12_tn
#define GLCD_FONT_TIMB12_TR               u8g2_font_timB12_tr
#define GLCD_FONT_TIMB14_TF               u8g2_font_timB14_tf
#define GLCD_FONT_TIMB14_TN               u8g2_font_timB14_tn
#define GLCD_FONT_TIMB14_TR               u8g2_font_timB14_tr
#define GLCD_FONT_TIMB18_TF               u8g2_font_timB18_tf
#define GLCD_FONT_TIMB18_TN               u8g2_font_timB18_tn
#define GLCD_FONT_TIMB18_TR               u8g2_font_timB18_tr
#define GLCD_FONT_TIMB24_TF               u8g2_font_timB24_tf
#define GLCD_FONT_TIMB24_TN               u8g2_font_timB24_tn
#define GLCD_FONT_TIMB24_TR               u8g2_font_timB24_tr
#define GLCD_FONT_TIMESNEWPIXEL_TR        u8g2_font_TimesNewPixel_tr
#define GLCD_FONT_TIMR08_TF               u8g2_font_timR08_tf
#define GLCD_FONT_TIMR08_TN               u8g2_font_timR08_tn
#define GLCD_FONT_TIMR08_TR               u8g2_font_timR08_tr
#define GLCD_FONT_TIMR10_TF               u8g2_font_timR10_tf
#define GLCD_FONT_TIMR10_TN               u8g2_font_timR10_tn
#define GLCD_FONT_TIMR10_TR               u8g2_font_timR10_tr
#define GLCD_FONT_TIMR12_TF               u8g2_font_timR12_tf
#define GLCD_FONT_TIMR12_TN               u8g2_font_timR12_tn
#define GLCD_FONT_TIMR12_TR               u8g2_font_timR12_tr
#define GLCD_FONT_TIMR14_TF               u8g2_font_timR14_tf
#define GLCD_FONT_TIMR14_TN               u8g2_font_timR14_tn
#define GLCD_FONT_TIMR14_TR               u8g2_font_timR14_tr
#define GLCD_FONT_TIMR18_TF               u8g2_font_timR18_tf
#define GLCD_FONT_TIMR18_TN               u8g2_font_timR18_tn
#define GLCD_FONT_TIMR18_TR               u8g2_font_timR18_tr
#define GLCD_FONT_TIMR24_TF               u8g2_font_timR24_tf
#define GLCD_FONT_TIMR24_TN               u8g2_font_timR24_tn
#define GLCD_FONT_TIMR24_TR               u8g2_font_timR24_tr
#define GLCD_FONT_TINYTIM_TF              u8g2_font_tinytim_tf
#define GLCD_FONT_TINYTIM_TN              u8g2_font_tinytim_tn
#define GLCD_FONT_TINYTIM_TR              u8g2_font_tinytim_tr
#define GLCD_FONT_TOM_THUMB_4X6_ME        u8g2_font_tom_thumb_4x6_me
#define GLCD_FONT_TOM_THUMB_4X6_MF        u8g2_font_tom_thumb_4x6_mf
#define GLCD_FONT_TOM_THUMB_4X6_MN        u8g2_font_tom_thumb_4x6_mn
#define GLCD_FONT_TOM_THUMB_4X6_MR        u8g2_font_tom_thumb_4x6_mr
#define GLCD_FONT_TOM_THUMB_4X6_T_ALL     u8g2_font_tom_thumb_4x6_t_all
#define GLCD_FONT_TOM_THUMB_4X6_TE        u8g2_font_tom_thumb_4x6_te
#define GLCD_FONT_TOM_THUMB_4X6_TF        u8g2_font_tom_thumb_4x6_tf
#define GLCD_FONT_TOM_THUMB_4X6_TN        u8g2_font_tom_thumb_4x6_tn
#define GLCD_FONT_TOM_THUMB_4X6_TR        u8g2_font_tom_thumb_4x6_tr
#define GLCD_FONT_TOOSEORNAMENT_TF        u8g2_font_tooseornament_tf
#define GLCD_FONT_TOOSEORNAMENT_TN        u8g2_font_tooseornament_tn
#define GLCD_FONT_TOOSEORNAMENT_TR        u8g2_font_tooseornament_tr
#define GLCD_FONT_TORUSSANSBOLD8_8N       u8g2_font_torussansbold8_8n
#define GLCD_FONT_TORUSSANSBOLD8_8R       u8g2_font_torussansbold8_8r
#define GLCD_FONT_TORUSSANSBOLD8_8U       u8g2_font_torussansbold8_8u
#define GLCD_FONT_TRIXEL_SQUARE_TF        u8g2_font_trixel_square_tf
#define GLCD_FONT_TRIXEL_SQUARE_TN        u8g2_font_trixel_square_tn
#define GLCD_FONT_TRIXEL_SQUARE_TR        u8g2_font_trixel_square_tr
#define GLCD_FONT_TWELVEDINGS_T_ALL       u8g2_font_twelvedings_t_all
#define GLCD_FONT_U8GLIB_4_HF             u8g2_font_u8glib_4_hf
#define GLCD_FONT_U8GLIB_4_HR             u8g2_font_u8glib_4_hr
#define GLCD_FONT_U8GLIB_4_TF             u8g2_font_u8glib_4_tf
#define GLCD_FONT_U8GLIB_4_TR             u8g2_font_u8glib_4_tr
#define GLCD_FONT_UNIFONT_H_SYMBOLS       u8g2_font_unifont_h_symbols
#define GLCD_FONT_UNIFONT_T_0_72_73       u8g2_font_unifont_t_0_72_73
#define GLCD_FONT_UNIFONT_T_0_75          u8g2_font_unifont_t_0_75
#define GLCD_FONT_UNIFONT_T_0_76          u8g2_font_unifont_t_0_76
#define GLCD_FONT_UNIFONT_T_0_77          u8g2_font_unifont_t_0_77
#define GLCD_FONT_UNIFONT_T_0_78_79       u8g2_font_unifont_t_0_78_79
#define GLCD_FONT_UNIFONT_T_0_86          u8g2_font_unifont_t_0_86
#define GLCD_FONT_UNIFONT_T_72_73         u8g2_font_unifont_t_72_73
#define GLCD_FONT_UNIFONT_T_75            u8g2_font_unifont_t_75
#define GLCD_FONT_UNIFONT_T_76            u8g2_font_unifont_t_76
#define GLCD_FONT_UNIFONT_T_77            u8g2_font_unifont_t_77
#define GLCD_FONT_UNIFONT_T_78_79         u8g2_font_unifont_t_78_79
#define GLCD_FONT_UNIFONT_T_86            u8g2_font_unifont_t_86
#define GLCD_FONT_UNIFONT_T_ANIMALS       u8g2_font_unifont_t_animals
#define GLCD_FONT_UNIFONT_T_ARABIC        u8g2_font_unifont_t_arabic
#define GLCD_FONT_UNIFONT_T_BENGALI       u8g2_font_unifont_t_bengali
#define GLCD_FONT_UNIFONT_T_CARDS         u8g2_font_unifont_t_cards
#define GLCD_FONT_UNIFONT_T_CHINESE1      u8g2_font_unifont_t_chinese1
#define GLCD_FONT_UNIFONT_T_CHINESE2      u8g2_font_unifont_t_chinese2
#define GLCD_FONT_UNIFONT_T_CHINESE3      u8g2_font_unifont_t_chinese3
#define GLCD_FONT_UNIFONT_T_CYRILLIC      u8g2_font_unifont_t_cyrillic
#define GLCD_FONT_UNIFONT_T_DEVANAGARI    u8g2_font_unifont_t_devanagari
#define GLCD_FONT_UNIFONT_T_DOMINO        u8g2_font_unifont_t_domino
#define GLCD_FONT_UNIFONT_T_EMOTICONS     u8g2_font_unifont_t_emoticons
#define GLCD_FONT_UNIFONT_TE              u8g2_font_unifont_te
#define GLCD_FONT_UNIFONT_T_EXTENDED      u8g2_font_unifont_t_extended
#define GLCD_FONT_UNIFONT_TF              u8g2_font_unifont_tf
#define GLCD_FONT_UNIFONT_T_GREEK         u8g2_font_unifont_t_greek
#define GLCD_FONT_UNIFONT_T_HEBREW        u8g2_font_unifont_t_hebrew
#define GLCD_FONT_UNIFONT_T_JAPANESE1     u8g2_font_unifont_t_japanese1
#define GLCD_FONT_UNIFONT_T_JAPANESE2     u8g2_font_unifont_t_japanese2
#define GLCD_FONT_UNIFONT_T_JAPANESE3     u8g2_font_unifont_t_japanese3
#define GLCD_FONT_UNIFONT_T_KOREAN1       u8g2_font_unifont_t_korean1
#define GLCD_FONT_UNIFONT_T_KOREAN2       u8g2_font_unifont_t_korean2
#define GLCD_FONT_UNIFONT_T_LATIN         u8g2_font_unifont_t_latin
#define GLCD_FONT_UNIFONT_T_POLISH        u8g2_font_unifont_t_polish
#define GLCD_FONT_UNIFONT_TR              u8g2_font_unifont_tr
#define GLCD_FONT_UNIFONT_T_SYMBOLS       u8g2_font_unifont_t_symbols
#define GLCD_FONT_UNIFONT_T_TIBETAN       u8g2_font_unifont_t_tibetan
#define GLCD_FONT_UNIFONT_T_URDU          u8g2_font_unifont_t_urdu
#define GLCD_FONT_UNIFONT_T_VIETNAMESE1   u8g2_font_unifont_t_vietnamese1
#define GLCD_FONT_UNIFONT_T_VIETNAMESE2   u8g2_font_unifont_t_vietnamese2
#define GLCD_FONT_UNIFONT_T_WEATHER       u8g2_font_unifont_t_weather
#define GLCD_FONT_UNTITLED16PIXELSANSSERIFBITMAP_TR u8g2_font_Untitled16PixelSansSerifBitmap_tr
#define GLCD_FONT_VICTORIABOLD8_8N        u8g2_font_victoriabold8_8n
#define GLCD_FONT_VICTORIABOLD8_8R        u8g2_font_victoriabold8_8r
#define GLCD_FONT_VICTORIABOLD8_8U        u8g2_font_victoriabold8_8u
#define GLCD_FONT_VICTORIAMEDIUM8_8N      u8g2_font_victoriamedium8_8n
#define GLCD_FONT_VICTORIAMEDIUM8_8R      u8g2_font_victoriamedium8_8r
#define GLCD_FONT_VICTORIAMEDIUM8_8U      u8g2_font_victoriamedium8_8u
#define GLCD_FONT_WIZZARD_TR              u8g2_font_Wizzard_tr
#define GLCD_FONT_WQY12_T_CHINESE1        u8g2_font_wqy12_t_chinese1
#define GLCD_FONT_WQY12_T_CHINESE2        u8g2_font_wqy12_t_chinese2
#define GLCD_FONT_WQY12_T_CHINESE3        u8g2_font_wqy12_t_chinese3
#define GLCD_FONT_WQY12_T_GB2312A         u8g2_font_wqy12_t_gb2312a
#define GLCD_FONT_WQY12_T_GB2312B         u8g2_font_wqy12_t_gb2312b
#define GLCD_FONT_WQY12_T_GB2312          u8g2_font_wqy12_t_gb2312
#define GLCD_FONT_WQY13_T_CHINESE1        u8g2_font_wqy13_t_chinese1
#define GLCD_FONT_WQY13_T_CHINESE2        u8g2_font_wqy13_t_chinese2
#define GLCD_FONT_WQY13_T_CHINESE3        u8g2_font_wqy13_t_chinese3
#define GLCD_FONT_WQY13_T_GB2312A         u8g2_font_wqy13_t_gb2312a
#define GLCD_FONT_WQY13_T_GB2312B         u8g2_font_wqy13_t_gb2312b
#define GLCD_FONT_WQY13_T_GB2312          u8g2_font_wqy13_t_gb2312
#define GLCD_FONT_WQY14_T_CHINESE1        u8g2_font_wqy14_t_chinese1
#define GLCD_FONT_WQY14_T_CHINESE2        u8g2_font_wqy14_t_chinese2
#define GLCD_FONT_WQY14_T_CHINESE3        u8g2_font_wqy14_t_chinese3
#define GLCD_FONT_WQY14_T_GB2312A         u8g2_font_wqy14_t_gb2312a
#define GLCD_FONT_WQY14_T_GB2312B         u8g2_font_wqy14_t_gb2312b
#define GLCD_FONT_WQY14_T_GB2312          u8g2_font_wqy14_t_gb2312
#define GLCD_FONT_WQY15_T_CHINESE1        u8g2_font_wqy15_t_chinese1
#define GLCD_FONT_WQY15_T_CHINESE2        u8g2_font_wqy15_t_chinese2
#define GLCD_FONT_WQY15_T_CHINESE3        u8g2_font_wqy15_t_chinese3
#define GLCD_FONT_WQY15_T_GB2312A         u8g2_font_wqy15_t_gb2312a
#define GLCD_FONT_WQY15_T_GB2312B         u8g2_font_wqy15_t_gb2312b
#define GLCD_FONT_WQY15_T_GB2312          u8g2_font_wqy15_t_gb2312
#define GLCD_FONT_WQY16_T_CHINESE1        u8g2_font_wqy16_t_chinese1
#define GLCD_FONT_WQY16_T_CHINESE2        u8g2_font_wqy16_t_chinese2
#define GLCD_FONT_WQY16_T_CHINESE3        u8g2_font_wqy16_t_chinese3
#define GLCD_FONT_WQY16_T_GB2312A         u8g2_font_wqy16_t_gb2312a
#define GLCD_FONT_WQY16_T_GB2312B         u8g2_font_wqy16_t_gb2312b
#define GLCD_FONT_WQY16_T_GB2312          u8g2_font_wqy16_t_gb2312
#define glcd_set_font(font)               u8g2_SetFont(&glcd, font)

#define GLCD_FONT_MODE_TRANSPARENT        1
#define GLCD_FONT_MODE_SOLID              0
#define glcd_set_font_mode(mode)          u8g2_SetFontMode(&glcd, mode)
#define glcd_set_font_direction(...)      u8g2_SetFontDirection(&glcd, __VA_ARGS__)

#define glcd_get_glyph_width(...)         u8g2_GetGlyphWidth(&glcd, __VA_ARGS__)
#define glcd_get_str_width(...)           u8g2_GetStrWidth(&glcd, __VA_ARGS__)

#define glcd_draw_glyph(...)              u8g2_DrawGlyph(&glcd, __VA_ARGS__)
#define glcd_draw_string(...)             u8g2_DrawStr(&glcd, __VA_ARGS__)
int16_t glcd_draw_string_P(int16_t x, int16_t y, const char *s);

#endif /* !__GLCD_MONO_H */
