/*
 * Copyright (c) 2017 Erik Kunze <ethersex@erik-kunze.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * For more information on the GPL, please go to:
 * http://www.gnu.org/copyleft/gpl.html
 */

#ifndef __GLCD_COLOR_H
#define __GLCD_COLOR_H

#undef noinline
#include "libs/ucglib/ucg.h"

typedef ucg_t glcd_t;

#define glcd_get_width()                  ucg_GetWidth(&glcd)
#define glcd_get_height()                 ucg_GetHeight(&glcd)

#define glcd_set_clip_range(...)          ucg_SetClipRange(&glcd, __VA_ARGS__)
#define glcd_set_max_clip_range()         ucg_SetMaxClipRange(&glcd)
#define glcd_reset_clip_range()           ucg_SetMaxClipRange(&glcd)

#define glcd_set_color(...)               ucg_SetColor(&glcd, __VA_ARGS__)
#define glcd_draw_pixel(...)              ucg_DrawPixel(&glcd, __VA_ARGS__)

#define glcd_draw_90_line(...)            ucg_Draw90Line(&glcd, __VA_ARGS__)
#define glcd_draw_h_line(...)             ucg_DrawHLine(&glcd, __VA_ARGS__)
#define glcd_draw_v_line(...)             ucg_DrawVLine(&glcd, __VA_ARGS__)
#define glcd_draw_hr_line(...)            ucg_DrawHRLine(&glcd, __VA_ARGS__)
#define glcd_draw_line(...)               ucg_DrawLine(&glcd, __VA_ARGS__)
#define glcd_draw_gradient_line(...)      ucg_DrawGradientLine(&glcd, __VA_ARGS__)

#define glcd_clear_screen()               ucg_ClearScreen(&glcd)
#define glcd_draw_box(...)                ucg_DrawBox(&glcd, __VA_ARGS__)
#define glcd_draw_r_box(...)              ucg_DrawRBox(&glcd, __VA_ARGS__)
#define glcd_draw_gradient_box(...)       ucg_DrawGradientBox(&glcd, __VA_ARGS__)
#define glcd_draw_frame(...)              ucg_DrawFrame(&glcd, __VA_ARGS__)
#define glcd_draw_r_frame(...)            ucg_DrawRFrame(&glcd, __VA_ARGS__)

#define glcd_draw_disc(...)               ucg_DrawDisc(&glcd, __VA_ARGS__)
#define glcd_draw_circle(...)             ucg_DrawCircle(&glcd, __VA_ARGS__)
#define glcd_draw_triangle(...)           ucg_drawTriangle(&glcd, __VA_ARGS__)
#define glcd_draw_tetragon(...)           ucg_DrawTetragon(&glcd, __VA_ARGS__)
/*
#define glcd_draw_transparent_bitmap_line(...) \
                                          ucg_DrawTransparentBitmapLine(&glcd, __VA_ARGS__)
#define glcd_draw_bitmap_line(...)        ucg_DrawBitmapLine(&glcd, __VA_ARGS__)
*/
#define glcd_set_rotate_0()               ucg_UndoRotate(&glcd)
#define glcd_set_rotate_90()              ucg_SetRotate90(&glcd)
#define glcd_set_rotate_180()             ucg_SetRotate180(&glcd)
#define glcd_set_rotate_270()             ucg_SetRotate270(&glcd)

#define glcd_set_scale_1x1()              ucg_UndoScale(&glcd)
#define glcd_set_scale_2x2()              ucg_SetScale2x2(&glcd)

#define GLCD_FONT_04B_03B_HF              ucg_font_04b_03b_hf
#define GLCD_FONT_04B_03B_HN              ucg_font_04b_03b_hn
#define GLCD_FONT_04B_03B_HR              ucg_font_04b_03b_hr
#define GLCD_FONT_04B_03B_TF              ucg_font_04b_03b_tf
#define GLCD_FONT_04B_03B_TN              ucg_font_04b_03b_tn
#define GLCD_FONT_04B_03B_TR              ucg_font_04b_03b_tr
#define GLCD_FONT_04B_03_HF               ucg_font_04b_03_hf
#define GLCD_FONT_04B_03_HN               ucg_font_04b_03_hn
#define GLCD_FONT_04B_03_HR               ucg_font_04b_03_hr
#define GLCD_FONT_04B_03_TF               ucg_font_04b_03_tf
#define GLCD_FONT_04B_03_TN               ucg_font_04b_03_tn
#define GLCD_FONT_04B_03_TR               ucg_font_04b_03_tr
#define GLCD_FONT_04B_24_HF               ucg_font_04b_24_hf
#define GLCD_FONT_04B_24_HN               ucg_font_04b_24_hn
#define GLCD_FONT_04B_24_HR               ucg_font_04b_24_hr
#define GLCD_FONT_04B_24_TF               ucg_font_04b_24_tf
#define GLCD_FONT_04B_24_TN               ucg_font_04b_24_tn
#define GLCD_FONT_04B_24_TR               ucg_font_04b_24_tr
#define GLCD_FONT_10X20_67_75             ucg_font_10x20_67_75
#define GLCD_FONT_10X20_78_79             ucg_font_10x20_78_79
#define GLCD_FONT_10X20_MF                ucg_font_10x20_mf
#define GLCD_FONT_10X20_MR                ucg_font_10x20_mr
#define GLCD_FONT_10X20_TF                ucg_font_10x20_tf
#define GLCD_FONT_10X20_TR                ucg_font_10x20_tr
#define GLCD_FONT_4X6_MF                  ucg_font_4x6_mf
#define GLCD_FONT_4X6_MR                  ucg_font_4x6_mr
#define GLCD_FONT_4X6_TF                  ucg_font_4x6_tf
#define GLCD_FONT_4X6_TR                  ucg_font_4x6_tr
#define GLCD_FONT_5X7_8F                  ucg_font_5x7_8f
#define GLCD_FONT_5X7_8R                  ucg_font_5x7_8r
#define GLCD_FONT_5X7_MF                  ucg_font_5x7_mf
#define GLCD_FONT_5X7_MR                  ucg_font_5x7_mr
#define GLCD_FONT_5X7_TF                  ucg_font_5x7_tf
#define GLCD_FONT_5X7_TR                  ucg_font_5x7_tr
#define GLCD_FONT_5X8_8F                  ucg_font_5x8_8f
#define GLCD_FONT_5X8_8R                  ucg_font_5x8_8r
#define GLCD_FONT_5X8_MF                  ucg_font_5x8_mf
#define GLCD_FONT_5X8_MR                  ucg_font_5x8_mr
#define GLCD_FONT_5X8_TF                  ucg_font_5x8_tf
#define GLCD_FONT_5X8_TR                  ucg_font_5x8_tr
#define GLCD_FONT_6X10_MF                 ucg_font_6x10_mf
#define GLCD_FONT_6X10_MR                 ucg_font_6x10_mr
#define GLCD_FONT_6X10_TF                 ucg_font_6x10_tf
#define GLCD_FONT_6X10_TR                 ucg_font_6x10_tr
#define GLCD_FONT_6X12_67_75              ucg_font_6x12_67_75
#define GLCD_FONT_6X12_75                 ucg_font_6x12_75
#define GLCD_FONT_6X12_78_79              ucg_font_6x12_78_79
#define GLCD_FONT_6X12_MF                 ucg_font_6x12_mf
#define GLCD_FONT_6X12_MR                 ucg_font_6x12_mr
#define GLCD_FONT_6X12_TF                 ucg_font_6x12_tf
#define GLCD_FONT_6X12_TR                 ucg_font_6x12_tr
#define GLCD_FONT_6X13_67_75              ucg_font_6x13_67_75
#define GLCD_FONT_6X13_78_79              ucg_font_6x13_78_79
#define GLCD_FONT_6X13B_TF                ucg_font_6x13B_tf
#define GLCD_FONT_6X13B_TR                ucg_font_6x13B_tr
#define GLCD_FONT_6X13_MF                 ucg_font_6x13_mf
#define GLCD_FONT_6X13_MR                 ucg_font_6x13_mr
#define GLCD_FONT_6X13O_TF                ucg_font_6x13O_tf
#define GLCD_FONT_6X13O_TR                ucg_font_6x13O_tr
#define GLCD_FONT_6X13_TF                 ucg_font_6x13_tf
#define GLCD_FONT_6X13_TR                 ucg_font_6x13_tr
#define GLCD_FONT_7X13_67_75              ucg_font_7x13_67_75
#define GLCD_FONT_7X13_78_79              ucg_font_7x13_78_79
#define GLCD_FONT_7X13B_TF                ucg_font_7x13B_tf
#define GLCD_FONT_7X13B_TR                ucg_font_7x13B_tr
#define GLCD_FONT_7X13_MF                 ucg_font_7x13_mf
#define GLCD_FONT_7X13_MR                 ucg_font_7x13_mr
#define GLCD_FONT_7X13O_TF                ucg_font_7x13O_tf
#define GLCD_FONT_7X13O_TR                ucg_font_7x13O_tr
#define GLCD_FONT_7X13_TF                 ucg_font_7x13_tf
#define GLCD_FONT_7X13_TR                 ucg_font_7x13_tr
#define GLCD_FONT_7X14B_MF                ucg_font_7x14B_mf
#define GLCD_FONT_7X14B_MR                ucg_font_7x14B_mr
#define GLCD_FONT_7X14B_TF                ucg_font_7x14B_tf
#define GLCD_FONT_7X14B_TR                ucg_font_7x14B_tr
#define GLCD_FONT_7X14_MF                 ucg_font_7x14_mf
#define GLCD_FONT_7X14_MR                 ucg_font_7x14_mr
#define GLCD_FONT_7X14_TF                 ucg_font_7x14_tf
#define GLCD_FONT_7X14_TR                 ucg_font_7x14_tr
#define GLCD_FONT_8X13_67_75              ucg_font_8x13_67_75
#define GLCD_FONT_8X13B_MF                ucg_font_8x13B_mf
#define GLCD_FONT_8X13B_MR                ucg_font_8x13B_mr
#define GLCD_FONT_8X13B_TF                ucg_font_8x13B_tf
#define GLCD_FONT_8X13B_TR                ucg_font_8x13B_tr
#define GLCD_FONT_8X13_MF                 ucg_font_8x13_mf
#define GLCD_FONT_8X13_MR                 ucg_font_8x13_mr
#define GLCD_FONT_8X13O_MF                ucg_font_8x13O_mf
#define GLCD_FONT_8X13O_MR                ucg_font_8x13O_mr
#define GLCD_FONT_8X13O_TF                ucg_font_8x13O_tf
#define GLCD_FONT_8X13O_TR                ucg_font_8x13O_tr
#define GLCD_FONT_8X13_TF                 ucg_font_8x13_tf
#define GLCD_FONT_8X13_TR                 ucg_font_8x13_tr
#define GLCD_FONT_9X15_67_75              ucg_font_9x15_67_75
#define GLCD_FONT_9X15_78_79              ucg_font_9x15_78_79
#define GLCD_FONT_9X15B_MF                ucg_font_9x15B_mf
#define GLCD_FONT_9X15B_MR                ucg_font_9x15B_mr
#define GLCD_FONT_9X15B_TF                ucg_font_9x15B_tf
#define GLCD_FONT_9X15B_TR                ucg_font_9x15B_tr
#define GLCD_FONT_9X15_MF                 ucg_font_9x15_mf
#define GLCD_FONT_9X15_MR                 ucg_font_9x15_mr
#define GLCD_FONT_9X15_TF                 ucg_font_9x15_tf
#define GLCD_FONT_9X15_TR                 ucg_font_9x15_tr
#define GLCD_FONT_9X18_67_75              ucg_font_9x18_67_75
#define GLCD_FONT_9X18_78_79              ucg_font_9x18_78_79
#define GLCD_FONT_9X18B_MF                ucg_font_9x18B_mf
#define GLCD_FONT_9X18B_MR                ucg_font_9x18B_mr
#define GLCD_FONT_9X18B_TF                ucg_font_9x18B_tf
#define GLCD_FONT_9X18B_TR                ucg_font_9x18B_tr
#define GLCD_FONT_9X18_MF                 ucg_font_9x18_mf
#define GLCD_FONT_9X18_MR                 ucg_font_9x18_mr
#define GLCD_FONT_9X18_TF                 ucg_font_9x18_tf
#define GLCD_FONT_9X18_TR                 ucg_font_9x18_tr
#define GLCD_FONT_AMSTRAD_CPC_8F          ucg_font_amstrad_cpc_8f
#define GLCD_FONT_AMSTRAD_CPC_8R          ucg_font_amstrad_cpc_8r
#define GLCD_FONT_BABY_HF                 ucg_font_baby_hf
#define GLCD_FONT_BABY_HN                 ucg_font_baby_hn
#define GLCD_FONT_BABY_HR                 ucg_font_baby_hr
#define GLCD_FONT_BABY_TF                 ucg_font_baby_tf
#define GLCD_FONT_BABY_TN                 ucg_font_baby_tn
#define GLCD_FONT_BABY_TR                 ucg_font_baby_tr
#define GLCD_FONT_BLIPFEST_07_HF          ucg_font_blipfest_07_hf
#define GLCD_FONT_BLIPFEST_07_HN          ucg_font_blipfest_07_hn
#define GLCD_FONT_BLIPFEST_07_HR          ucg_font_blipfest_07_hr
#define GLCD_FONT_BLIPFEST_07_TF          ucg_font_blipfest_07_tf
#define GLCD_FONT_BLIPFEST_07_TN          ucg_font_blipfest_07_tn
#define GLCD_FONT_BLIPFEST_07_TR          ucg_font_blipfest_07_tr
#define GLCD_FONT_CHIKITA_HF              ucg_font_chikita_hf
#define GLCD_FONT_CHIKITA_HN              ucg_font_chikita_hn
#define GLCD_FONT_CHIKITA_HR              ucg_font_chikita_hr
#define GLCD_FONT_CHIKITA_TF              ucg_font_chikita_tf
#define GLCD_FONT_CHIKITA_TN              ucg_font_chikita_tn
#define GLCD_FONT_CHIKITA_TR              ucg_font_chikita_tr
#define GLCD_FONT_COURB08_MF              ucg_font_courB08_mf
#define GLCD_FONT_COURB08_MR              ucg_font_courB08_mr
#define GLCD_FONT_COURB08_TF              ucg_font_courB08_tf
#define GLCD_FONT_COURB08_TR              ucg_font_courB08_tr
#define GLCD_FONT_COURB10_MF              ucg_font_courB10_mf
#define GLCD_FONT_COURB10_MR              ucg_font_courB10_mr
#define GLCD_FONT_COURB10_TF              ucg_font_courB10_tf
#define GLCD_FONT_COURB10_TR              ucg_font_courB10_tr
#define GLCD_FONT_COURB12_MF              ucg_font_courB12_mf
#define GLCD_FONT_COURB12_MR              ucg_font_courB12_mr
#define GLCD_FONT_COURB12_TF              ucg_font_courB12_tf
#define GLCD_FONT_COURB12_TR              ucg_font_courB12_tr
#define GLCD_FONT_COURB14_MF              ucg_font_courB14_mf
#define GLCD_FONT_COURB14_MR              ucg_font_courB14_mr
#define GLCD_FONT_COURB14_TF              ucg_font_courB14_tf
#define GLCD_FONT_COURB14_TR              ucg_font_courB14_tr
#define GLCD_FONT_COURB18_MF              ucg_font_courB18_mf
#define GLCD_FONT_COURB18_MN              ucg_font_courB18_mn
#define GLCD_FONT_COURB18_MR              ucg_font_courB18_mr
#define GLCD_FONT_COURB18_TF              ucg_font_courB18_tf
#define GLCD_FONT_COURB18_TN              ucg_font_courB18_tn
#define GLCD_FONT_COURB18_TR              ucg_font_courB18_tr
#define GLCD_FONT_COURB24_MF              ucg_font_courB24_mf
#define GLCD_FONT_COURB24_MN              ucg_font_courB24_mn
#define GLCD_FONT_COURB24_MR              ucg_font_courB24_mr
#define GLCD_FONT_COURB24_TF              ucg_font_courB24_tf
#define GLCD_FONT_COURB24_TN              ucg_font_courB24_tn
#define GLCD_FONT_COURB24_TR              ucg_font_courB24_tr
#define GLCD_FONT_COURR08_MF              ucg_font_courR08_mf
#define GLCD_FONT_COURR08_MR              ucg_font_courR08_mr
#define GLCD_FONT_COURR08_TF              ucg_font_courR08_tf
#define GLCD_FONT_COURR08_TR              ucg_font_courR08_tr
#define GLCD_FONT_COURR10_MF              ucg_font_courR10_mf
#define GLCD_FONT_COURR10_MR              ucg_font_courR10_mr
#define GLCD_FONT_COURR10_TF              ucg_font_courR10_tf
#define GLCD_FONT_COURR10_TR              ucg_font_courR10_tr
#define GLCD_FONT_COURR12_MF              ucg_font_courR12_mf
#define GLCD_FONT_COURR12_MR              ucg_font_courR12_mr
#define GLCD_FONT_COURR12_TF              ucg_font_courR12_tf
#define GLCD_FONT_COURR12_TR              ucg_font_courR12_tr
#define GLCD_FONT_COURR14_MF              ucg_font_courR14_mf
#define GLCD_FONT_COURR14_MR              ucg_font_courR14_mr
#define GLCD_FONT_COURR14_TF              ucg_font_courR14_tf
#define GLCD_FONT_COURR14_TR              ucg_font_courR14_tr
#define GLCD_FONT_COURR18_MF              ucg_font_courR18_mf
#define GLCD_FONT_COURR18_MR              ucg_font_courR18_mr
#define GLCD_FONT_COURR18_TF              ucg_font_courR18_tf
#define GLCD_FONT_COURR18_TR              ucg_font_courR18_tr
#define GLCD_FONT_COURR24_MF              ucg_font_courR24_mf
#define GLCD_FONT_COURR24_MN              ucg_font_courR24_mn
#define GLCD_FONT_COURR24_MR              ucg_font_courR24_mr
#define GLCD_FONT_COURR24_TF              ucg_font_courR24_tf
#define GLCD_FONT_COURR24_TN              ucg_font_courR24_tn
#define GLCD_FONT_COURR24_TR              ucg_font_courR24_tr
#define GLCD_FONT_CU12_67_75              ucg_font_cu12_67_75
#define GLCD_FONT_CU12_75                 ucg_font_cu12_75
#define GLCD_FONT_CU12_HF                 ucg_font_cu12_hf
#define GLCD_FONT_CU12_MF                 ucg_font_cu12_mf
#define GLCD_FONT_CU12_TF                 ucg_font_cu12_tf
#define GLCD_FONT_CURSOR_TF               ucg_font_cursor_tf
#define GLCD_FONT_CURSOR_TR               ucg_font_cursor_tr
#define GLCD_FONT_FIXED_V0_HF             ucg_font_fixed_v0_hf
#define GLCD_FONT_FIXED_V0_HN             ucg_font_fixed_v0_hn
#define GLCD_FONT_FIXED_V0_HR             ucg_font_fixed_v0_hr
#define GLCD_FONT_FIXED_V0_MR             ucg_font_fixed_v0_mr
#define GLCD_FONT_FIXED_V0_TF             ucg_font_fixed_v0_tf
#define GLCD_FONT_FIXED_V0_TN             ucg_font_fixed_v0_tn
#define GLCD_FONT_FIXED_V0_TR             ucg_font_fixed_v0_tr
#define GLCD_FONT_FREEDOOMR10_TR          ucg_font_freedoomr10_tr
#define GLCD_FONT_FREEDOOMR25_TN          ucg_font_freedoomr25_tn
#define GLCD_FONT_FUB11_HF                ucg_font_fub11_hf
#define GLCD_FONT_FUB11_HN                ucg_font_fub11_hn
#define GLCD_FONT_FUB11_HR                ucg_font_fub11_hr
#define GLCD_FONT_FUB11_TF                ucg_font_fub11_tf
#define GLCD_FONT_FUB11_TN                ucg_font_fub11_tn
#define GLCD_FONT_FUB11_TR                ucg_font_fub11_tr
#define GLCD_FONT_FUB14_HF                ucg_font_fub14_hf
#define GLCD_FONT_FUB14_HN                ucg_font_fub14_hn
#define GLCD_FONT_FUB14_HR                ucg_font_fub14_hr
#define GLCD_FONT_FUB14_TF                ucg_font_fub14_tf
#define GLCD_FONT_FUB14_TN                ucg_font_fub14_tn
#define GLCD_FONT_FUB14_TR                ucg_font_fub14_tr
#define GLCD_FONT_FUB17_HF                ucg_font_fub17_hf
#define GLCD_FONT_FUB17_HN                ucg_font_fub17_hn
#define GLCD_FONT_FUB17_HR                ucg_font_fub17_hr
#define GLCD_FONT_FUB17_TF                ucg_font_fub17_tf
#define GLCD_FONT_FUB17_TN                ucg_font_fub17_tn
#define GLCD_FONT_FUB17_TR                ucg_font_fub17_tr
#define GLCD_FONT_FUB20_HF                ucg_font_fub20_hf
#define GLCD_FONT_FUB20_HN                ucg_font_fub20_hn
#define GLCD_FONT_FUB20_HR                ucg_font_fub20_hr
#define GLCD_FONT_FUB20_TF                ucg_font_fub20_tf
#define GLCD_FONT_FUB20_TN                ucg_font_fub20_tn
#define GLCD_FONT_FUB20_TR                ucg_font_fub20_tr
#define GLCD_FONT_FUB25_HF                ucg_font_fub25_hf
#define GLCD_FONT_FUB25_HN                ucg_font_fub25_hn
#define GLCD_FONT_FUB25_HR                ucg_font_fub25_hr
#define GLCD_FONT_FUB25_TF                ucg_font_fub25_tf
#define GLCD_FONT_FUB25_TN                ucg_font_fub25_tn
#define GLCD_FONT_FUB25_TR                ucg_font_fub25_tr
#define GLCD_FONT_FUB30_HF                ucg_font_fub30_hf
#define GLCD_FONT_FUB30_HN                ucg_font_fub30_hn
#define GLCD_FONT_FUB30_HR                ucg_font_fub30_hr
#define GLCD_FONT_FUB30_TF                ucg_font_fub30_tf
#define GLCD_FONT_FUB30_TN                ucg_font_fub30_tn
#define GLCD_FONT_FUB30_TR                ucg_font_fub30_tr
#define GLCD_FONT_FUB35_HF                ucg_font_fub35_hf
#define GLCD_FONT_FUB35_HN                ucg_font_fub35_hn
#define GLCD_FONT_FUB35_HR                ucg_font_fub35_hr
#define GLCD_FONT_FUB35_TF                ucg_font_fub35_tf
#define GLCD_FONT_FUB35_TN                ucg_font_fub35_tn
#define GLCD_FONT_FUB35_TR                ucg_font_fub35_tr
#define GLCD_FONT_FUB42_HF                ucg_font_fub42_hf
#define GLCD_FONT_FUB42_HN                ucg_font_fub42_hn
#define GLCD_FONT_FUB42_HR                ucg_font_fub42_hr
#define GLCD_FONT_FUB42_TF                ucg_font_fub42_tf
#define GLCD_FONT_FUB42_TN                ucg_font_fub42_tn
#define GLCD_FONT_FUB42_TR                ucg_font_fub42_tr
#define GLCD_FONT_FUB49_HN                ucg_font_fub49_hn
#define GLCD_FONT_FUB49_TN                ucg_font_fub49_tn
#define GLCD_FONT_FUR11_HF                ucg_font_fur11_hf
#define GLCD_FONT_FUR11_HN                ucg_font_fur11_hn
#define GLCD_FONT_FUR11_HR                ucg_font_fur11_hr
#define GLCD_FONT_FUR11_TF                ucg_font_fur11_tf
#define GLCD_FONT_FUR11_TN                ucg_font_fur11_tn
#define GLCD_FONT_FUR11_TR                ucg_font_fur11_tr
#define GLCD_FONT_FUR14_HF                ucg_font_fur14_hf
#define GLCD_FONT_FUR14_HN                ucg_font_fur14_hn
#define GLCD_FONT_FUR14_HR                ucg_font_fur14_hr
#define GLCD_FONT_FUR14_TF                ucg_font_fur14_tf
#define GLCD_FONT_FUR14_TN                ucg_font_fur14_tn
#define GLCD_FONT_FUR14_TR                ucg_font_fur14_tr
#define GLCD_FONT_FUR17_HF                ucg_font_fur17_hf
#define GLCD_FONT_FUR17_HN                ucg_font_fur17_hn
#define GLCD_FONT_FUR17_HR                ucg_font_fur17_hr
#define GLCD_FONT_FUR17_TF                ucg_font_fur17_tf
#define GLCD_FONT_FUR17_TN                ucg_font_fur17_tn
#define GLCD_FONT_FUR17_TR                ucg_font_fur17_tr
#define GLCD_FONT_FUR20_HF                ucg_font_fur20_hf
#define GLCD_FONT_FUR20_HN                ucg_font_fur20_hn
#define GLCD_FONT_FUR20_HR                ucg_font_fur20_hr
#define GLCD_FONT_FUR20_TF                ucg_font_fur20_tf
#define GLCD_FONT_FUR20_TN                ucg_font_fur20_tn
#define GLCD_FONT_FUR20_TR                ucg_font_fur20_tr
#define GLCD_FONT_FUR25_HF                ucg_font_fur25_hf
#define GLCD_FONT_FUR25_HN                ucg_font_fur25_hn
#define GLCD_FONT_FUR25_HR                ucg_font_fur25_hr
#define GLCD_FONT_FUR25_TF                ucg_font_fur25_tf
#define GLCD_FONT_FUR25_TN                ucg_font_fur25_tn
#define GLCD_FONT_FUR25_TR                ucg_font_fur25_tr
#define GLCD_FONT_FUR30_HF                ucg_font_fur30_hf
#define GLCD_FONT_FUR30_HN                ucg_font_fur30_hn
#define GLCD_FONT_FUR30_HR                ucg_font_fur30_hr
#define GLCD_FONT_FUR30_TF                ucg_font_fur30_tf
#define GLCD_FONT_FUR30_TN                ucg_font_fur30_tn
#define GLCD_FONT_FUR30_TR                ucg_font_fur30_tr
#define GLCD_FONT_FUR35_HF                ucg_font_fur35_hf
#define GLCD_FONT_FUR35_HN                ucg_font_fur35_hn
#define GLCD_FONT_FUR35_HR                ucg_font_fur35_hr
#define GLCD_FONT_FUR35_TF                ucg_font_fur35_tf
#define GLCD_FONT_FUR35_TN                ucg_font_fur35_tn
#define GLCD_FONT_FUR35_TR                ucg_font_fur35_tr
#define GLCD_FONT_FUR42_HF                ucg_font_fur42_hf
#define GLCD_FONT_FUR42_HN                ucg_font_fur42_hn
#define GLCD_FONT_FUR42_HR                ucg_font_fur42_hr
#define GLCD_FONT_FUR42_TF                ucg_font_fur42_tf
#define GLCD_FONT_FUR42_TN                ucg_font_fur42_tn
#define GLCD_FONT_FUR42_TR                ucg_font_fur42_tr
#define GLCD_FONT_FUR49_HN                ucg_font_fur49_hn
#define GLCD_FONT_FUR49_TN                ucg_font_fur49_tn
#define GLCD_FONT_FUR49_TR                ucg_font_fur49_tr
#define GLCD_FONT_HELVB08_HF              ucg_font_helvB08_hf
#define GLCD_FONT_HELVB08_HR              ucg_font_helvB08_hr
#define GLCD_FONT_HELVB08_TF              ucg_font_helvB08_tf
#define GLCD_FONT_HELVB08_TR              ucg_font_helvB08_tr
#define GLCD_FONT_HELVB10_HF              ucg_font_helvB10_hf
#define GLCD_FONT_HELVB10_HR              ucg_font_helvB10_hr
#define GLCD_FONT_HELVB10_TF              ucg_font_helvB10_tf
#define GLCD_FONT_HELVB10_TR              ucg_font_helvB10_tr
#define GLCD_FONT_HELVB12_HF              ucg_font_helvB12_hf
#define GLCD_FONT_HELVB12_HR              ucg_font_helvB12_hr
#define GLCD_FONT_HELVB12_TF              ucg_font_helvB12_tf
#define GLCD_FONT_HELVB12_TR              ucg_font_helvB12_tr
#define GLCD_FONT_HELVB14_HF              ucg_font_helvB14_hf
#define GLCD_FONT_HELVB14_HR              ucg_font_helvB14_hr
#define GLCD_FONT_HELVB14_TF              ucg_font_helvB14_tf
#define GLCD_FONT_HELVB14_TR              ucg_font_helvB14_tr
#define GLCD_FONT_HELVB18_HF              ucg_font_helvB18_hf
#define GLCD_FONT_HELVB18_HR              ucg_font_helvB18_hr
#define GLCD_FONT_HELVB18_TF              ucg_font_helvB18_tf
#define GLCD_FONT_HELVB18_TR              ucg_font_helvB18_tr
#define GLCD_FONT_HELVB24_HF              ucg_font_helvB24_hf
#define GLCD_FONT_HELVB24_HN              ucg_font_helvB24_hn
#define GLCD_FONT_HELVB24_HR              ucg_font_helvB24_hr
#define GLCD_FONT_HELVB24_TF              ucg_font_helvB24_tf
#define GLCD_FONT_HELVB24_TN              ucg_font_helvB24_tn
#define GLCD_FONT_HELVB24_TR              ucg_font_helvB24_tr
#define GLCD_FONT_HELVR08_HF              ucg_font_helvR08_hf
#define GLCD_FONT_HELVR08_HR              ucg_font_helvR08_hr
#define GLCD_FONT_HELVR08_TF              ucg_font_helvR08_tf
#define GLCD_FONT_HELVR08_TR              ucg_font_helvR08_tr
#define GLCD_FONT_HELVR10_HF              ucg_font_helvR10_hf
#define GLCD_FONT_HELVR10_HR              ucg_font_helvR10_hr
#define GLCD_FONT_HELVR10_TF              ucg_font_helvR10_tf
#define GLCD_FONT_HELVR10_TR              ucg_font_helvR10_tr
#define GLCD_FONT_HELVR12_HF              ucg_font_helvR12_hf
#define GLCD_FONT_HELVR12_HR              ucg_font_helvR12_hr
#define GLCD_FONT_HELVR12_TF              ucg_font_helvR12_tf
#define GLCD_FONT_HELVR12_TR              ucg_font_helvR12_tr
#define GLCD_FONT_HELVR14_HF              ucg_font_helvR14_hf
#define GLCD_FONT_HELVR14_HR              ucg_font_helvR14_hr
#define GLCD_FONT_HELVR14_TF              ucg_font_helvR14_tf
#define GLCD_FONT_HELVR14_TR              ucg_font_helvR14_tr
#define GLCD_FONT_HELVR18_HF              ucg_font_helvR18_hf
#define GLCD_FONT_HELVR18_HR              ucg_font_helvR18_hr
#define GLCD_FONT_HELVR18_TF              ucg_font_helvR18_tf
#define GLCD_FONT_HELVR18_TR              ucg_font_helvR18_tr
#define GLCD_FONT_HELVR24_HF              ucg_font_helvR24_hf
#define GLCD_FONT_HELVR24_HN              ucg_font_helvR24_hn
#define GLCD_FONT_HELVR24_HR              ucg_font_helvR24_hr
#define GLCD_FONT_HELVR24_TF              ucg_font_helvR24_tf
#define GLCD_FONT_HELVR24_TN              ucg_font_helvR24_tn
#define GLCD_FONT_HELVR24_TR              ucg_font_helvR24_tr
#define GLCD_FONT_INB16_MF                ucg_font_inb16_mf
#define GLCD_FONT_INB16_MN                ucg_font_inb16_mn
#define GLCD_FONT_INB16_MR                ucg_font_inb16_mr
#define GLCD_FONT_INB16_TF                ucg_font_inb16_tf
#define GLCD_FONT_INB16_TN                ucg_font_inb16_tn
#define GLCD_FONT_INB16_TR                ucg_font_inb16_tr
#define GLCD_FONT_INB19_MF                ucg_font_inb19_mf
#define GLCD_FONT_INB19_MN                ucg_font_inb19_mn
#define GLCD_FONT_INB19_MR                ucg_font_inb19_mr
#define GLCD_FONT_INB19_TF                ucg_font_inb19_tf
#define GLCD_FONT_INB19_TN                ucg_font_inb19_tn
#define GLCD_FONT_INB19_TR                ucg_font_inb19_tr
#define GLCD_FONT_INB21_MF                ucg_font_inb21_mf
#define GLCD_FONT_INB21_MN                ucg_font_inb21_mn
#define GLCD_FONT_INB21_MR                ucg_font_inb21_mr
#define GLCD_FONT_INB21_TF                ucg_font_inb21_tf
#define GLCD_FONT_INB21_TN                ucg_font_inb21_tn
#define GLCD_FONT_INB21_TR                ucg_font_inb21_tr
#define GLCD_FONT_INB24_MF                ucg_font_inb24_mf
#define GLCD_FONT_INB24_MN                ucg_font_inb24_mn
#define GLCD_FONT_INB24_MR                ucg_font_inb24_mr
#define GLCD_FONT_INB24_TF                ucg_font_inb24_tf
#define GLCD_FONT_INB24_TN                ucg_font_inb24_tn
#define GLCD_FONT_INB24_TR                ucg_font_inb24_tr
#define GLCD_FONT_INB27_MF                ucg_font_inb27_mf
#define GLCD_FONT_INB27_MN                ucg_font_inb27_mn
#define GLCD_FONT_INB27_MR                ucg_font_inb27_mr
#define GLCD_FONT_INB27_TF                ucg_font_inb27_tf
#define GLCD_FONT_INB27_TN                ucg_font_inb27_tn
#define GLCD_FONT_INB27_TR                ucg_font_inb27_tr
#define GLCD_FONT_INB30_MF                ucg_font_inb30_mf
#define GLCD_FONT_INB30_MN                ucg_font_inb30_mn
#define GLCD_FONT_INB30_MR                ucg_font_inb30_mr
#define GLCD_FONT_INB30_TF                ucg_font_inb30_tf
#define GLCD_FONT_INB30_TN                ucg_font_inb30_tn
#define GLCD_FONT_INB30_TR                ucg_font_inb30_tr
#define GLCD_FONT_INB33_MF                ucg_font_inb33_mf
#define GLCD_FONT_INB33_MN                ucg_font_inb33_mn
#define GLCD_FONT_INB33_MR                ucg_font_inb33_mr
#define GLCD_FONT_INB33_TF                ucg_font_inb33_tf
#define GLCD_FONT_INB33_TN                ucg_font_inb33_tn
#define GLCD_FONT_INB33_TR                ucg_font_inb33_tr
#define GLCD_FONT_INB38_MF                ucg_font_inb38_mf
#define GLCD_FONT_INB38_MN                ucg_font_inb38_mn
#define GLCD_FONT_INB38_MR                ucg_font_inb38_mr
#define GLCD_FONT_INB38_TF                ucg_font_inb38_tf
#define GLCD_FONT_INB38_TN                ucg_font_inb38_tn
#define GLCD_FONT_INB38_TR                ucg_font_inb38_tr
#define GLCD_FONT_INB42_MF                ucg_font_inb42_mf
#define GLCD_FONT_INB42_MN                ucg_font_inb42_mn
#define GLCD_FONT_INB42_MR                ucg_font_inb42_mr
#define GLCD_FONT_INB42_TF                ucg_font_inb42_tf
#define GLCD_FONT_INB42_TN                ucg_font_inb42_tn
#define GLCD_FONT_INB42_TR                ucg_font_inb42_tr
#define GLCD_FONT_INB46_MF                ucg_font_inb46_mf
#define GLCD_FONT_INB46_MN                ucg_font_inb46_mn
#define GLCD_FONT_INB46_MR                ucg_font_inb46_mr
#define GLCD_FONT_INB46_TF                ucg_font_inb46_tf
#define GLCD_FONT_INB46_TN                ucg_font_inb46_tn
#define GLCD_FONT_INB46_TR                ucg_font_inb46_tr
#define GLCD_FONT_INB49_MF                ucg_font_inb49_mf
#define GLCD_FONT_INB49_MN                ucg_font_inb49_mn
#define GLCD_FONT_INB49_MR                ucg_font_inb49_mr
#define GLCD_FONT_INB49_TF                ucg_font_inb49_tf
#define GLCD_FONT_INB49_TN                ucg_font_inb49_tn
#define GLCD_FONT_INB49_TR                ucg_font_inb49_tr
#define GLCD_FONT_INB53_MF                ucg_font_inb53_mf
#define GLCD_FONT_INB53_MN                ucg_font_inb53_mn
#define GLCD_FONT_INB53_MR                ucg_font_inb53_mr
#define GLCD_FONT_INB53_TF                ucg_font_inb53_tf
#define GLCD_FONT_INB53_TN                ucg_font_inb53_tn
#define GLCD_FONT_INB53_TR                ucg_font_inb53_tr
#define GLCD_FONT_INB57_MF                ucg_font_inb57_mf
#define GLCD_FONT_INB57_MN                ucg_font_inb57_mn
#define GLCD_FONT_INB57_MR                ucg_font_inb57_mr
#define GLCD_FONT_INB57_TF                ucg_font_inb57_tf
#define GLCD_FONT_INB57_TN                ucg_font_inb57_tn
#define GLCD_FONT_INB57_TR                ucg_font_inb57_tr
#define GLCD_FONT_INB63_MN                ucg_font_inb63_mn
#define GLCD_FONT_INB63_TF                ucg_font_inb63_tf
#define GLCD_FONT_INB63_TN                ucg_font_inb63_tn
#define GLCD_FONT_INB63_TR                ucg_font_inb63_tr
#define GLCD_FONT_INR16_MF                ucg_font_inr16_mf
#define GLCD_FONT_INR16_MN                ucg_font_inr16_mn
#define GLCD_FONT_INR16_MR                ucg_font_inr16_mr
#define GLCD_FONT_INR16_TF                ucg_font_inr16_tf
#define GLCD_FONT_INR16_TN                ucg_font_inr16_tn
#define GLCD_FONT_INR16_TR                ucg_font_inr16_tr
#define GLCD_FONT_INR19_MF                ucg_font_inr19_mf
#define GLCD_FONT_INR19_MN                ucg_font_inr19_mn
#define GLCD_FONT_INR19_MR                ucg_font_inr19_mr
#define GLCD_FONT_INR19_TF                ucg_font_inr19_tf
#define GLCD_FONT_INR19_TN                ucg_font_inr19_tn
#define GLCD_FONT_INR19_TR                ucg_font_inr19_tr
#define GLCD_FONT_INR21_MF                ucg_font_inr21_mf
#define GLCD_FONT_INR21_MN                ucg_font_inr21_mn
#define GLCD_FONT_INR21_MR                ucg_font_inr21_mr
#define GLCD_FONT_INR21_TF                ucg_font_inr21_tf
#define GLCD_FONT_INR21_TN                ucg_font_inr21_tn
#define GLCD_FONT_INR21_TR                ucg_font_inr21_tr
#define GLCD_FONT_INR24_MF                ucg_font_inr24_mf
#define GLCD_FONT_INR24_MN                ucg_font_inr24_mn
#define GLCD_FONT_INR24_MR                ucg_font_inr24_mr
#define GLCD_FONT_INR24_TF                ucg_font_inr24_tf
#define GLCD_FONT_INR24_TN                ucg_font_inr24_tn
#define GLCD_FONT_INR24_TR                ucg_font_inr24_tr
#define GLCD_FONT_INR27_MF                ucg_font_inr27_mf
#define GLCD_FONT_INR27_MN                ucg_font_inr27_mn
#define GLCD_FONT_INR27_MR                ucg_font_inr27_mr
#define GLCD_FONT_INR27_TF                ucg_font_inr27_tf
#define GLCD_FONT_INR27_TN                ucg_font_inr27_tn
#define GLCD_FONT_INR27_TR                ucg_font_inr27_tr
#define GLCD_FONT_INR30_MF                ucg_font_inr30_mf
#define GLCD_FONT_INR30_MN                ucg_font_inr30_mn
#define GLCD_FONT_INR30_MR                ucg_font_inr30_mr
#define GLCD_FONT_INR30_TF                ucg_font_inr30_tf
#define GLCD_FONT_INR30_TN                ucg_font_inr30_tn
#define GLCD_FONT_INR30_TR                ucg_font_inr30_tr
#define GLCD_FONT_INR33_MF                ucg_font_inr33_mf
#define GLCD_FONT_INR33_MN                ucg_font_inr33_mn
#define GLCD_FONT_INR33_MR                ucg_font_inr33_mr
#define GLCD_FONT_INR33_TF                ucg_font_inr33_tf
#define GLCD_FONT_INR33_TN                ucg_font_inr33_tn
#define GLCD_FONT_INR33_TR                ucg_font_inr33_tr
#define GLCD_FONT_INR38_MF                ucg_font_inr38_mf
#define GLCD_FONT_INR38_MN                ucg_font_inr38_mn
#define GLCD_FONT_INR38_MR                ucg_font_inr38_mr
#define GLCD_FONT_INR38_TF                ucg_font_inr38_tf
#define GLCD_FONT_INR38_TN                ucg_font_inr38_tn
#define GLCD_FONT_INR38_TR                ucg_font_inr38_tr
#define GLCD_FONT_INR42_MF                ucg_font_inr42_mf
#define GLCD_FONT_INR42_MN                ucg_font_inr42_mn
#define GLCD_FONT_INR42_MR                ucg_font_inr42_mr
#define GLCD_FONT_INR42_TF                ucg_font_inr42_tf
#define GLCD_FONT_INR42_TN                ucg_font_inr42_tn
#define GLCD_FONT_INR42_TR                ucg_font_inr42_tr
#define GLCD_FONT_INR46_MF                ucg_font_inr46_mf
#define GLCD_FONT_INR46_MN                ucg_font_inr46_mn
#define GLCD_FONT_INR46_MR                ucg_font_inr46_mr
#define GLCD_FONT_INR46_TF                ucg_font_inr46_tf
#define GLCD_FONT_INR46_TN                ucg_font_inr46_tn
#define GLCD_FONT_INR46_TR                ucg_font_inr46_tr
#define GLCD_FONT_INR49_MF                ucg_font_inr49_mf
#define GLCD_FONT_INR49_MN                ucg_font_inr49_mn
#define GLCD_FONT_INR49_MR                ucg_font_inr49_mr
#define GLCD_FONT_INR49_TF                ucg_font_inr49_tf
#define GLCD_FONT_INR49_TN                ucg_font_inr49_tn
#define GLCD_FONT_INR49_TR                ucg_font_inr49_tr
#define GLCD_FONT_INR53_MF                ucg_font_inr53_mf
#define GLCD_FONT_INR53_MN                ucg_font_inr53_mn
#define GLCD_FONT_INR53_MR                ucg_font_inr53_mr
#define GLCD_FONT_INR53_TF                ucg_font_inr53_tf
#define GLCD_FONT_INR53_TN                ucg_font_inr53_tn
#define GLCD_FONT_INR53_TR                ucg_font_inr53_tr
#define GLCD_FONT_INR57_MN                ucg_font_inr57_mn
#define GLCD_FONT_INR57_TF                ucg_font_inr57_tf
#define GLCD_FONT_INR57_TN                ucg_font_inr57_tn
#define GLCD_FONT_INR57_TR                ucg_font_inr57_tr
#define GLCD_FONT_INR62_MN                ucg_font_inr62_mn
#define GLCD_FONT_INR62_TN                ucg_font_inr62_tn
#define GLCD_FONT_INR62_TR                ucg_font_inr62_tr
#define GLCD_FONT_LOGISOSO16_HF           ucg_font_logisoso16_hf
#define GLCD_FONT_LOGISOSO16_HN           ucg_font_logisoso16_hn
#define GLCD_FONT_LOGISOSO16_HR           ucg_font_logisoso16_hr
#define GLCD_FONT_LOGISOSO16_TF           ucg_font_logisoso16_tf
#define GLCD_FONT_LOGISOSO16_TN           ucg_font_logisoso16_tn
#define GLCD_FONT_LOGISOSO16_TR           ucg_font_logisoso16_tr
#define GLCD_FONT_LOGISOSO18_HF           ucg_font_logisoso18_hf
#define GLCD_FONT_LOGISOSO18_HN           ucg_font_logisoso18_hn
#define GLCD_FONT_LOGISOSO18_HR           ucg_font_logisoso18_hr
#define GLCD_FONT_LOGISOSO18_TF           ucg_font_logisoso18_tf
#define GLCD_FONT_LOGISOSO18_TN           ucg_font_logisoso18_tn
#define GLCD_FONT_LOGISOSO18_TR           ucg_font_logisoso18_tr
#define GLCD_FONT_LOGISOSO20_HF           ucg_font_logisoso20_hf
#define GLCD_FONT_LOGISOSO20_HN           ucg_font_logisoso20_hn
#define GLCD_FONT_LOGISOSO20_HR           ucg_font_logisoso20_hr
#define GLCD_FONT_LOGISOSO20_TF           ucg_font_logisoso20_tf
#define GLCD_FONT_LOGISOSO20_TN           ucg_font_logisoso20_tn
#define GLCD_FONT_LOGISOSO20_TR           ucg_font_logisoso20_tr
#define GLCD_FONT_LOGISOSO22_HF           ucg_font_logisoso22_hf
#define GLCD_FONT_LOGISOSO22_HN           ucg_font_logisoso22_hn
#define GLCD_FONT_LOGISOSO22_HR           ucg_font_logisoso22_hr
#define GLCD_FONT_LOGISOSO22_TF           ucg_font_logisoso22_tf
#define GLCD_FONT_LOGISOSO22_TN           ucg_font_logisoso22_tn
#define GLCD_FONT_LOGISOSO22_TR           ucg_font_logisoso22_tr
#define GLCD_FONT_LOGISOSO24_HF           ucg_font_logisoso24_hf
#define GLCD_FONT_LOGISOSO24_HN           ucg_font_logisoso24_hn
#define GLCD_FONT_LOGISOSO24_HR           ucg_font_logisoso24_hr
#define GLCD_FONT_LOGISOSO24_TF           ucg_font_logisoso24_tf
#define GLCD_FONT_LOGISOSO24_TN           ucg_font_logisoso24_tn
#define GLCD_FONT_LOGISOSO24_TR           ucg_font_logisoso24_tr
#define GLCD_FONT_LOGISOSO26_HF           ucg_font_logisoso26_hf
#define GLCD_FONT_LOGISOSO26_HN           ucg_font_logisoso26_hn
#define GLCD_FONT_LOGISOSO26_HR           ucg_font_logisoso26_hr
#define GLCD_FONT_LOGISOSO26_TF           ucg_font_logisoso26_tf
#define GLCD_FONT_LOGISOSO26_TN           ucg_font_logisoso26_tn
#define GLCD_FONT_LOGISOSO26_TR           ucg_font_logisoso26_tr
#define GLCD_FONT_LOGISOSO28_HF           ucg_font_logisoso28_hf
#define GLCD_FONT_LOGISOSO28_HN           ucg_font_logisoso28_hn
#define GLCD_FONT_LOGISOSO28_HR           ucg_font_logisoso28_hr
#define GLCD_FONT_LOGISOSO28_TF           ucg_font_logisoso28_tf
#define GLCD_FONT_LOGISOSO28_TN           ucg_font_logisoso28_tn
#define GLCD_FONT_LOGISOSO28_TR           ucg_font_logisoso28_tr
#define GLCD_FONT_LOGISOSO30_TF           ucg_font_logisoso30_tf
#define GLCD_FONT_LOGISOSO30_TN           ucg_font_logisoso30_tn
#define GLCD_FONT_LOGISOSO30_TR           ucg_font_logisoso30_tr
#define GLCD_FONT_LOGISOSO32_TF           ucg_font_logisoso32_tf
#define GLCD_FONT_LOGISOSO32_TN           ucg_font_logisoso32_tn
#define GLCD_FONT_LOGISOSO32_TR           ucg_font_logisoso32_tr
#define GLCD_FONT_LOGISOSO34_TF           ucg_font_logisoso34_tf
#define GLCD_FONT_LOGISOSO34_TN           ucg_font_logisoso34_tn
#define GLCD_FONT_LOGISOSO34_TR           ucg_font_logisoso34_tr
#define GLCD_FONT_LOGISOSO38_TF           ucg_font_logisoso38_tf
#define GLCD_FONT_LOGISOSO38_TN           ucg_font_logisoso38_tn
#define GLCD_FONT_LOGISOSO38_TR           ucg_font_logisoso38_tr
#define GLCD_FONT_LOGISOSO42_TF           ucg_font_logisoso42_tf
#define GLCD_FONT_LOGISOSO42_TN           ucg_font_logisoso42_tn
#define GLCD_FONT_LOGISOSO42_TR           ucg_font_logisoso42_tr
#define GLCD_FONT_LOGISOSO46_TF           ucg_font_logisoso46_tf
#define GLCD_FONT_LOGISOSO46_TN           ucg_font_logisoso46_tn
#define GLCD_FONT_LOGISOSO46_TR           ucg_font_logisoso46_tr
#define GLCD_FONT_LOGISOSO50_TF           ucg_font_logisoso50_tf
#define GLCD_FONT_LOGISOSO50_TN           ucg_font_logisoso50_tn
#define GLCD_FONT_LOGISOSO50_TR           ucg_font_logisoso50_tr
#define GLCD_FONT_LOGISOSO54_TF           ucg_font_logisoso54_tf
#define GLCD_FONT_LOGISOSO54_TN           ucg_font_logisoso54_tn
#define GLCD_FONT_LOGISOSO54_TR           ucg_font_logisoso54_tr
#define GLCD_FONT_LOGISOSO58_TF           ucg_font_logisoso58_tf
#define GLCD_FONT_LOGISOSO58_TN           ucg_font_logisoso58_tn
#define GLCD_FONT_LOGISOSO58_TR           ucg_font_logisoso58_tr
#define GLCD_FONT_LOGISOSO62_TN           ucg_font_logisoso62_tn
#define GLCD_FONT_LUCASFONT_ALTERNATE_HF  ucg_font_lucasfont_alternate_hf
#define GLCD_FONT_LUCASFONT_ALTERNATE_HN  ucg_font_lucasfont_alternate_hn
#define GLCD_FONT_LUCASFONT_ALTERNATE_HR  ucg_font_lucasfont_alternate_hr
#define GLCD_FONT_LUCASFONT_ALTERNATE_TF  ucg_font_lucasfont_alternate_tf
#define GLCD_FONT_LUCASFONT_ALTERNATE_TN  ucg_font_lucasfont_alternate_tn
#define GLCD_FONT_LUCASFONT_ALTERNATE_TR  ucg_font_lucasfont_alternate_tr
#define GLCD_FONT_M2ICON_5                ucg_font_m2icon_5
#define GLCD_FONT_M2ICON_7                ucg_font_m2icon_7
#define GLCD_FONT_M2ICON_9                ucg_font_m2icon_9
#define GLCD_FONT_MICRO_MF                ucg_font_micro_mf
#define GLCD_FONT_MICRO_TF                ucg_font_micro_tf
#define GLCD_FONT_NCENB08_HF              ucg_font_ncenB08_hf
#define GLCD_FONT_NCENB08_HR              ucg_font_ncenB08_hr
#define GLCD_FONT_NCENB08_TF              ucg_font_ncenB08_tf
#define GLCD_FONT_NCENB08_TR              ucg_font_ncenB08_tr
#define GLCD_FONT_NCENB10_HF              ucg_font_ncenB10_hf
#define GLCD_FONT_NCENB10_HR              ucg_font_ncenB10_hr
#define GLCD_FONT_NCENB10_TF              ucg_font_ncenB10_tf
#define GLCD_FONT_NCENB10_TR              ucg_font_ncenB10_tr
#define GLCD_FONT_NCENB12_HF              ucg_font_ncenB12_hf
#define GLCD_FONT_NCENB12_HR              ucg_font_ncenB12_hr
#define GLCD_FONT_NCENB12_TF              ucg_font_ncenB12_tf
#define GLCD_FONT_NCENB12_TR              ucg_font_ncenB12_tr
#define GLCD_FONT_NCENB14_HF              ucg_font_ncenB14_hf
#define GLCD_FONT_NCENB14_HR              ucg_font_ncenB14_hr
#define GLCD_FONT_NCENB14_TF              ucg_font_ncenB14_tf
#define GLCD_FONT_NCENB14_TR              ucg_font_ncenB14_tr
#define GLCD_FONT_NCENB18_HF              ucg_font_ncenB18_hf
#define GLCD_FONT_NCENB18_HR              ucg_font_ncenB18_hr
#define GLCD_FONT_NCENB18_TF              ucg_font_ncenB18_tf
#define GLCD_FONT_NCENB18_TR              ucg_font_ncenB18_tr
#define GLCD_FONT_NCENB24_HF              ucg_font_ncenB24_hf
#define GLCD_FONT_NCENB24_HN              ucg_font_ncenB24_hn
#define GLCD_FONT_NCENB24_HR              ucg_font_ncenB24_hr
#define GLCD_FONT_NCENB24_TF              ucg_font_ncenB24_tf
#define GLCD_FONT_NCENB24_TN              ucg_font_ncenB24_tn
#define GLCD_FONT_NCENB24_TR              ucg_font_ncenB24_tr
#define GLCD_FONT_NCENR08_HF              ucg_font_ncenR08_hf
#define GLCD_FONT_NCENR08_HR              ucg_font_ncenR08_hr
#define GLCD_FONT_NCENR08_TF              ucg_font_ncenR08_tf
#define GLCD_FONT_NCENR08_TR              ucg_font_ncenR08_tr
#define GLCD_FONT_NCENR10_HF              ucg_font_ncenR10_hf
#define GLCD_FONT_NCENR10_HR              ucg_font_ncenR10_hr
#define GLCD_FONT_NCENR10_TF              ucg_font_ncenR10_tf
#define GLCD_FONT_NCENR10_TR              ucg_font_ncenR10_tr
#define GLCD_FONT_NCENR12_HF              ucg_font_ncenR12_hf
#define GLCD_FONT_NCENR12_HR              ucg_font_ncenR12_hr
#define GLCD_FONT_NCENR12_TF              ucg_font_ncenR12_tf
#define GLCD_FONT_NCENR12_TR              ucg_font_ncenR12_tr
#define GLCD_FONT_NCENR14_HF              ucg_font_ncenR14_hf
#define GLCD_FONT_NCENR14_HR              ucg_font_ncenR14_hr
#define GLCD_FONT_NCENR14_TF              ucg_font_ncenR14_tf
#define GLCD_FONT_NCENR14_TR              ucg_font_ncenR14_tr
#define GLCD_FONT_NCENR18_HF              ucg_font_ncenR18_hf
#define GLCD_FONT_NCENR18_HR              ucg_font_ncenR18_hr
#define GLCD_FONT_NCENR18_TF              ucg_font_ncenR18_tf
#define GLCD_FONT_NCENR18_TR              ucg_font_ncenR18_tr
#define GLCD_FONT_NCENR24_HF              ucg_font_ncenR24_hf
#define GLCD_FONT_NCENR24_HN              ucg_font_ncenR24_hn
#define GLCD_FONT_NCENR24_HR              ucg_font_ncenR24_hr
#define GLCD_FONT_NCENR24_TF              ucg_font_ncenR24_tf
#define GLCD_FONT_NCENR24_TN              ucg_font_ncenR24_tn
#define GLCD_FONT_NCENR24_TR              ucg_font_ncenR24_tr
#define GLCD_FONT_ORGV01_HF               ucg_font_orgv01_hf
#define GLCD_FONT_ORGV01_HN               ucg_font_orgv01_hn
#define GLCD_FONT_ORGV01_HR               ucg_font_orgv01_hr
#define GLCD_FONT_ORGV01_TF               ucg_font_orgv01_tf
#define GLCD_FONT_ORGV01_TN               ucg_font_orgv01_tn
#define GLCD_FONT_ORGV01_TR               ucg_font_orgv01_tr
#define GLCD_FONT_OSB18_HF                ucg_font_osb18_hf
#define GLCD_FONT_OSB18_HN                ucg_font_osb18_hn
#define GLCD_FONT_OSB18_HR                ucg_font_osb18_hr
#define GLCD_FONT_OSB18_TF                ucg_font_osb18_tf
#define GLCD_FONT_OSB18_TN                ucg_font_osb18_tn
#define GLCD_FONT_OSB18_TR                ucg_font_osb18_tr
#define GLCD_FONT_OSB21_HF                ucg_font_osb21_hf
#define GLCD_FONT_OSB21_HN                ucg_font_osb21_hn
#define GLCD_FONT_OSB21_HR                ucg_font_osb21_hr
#define GLCD_FONT_OSB21_TF                ucg_font_osb21_tf
#define GLCD_FONT_OSB21_TN                ucg_font_osb21_tn
#define GLCD_FONT_OSB21_TR                ucg_font_osb21_tr
#define GLCD_FONT_OSB26_HF                ucg_font_osb26_hf
#define GLCD_FONT_OSB26_HN                ucg_font_osb26_hn
#define GLCD_FONT_OSB26_HR                ucg_font_osb26_hr
#define GLCD_FONT_OSB26_TF                ucg_font_osb26_tf
#define GLCD_FONT_OSB26_TN                ucg_font_osb26_tn
#define GLCD_FONT_OSB26_TR                ucg_font_osb26_tr
#define GLCD_FONT_OSB29_HF                ucg_font_osb29_hf
#define GLCD_FONT_OSB29_HN                ucg_font_osb29_hn
#define GLCD_FONT_OSB29_HR                ucg_font_osb29_hr
#define GLCD_FONT_OSB29_TF                ucg_font_osb29_tf
#define GLCD_FONT_OSB29_TN                ucg_font_osb29_tn
#define GLCD_FONT_OSB29_TR                ucg_font_osb29_tr
#define GLCD_FONT_OSB35_HF                ucg_font_osb35_hf
#define GLCD_FONT_OSB35_HN                ucg_font_osb35_hn
#define GLCD_FONT_OSB35_HR                ucg_font_osb35_hr
#define GLCD_FONT_OSB35_TF                ucg_font_osb35_tf
#define GLCD_FONT_OSB35_TN                ucg_font_osb35_tn
#define GLCD_FONT_OSB35_TR                ucg_font_osb35_tr
#define GLCD_FONT_OSB41_HF                ucg_font_osb41_hf
#define GLCD_FONT_OSB41_HN                ucg_font_osb41_hn
#define GLCD_FONT_OSB41_HR                ucg_font_osb41_hr
#define GLCD_FONT_OSB41_TF                ucg_font_osb41_tf
#define GLCD_FONT_OSB41_TN                ucg_font_osb41_tn
#define GLCD_FONT_OSB41_TR                ucg_font_osb41_tr
#define GLCD_FONT_OSR18_HF                ucg_font_osr18_hf
#define GLCD_FONT_OSR18_HN                ucg_font_osr18_hn
#define GLCD_FONT_OSR18_HR                ucg_font_osr18_hr
#define GLCD_FONT_OSR18_TF                ucg_font_osr18_tf
#define GLCD_FONT_OSR18_TN                ucg_font_osr18_tn
#define GLCD_FONT_OSR18_TR                ucg_font_osr18_tr
#define GLCD_FONT_OSR21_HF                ucg_font_osr21_hf
#define GLCD_FONT_OSR21_HN                ucg_font_osr21_hn
#define GLCD_FONT_OSR21_HR                ucg_font_osr21_hr
#define GLCD_FONT_OSR21_TF                ucg_font_osr21_tf
#define GLCD_FONT_OSR21_TN                ucg_font_osr21_tn
#define GLCD_FONT_OSR21_TR                ucg_font_osr21_tr
#define GLCD_FONT_OSR26_HF                ucg_font_osr26_hf
#define GLCD_FONT_OSR26_HN                ucg_font_osr26_hn
#define GLCD_FONT_OSR26_HR                ucg_font_osr26_hr
#define GLCD_FONT_OSR26_TF                ucg_font_osr26_tf
#define GLCD_FONT_OSR26_TN                ucg_font_osr26_tn
#define GLCD_FONT_OSR26_TR                ucg_font_osr26_tr
#define GLCD_FONT_OSR29_HF                ucg_font_osr29_hf
#define GLCD_FONT_OSR29_HN                ucg_font_osr29_hn
#define GLCD_FONT_OSR29_HR                ucg_font_osr29_hr
#define GLCD_FONT_OSR29_TF                ucg_font_osr29_tf
#define GLCD_FONT_OSR29_TN                ucg_font_osr29_tn
#define GLCD_FONT_OSR29_TR                ucg_font_osr29_tr
#define GLCD_FONT_OSR35_HF                ucg_font_osr35_hf
#define GLCD_FONT_OSR35_HN                ucg_font_osr35_hn
#define GLCD_FONT_OSR35_HR                ucg_font_osr35_hr
#define GLCD_FONT_OSR35_TF                ucg_font_osr35_tf
#define GLCD_FONT_OSR35_TN                ucg_font_osr35_tn
#define GLCD_FONT_OSR35_TR                ucg_font_osr35_tr
#define GLCD_FONT_OSR41_HF                ucg_font_osr41_hf
#define GLCD_FONT_OSR41_HN                ucg_font_osr41_hn
#define GLCD_FONT_OSR41_HR                ucg_font_osr41_hr
#define GLCD_FONT_OSR41_TF                ucg_font_osr41_tf
#define GLCD_FONT_OSR41_TN                ucg_font_osr41_tn
#define GLCD_FONT_OSR41_TR                ucg_font_osr41_tr
#define GLCD_FONT_P01TYPE_HF              ucg_font_p01type_hf
#define GLCD_FONT_P01TYPE_HN              ucg_font_p01type_hn
#define GLCD_FONT_P01TYPE_HR              ucg_font_p01type_hr
#define GLCD_FONT_P01TYPE_TF              ucg_font_p01type_tf
#define GLCD_FONT_P01TYPE_TN              ucg_font_p01type_tn
#define GLCD_FONT_P01TYPE_TR              ucg_font_p01type_tr
#define GLCD_FONT_PIXELLE_MICRO_HF        ucg_font_pixelle_micro_hf
#define GLCD_FONT_PIXELLE_MICRO_HN        ucg_font_pixelle_micro_hn
#define GLCD_FONT_PIXELLE_MICRO_HR        ucg_font_pixelle_micro_hr
#define GLCD_FONT_PIXELLE_MICRO_TF        ucg_font_pixelle_micro_tf
#define GLCD_FONT_PIXELLE_MICRO_TN        ucg_font_pixelle_micro_tn
#define GLCD_FONT_PIXELLE_MICRO_TR        ucg_font_pixelle_micro_tr
#define GLCD_FONT_PROFONT10_8F            ucg_font_profont10_8f
#define GLCD_FONT_PROFONT10_8R            ucg_font_profont10_8r
#define GLCD_FONT_PROFONT10_MF            ucg_font_profont10_mf
#define GLCD_FONT_PROFONT10_MR            ucg_font_profont10_mr
#define GLCD_FONT_PROFONT11_8F            ucg_font_profont11_8f
#define GLCD_FONT_PROFONT11_8R            ucg_font_profont11_8r
#define GLCD_FONT_PROFONT11_MF            ucg_font_profont11_mf
#define GLCD_FONT_PROFONT11_MR            ucg_font_profont11_mr
#define GLCD_FONT_PROFONT12_8F            ucg_font_profont12_8f
#define GLCD_FONT_PROFONT12_8R            ucg_font_profont12_8r
#define GLCD_FONT_PROFONT12_MF            ucg_font_profont12_mf
#define GLCD_FONT_PROFONT12_MR            ucg_font_profont12_mr
#define GLCD_FONT_PROFONT15_8F            ucg_font_profont15_8f
#define GLCD_FONT_PROFONT15_8R            ucg_font_profont15_8r
#define GLCD_FONT_PROFONT15_MF            ucg_font_profont15_mf
#define GLCD_FONT_PROFONT15_MR            ucg_font_profont15_mr
#define GLCD_FONT_PROFONT17_8F            ucg_font_profont17_8f
#define GLCD_FONT_PROFONT17_8R            ucg_font_profont17_8r
#define GLCD_FONT_PROFONT17_MF            ucg_font_profont17_mf
#define GLCD_FONT_PROFONT17_MR            ucg_font_profont17_mr
#define GLCD_FONT_PROFONT22_8F            ucg_font_profont22_8f
#define GLCD_FONT_PROFONT22_8N            ucg_font_profont22_8n
#define GLCD_FONT_PROFONT22_8R            ucg_font_profont22_8r
#define GLCD_FONT_PROFONT22_MF            ucg_font_profont22_mf
#define GLCD_FONT_PROFONT22_MN            ucg_font_profont22_mn
#define GLCD_FONT_PROFONT22_MR            ucg_font_profont22_mr
#define GLCD_FONT_PROFONT29_8F            ucg_font_profont29_8f
#define GLCD_FONT_PROFONT29_8N            ucg_font_profont29_8n
#define GLCD_FONT_PROFONT29_8R            ucg_font_profont29_8r
#define GLCD_FONT_PROFONT29_MF            ucg_font_profont29_mf
#define GLCD_FONT_PROFONT29_MN            ucg_font_profont29_mn
#define GLCD_FONT_PROFONT29_MR            ucg_font_profont29_mr
#define GLCD_FONT_ROBOT_DE_NIRO_HF        ucg_font_robot_de_niro_hf
#define GLCD_FONT_ROBOT_DE_NIRO_HN        ucg_font_robot_de_niro_hn
#define GLCD_FONT_ROBOT_DE_NIRO_HR        ucg_font_robot_de_niro_hr
#define GLCD_FONT_ROBOT_DE_NIRO_TF        ucg_font_robot_de_niro_tf
#define GLCD_FONT_ROBOT_DE_NIRO_TN        ucg_font_robot_de_niro_tn
#define GLCD_FONT_ROBOT_DE_NIRO_TR        ucg_font_robot_de_niro_tr
#define GLCD_FONT_SYMB08_TF               ucg_font_symb08_tf
#define GLCD_FONT_SYMB08_TR               ucg_font_symb08_tr
#define GLCD_FONT_SYMB10_TF               ucg_font_symb10_tf
#define GLCD_FONT_SYMB10_TR               ucg_font_symb10_tr
#define GLCD_FONT_SYMB12_TF               ucg_font_symb12_tf
#define GLCD_FONT_SYMB12_TR               ucg_font_symb12_tr
#define GLCD_FONT_SYMB14_TF               ucg_font_symb14_tf
#define GLCD_FONT_SYMB14_TR               ucg_font_symb14_tr
#define GLCD_FONT_SYMB18_TF               ucg_font_symb18_tf
#define GLCD_FONT_SYMB18_TR               ucg_font_symb18_tr
#define GLCD_FONT_SYMB24_TF               ucg_font_symb24_tf
#define GLCD_FONT_SYMB24_TR               ucg_font_symb24_tr
#define GLCD_FONT_TIMB08_HF               ucg_font_timB08_hf
#define GLCD_FONT_TIMB08_HR               ucg_font_timB08_hr
#define GLCD_FONT_TIMB08_TF               ucg_font_timB08_tf
#define GLCD_FONT_TIMB08_TR               ucg_font_timB08_tr
#define GLCD_FONT_TIMB10_HF               ucg_font_timB10_hf
#define GLCD_FONT_TIMB10_HR               ucg_font_timB10_hr
#define GLCD_FONT_TIMB10_TF               ucg_font_timB10_tf
#define GLCD_FONT_TIMB10_TR               ucg_font_timB10_tr
#define GLCD_FONT_TIMB12_HF               ucg_font_timB12_hf
#define GLCD_FONT_TIMB12_HR               ucg_font_timB12_hr
#define GLCD_FONT_TIMB12_TF               ucg_font_timB12_tf
#define GLCD_FONT_TIMB12_TR               ucg_font_timB12_tr
#define GLCD_FONT_TIMB14_HF               ucg_font_timB14_hf
#define GLCD_FONT_TIMB14_HR               ucg_font_timB14_hr
#define GLCD_FONT_TIMB14_TF               ucg_font_timB14_tf
#define GLCD_FONT_TIMB14_TR               ucg_font_timB14_tr
#define GLCD_FONT_TIMB18_HF               ucg_font_timB18_hf
#define GLCD_FONT_TIMB18_HR               ucg_font_timB18_hr
#define GLCD_FONT_TIMB18_TF               ucg_font_timB18_tf
#define GLCD_FONT_TIMB18_TR               ucg_font_timB18_tr
#define GLCD_FONT_TIMB24_HF               ucg_font_timB24_hf
#define GLCD_FONT_TIMB24_HN               ucg_font_timB24_hn
#define GLCD_FONT_TIMB24_HR               ucg_font_timB24_hr
#define GLCD_FONT_TIMB24_TF               ucg_font_timB24_tf
#define GLCD_FONT_TIMB24_TN               ucg_font_timB24_tn
#define GLCD_FONT_TIMB24_TR               ucg_font_timB24_tr
#define GLCD_FONT_TIMR08_HF               ucg_font_timR08_hf
#define GLCD_FONT_TIMR08_HR               ucg_font_timR08_hr
#define GLCD_FONT_TIMR08_TF               ucg_font_timR08_tf
#define GLCD_FONT_TIMR08_TR               ucg_font_timR08_tr
#define GLCD_FONT_TIMR10_HF               ucg_font_timR10_hf
#define GLCD_FONT_TIMR10_HR               ucg_font_timR10_hr
#define GLCD_FONT_TIMR10_TF               ucg_font_timR10_tf
#define GLCD_FONT_TIMR10_TR               ucg_font_timR10_tr
#define GLCD_FONT_TIMR12_HF               ucg_font_timR12_hf
#define GLCD_FONT_TIMR12_HR               ucg_font_timR12_hr
#define GLCD_FONT_TIMR12_TF               ucg_font_timR12_tf
#define GLCD_FONT_TIMR12_TR               ucg_font_timR12_tr
#define GLCD_FONT_TIMR14_HF               ucg_font_timR14_hf
#define GLCD_FONT_TIMR14_HR               ucg_font_timR14_hr
#define GLCD_FONT_TIMR14_TF               ucg_font_timR14_tf
#define GLCD_FONT_TIMR14_TR               ucg_font_timR14_tr
#define GLCD_FONT_TIMR18_HF               ucg_font_timR18_hf
#define GLCD_FONT_TIMR18_HR               ucg_font_timR18_hr
#define GLCD_FONT_TIMR18_TF               ucg_font_timR18_tf
#define GLCD_FONT_TIMR18_TR               ucg_font_timR18_tr
#define GLCD_FONT_TIMR24_HF               ucg_font_timR24_hf
#define GLCD_FONT_TIMR24_HN               ucg_font_timR24_hn
#define GLCD_FONT_TIMR24_HR               ucg_font_timR24_hr
#define GLCD_FONT_TIMR24_TF               ucg_font_timR24_tf
#define GLCD_FONT_TIMR24_TN               ucg_font_timR24_tn
#define GLCD_FONT_TIMR24_TR               ucg_font_timR24_tr
#define GLCD_FONT_TPSSB_HF                ucg_font_tpssb_hf
#define GLCD_FONT_TPSSB_HN                ucg_font_tpssb_hn
#define GLCD_FONT_TPSSB_HR                ucg_font_tpssb_hr
#define GLCD_FONT_TPSSB_TF                ucg_font_tpssb_tf
#define GLCD_FONT_TPSSB_TN                ucg_font_tpssb_tn
#define GLCD_FONT_TPSSB_TR                ucg_font_tpssb_tr
#define GLCD_FONT_TPSS_HF                 ucg_font_tpss_hf
#define GLCD_FONT_TPSS_HN                 ucg_font_tpss_hn
#define GLCD_FONT_TPSS_HR                 ucg_font_tpss_hr
#define GLCD_FONT_TPSS_TF                 ucg_font_tpss_tf
#define GLCD_FONT_TPSS_TN                 ucg_font_tpss_tn
#define GLCD_FONT_TPSS_TR                 ucg_font_tpss_tr
#define GLCD_FONT_TRIXEL_SQUARE_HF        ucg_font_trixel_square_hf
#define GLCD_FONT_TRIXEL_SQUARE_HN        ucg_font_trixel_square_hn
#define GLCD_FONT_TRIXEL_SQUARE_HR        ucg_font_trixel_square_hr
#define GLCD_FONT_TRIXEL_SQUARE_TF        ucg_font_trixel_square_tf
#define GLCD_FONT_TRIXEL_SQUARE_TN        ucg_font_trixel_square_tn
#define GLCD_FONT_TRIXEL_SQUARE_TR        ucg_font_trixel_square_tr
#define GLCD_FONT_U8GLIB_4_HF             ucg_font_u8glib_4_hf
#define GLCD_FONT_U8GLIB_4_HR             ucg_font_u8glib_4_hr
#define GLCD_FONT_U8GLIB_4_TF             ucg_font_u8glib_4_tf
#define GLCD_FONT_U8GLIB_4_TR             ucg_font_u8glib_4_tr
#define GLCD_FONT_UNIFONT_0_8             ucg_font_unifont_0_8
#define GLCD_FONT_UNIFONT_12_13           ucg_font_unifont_12_13
#define GLCD_FONT_UNIFONT_18_19           ucg_font_unifont_18_19
#define GLCD_FONT_UNIFONT_2_3             ucg_font_unifont_2_3
#define GLCD_FONT_UNIFONT_4_5             ucg_font_unifont_4_5
#define GLCD_FONT_UNIFONT_67_75           ucg_font_unifont_67_75
#define GLCD_FONT_UNIFONT_72_73           ucg_font_unifont_72_73
#define GLCD_FONT_UNIFONT_78_79           ucg_font_unifont_78_79
#define GLCD_FONT_UNIFONT_8_9             ucg_font_unifont_8_9
#define GLCD_FONT_UNIFONT_MF              ucg_font_unifont_mf
#define GLCD_FONT_UNIFONT_MR              ucg_font_unifont_mr
#define GLCD_FONT_UNIFONT_TF              ucg_font_unifont_tf
#define GLCD_FONT_UNIFONT_TR              ucg_font_unifont_tr
#define glcd_set_font(font)               ucg_SetFont(&glcd, font)

#define GLCD_FONT_MODE_TRANSPARENT        UCG_FONT_MODE_TRANSPARENT
#define GLCD_FONT_MODE_SOLID              UCG_FONT_MODE_SOLID
#define glcd_set_font_mode(mode)          ucg_SetFontMode(&glcd, mode)

#define glcd_get_glyph_width(...)         ucg_GetGlyphWidth(&glcd, __VA_ARGS__)
#define glcd_get_str_width(...)           ucg_GetStrWidth(&glcd, __VA_ARGS__)

#define glcd_draw_glyph(...)              ucg_DrawGlyph(&glcd, __VA_ARGS__)
#define glcd_draw_string(...)             ucg_DrawString(&glcd, __VA_ARGS__)
int16_t glcd_draw_string_P(int16_t x, int16_t y, uint8_t dir, const char *s);

#endif /* !__GLCD_COLOR_H */
