TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(GLCD_SUPPORT)_SRC += hardware/lcd/glcd/glcd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

