TARGET = libstella.a
TOPDIR = ..
SRC = \
	process.c \
	pwm-gpl2.c \
	timer.c \
	stella_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
