TARGET = libstella.a
TOPDIR = ..
SRC = \
	stella_pwm.c \
	stella_net.c \
	stella_protocol.c \
	stella.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
