TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(UECMD_SUPPORT)_SRC += protocols/ecmd/via_udp/uecmd_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
