TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MSR1_SUPPORT)_ECMD_SRC += protocols/msr1/msr1.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
