TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MSR1_SUPPORT)_SRC += protocols/msr1/msr1.c
$(MSR1_SUPPORT)_ECMD_SRC += protocols/msr1/msr1_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
