TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SENDMAIL_SUPPORT)_SRC += protocols/smtp/sendmail.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
