TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DMX_STORAGE_SUPPORT)_SRC += \
	services/dmx-storage/dmx_storage.c \
	services/dmx-storage/dmx_storage_ecmd.c \

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
