TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DMX_STORAGE_SUPPORT)_SRC += \
	services/dmx-storage/dmx-storage.c \
	services/dmx-storage/dmx-storage-ecmd.c \

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
