TARGET = libwatchcat.a
TOPDIR = ..
SRC = \
	watchcat.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
