TOPDIR ?= ../..
include $(TOPDIR)/.config

$(TTY_SUPPORT)_SRC += core/tty/tty.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
