TOPDIR ?= ../..
include $(TOPDIR)/.config

$(TTY_SUPPORT)_SRC += core/tty/tty.c
$(TTY_LL_HD44780)_SRC += core/tty/tty-hd44780.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
