TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(GENERIC_ASK_SUPPORT)_SRC += hardware/radio/generic/generic.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
