TOPDIR ?= ../..
include $(TOPDIR)/.config

$(HBRIDGE_SUPPORT)_SRC += hardware/hbridge/hbridge.c
$(HBRIDGE_SUPPORT)_ECMD_SRC += hardware/hbridge/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
