SUBSUBDIRS += services/clock
SUBSUBDIRS += services/cron
SUBSUBDIRS += services/dyndns
SUBSUBDIRS += services/dmx-storage
SUBSUBDIRS += services/dmx-fxslot
SUBSUBDIRS += services/echo
SUBSUBDIRS += services/freqcount
SUBSUBDIRS += services/pam
SUBSUBDIRS += services/httpd
SUBSUBDIRS += services/jabber
SUBSUBDIRS += services/ntp
SUBSUBDIRS += services/wol
SUBSUBDIRS += services/motd
SUBSUBDIRS += services/moodlight
SUBSUBDIRS += services/stella
SUBSUBDIRS += services/starburst
SUBSUBDIRS += services/tanklevel
SUBSUBDIRS += services/tftp
SUBSUBDIRS += services/upnp
SUBSUBDIRS += services/appsample
SUBSUBDIRS += services/watchcat
SUBSUBDIRS += services/vnc
SUBSUBDIRS += services/watchasync
SUBSUBDIRS += services/curtain
SUBSUBDIRS += services/glcdmenu
SUBSUBDIRS += services/lome6
SUBSUBDIRS += services/projectors/sanyoZ700

# generic fluff
include $(TOPDIR)/scripts/rules.mk
include $(TOPDIR)/services/custom.mk
