TARGET = libcron.a
TOPDIR = ..
SRC = \
	cron.c \
	test.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
