TARGET = libclock.a
TOPDIR = ..
SRC = \
	cron.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
