/* This file has been generated by known_buddies.m4 automatically.
   Please do not modify it, edit the m4 scripts instead. */
/* Char array definitions follow */

/* Definition of alias pointer array follows */
static const PROGMEM char *jabber_known_buddies[] = {
        NULL
};
