TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(RC5_SUPPORT)_SRC += hardware/ir/rc5/rc5.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
