TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(RC5_SUPPORT)_SRC += hardware/ir/rc5/rc5.c
$(RC5_SUPPORT)_ECMD_SRC += hardware/ir/rc5/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
