TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(RC5_SUPPORT)_SRC += hardware/ir/rc5/rc5.c
$(RC5_UDP_SUPPORT)_SRC += hardware/ir/rc5/rc5_net.c
$(RC5_SUPPORT)_ECMD_SRC += hardware/ir/rc5/rc5_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
