TOPDIR ?= ../..
include $(TOPDIR)/.config

$(TO1_SUPPORT)_SRC += protocols/to1/to1.c
$(TO1_SUPPORT)_ECMD_SRC += protocols/to1/to1_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
