TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SGC_SUPPORT)_SRC += protocols/sgc/sgc.c
$(SGC_SUPPORT)_ECMD_SRC += protocols/sgc/sgc_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
