TOPDIR ?= ../..
include $(TOPDIR)/.config

$(HTTPLOG_SUPPORT)_SRC += protocols/httplog/httplog.c
$(HTTPLOG_SUPPORT)_SRC += protocols/httplog/httplog_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
