TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(DATAFLASH_SUPPORT)_SRC += hardware/storage/dataflash/df.c hardware/storage/dataflash/fs.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
