TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MQTT_SUPPORT)_SRC += protocols/mqtt/mqtt.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

