TOPDIR ?= ../..
include $(TOPDIR)/.config

$(CLOCK_SUPPORT)_SRC += services/clock/clock.c services/clock/clock_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
