TOPDIR ?= ../..
include $(TOPDIR)/.config

$(YPORT_SUPPORT)_SRC += protocols/yport/yport.c protocols/yport/yport_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
