/* Do not edit! This file is autogenerated by MenuEdit */

#ifndef MENU_INTERPRETER_CONFIG_H
#define MENU_INTERPRETER_CONFIG_H

#define USE16BITADDR

#define LARGESCREEN

#define MENU_DATASIZE 48
#define MENU_OBJECTS_MAX 3
#define MENU_LIST_MAX 1
#define MENU_TEXT_MAX 2
#define MENU_CHECKBOX_MAX 0
#define MENU_RADIOBUTTON_MAX 0
#define MENU_GFX_MAX 0
#define MENU_ACTION_MAX 65534

#define MENU_SCREEN_X 320
#define MENU_SCREEN_Y 240

#define MENU_ACTION_LISTINDEXCHANGE_list1 65534

#define MENU_TEXT_LISTCONTENT 0
#define MENU_TEXT_LABEL_DYN 1



#define MENU_LISTINDEX_list1 0


#define MENU_USE_LABEL
#define MENU_USE_LIST
#define MENU_USE_WINDOW

#endif

