TOPDIR ?= ..
include $(TOPDIR)/.config

$(NTP_SUPPORT)_SRC += ntp/ntp.c ntp/ntp_net.c
$(NTPD_SUPPORT)_SRC += ntp/ntpd_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
