TARGET = libntp.a
TOPDIR = ..
SRC = \
	ntp.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
