TARGET = libntp.a
TOPDIR = ..
SRC = \
	ntp.c \
	ntpd_net.c \
	ntp_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
