TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DMX_SUPPORT)_SRC += protocols/dmx/dmx.c

$(DMX_SUPPORT)_ECMD_SRC += \
	protocols/dmx/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
