TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DMX_SUPPORT)_SRC += protocols/dmx/dmx.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
