TARGET = libhc165.a
TOPDIR = ..
SRC = \
	hc165.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
