TOPDIR ?= ../..
include $(TOPDIR)/.config

$(NETSTAT_SUPPORT)_SRC += protocols/netstat/netstat.c
$(NETSTAT_SUPPORT)_ECMD_SRC += protocols/netstat/netstat_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
