TOPDIR ?= ..
include $(TOPDIR)/.config

$(ECMD_SERIAL_I2C_SUPPORT)_SRC += ecmd_serial/ecmd_serial_i2c.c
$(ECMD_SERIAL_USART_SUPPORT)_SRC += ecmd_serial/ecmd_serial_usart.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
