TARGET = libecmd_serial.a
TOPDIR = ..
SRC = \
	ecmd_serial_i2c.c \
	ecmd_serial_usart.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
