TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DHT_SUPPORT)_SRC += hardware/dht/dht.c
$(DHT_SUPPORT)_ECMD_SRC += hardware/dht/dht_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
