TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SER_RAM_23K256_SUPPORT)_SRC += hardware/serial_ram/23k256/sram_23k256.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
