TOPDIR ?= ..
include $(TOPDIR)/.config

$(ZBUS_SUPPORT)_SRC += zbus/process.c zbus/zbus.c
$(ZBUS_RAW_SUPPORT)_SRC += zbus/zbus_raw_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
