TARGET = libzbus.a
TOPDIR = ..
SRC = \
	process.c \
	zbus.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
