TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MOTORCURTAIN_SUPPORT)_SRC += services/curtain/curtain.c services/curtain/curtain_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
