TARGET = libdyndns.a
TOPDIR = ..
SRC = \
	dyndns.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
