TOPDIR ?= ..
include $(TOPDIR)/.config

$(DYNDNS_SUPPORT)_SRC += dyndns/dyndns.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
