TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SMS77_SUPPORT)_SRC += protocols/sms77/sms77.c
$(SMS77_SUPPORT)_SRC += protocols/sms77/sms77_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
