TARGET = libjabber.a
TOPDIR = ..
SRC = \
	jabber.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk

