TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ZBUS_SUPPORT)_SRC += protocols/zbus/process.c protocols/zbus/zbus.c
$(ZBUS_RAW_SUPPORT)_SRC += protocols/zbus/zbus_raw_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
