TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(ST7626_SUPPORT)_SRC += hardware/lcd/ST7626/ST7626.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
