TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SERIAL_LINE_LOG_SUPPORT)_SRC += protocols/serial_line_log/serial_line_log.c
$(SERIAL_LINE_LOG_SUPPORT)_ECMD_SRC += protocols/serial_line_log/serial_line_log_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
