TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DYNDNS_SUPPORT)_SRC += services/dyndns/dyndns.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
