TOPDIR ?= ../..
include $(TOPDIR)/.config

$(UDP_STATES_RECIEVE)_SRC += protocols/udp_states/udp_states_recieve.c
$(UDP_STATES_TRANSMIT)_SRC += protocols/udp_states/udp_states_transmit.c
##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
