TOPDIR ?= ../..
include $(TOPDIR)/.config

$(TWITTER_SUPPORT)_SRC += protocols/twitter/twitter.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
