TOPDIR ?= ../..
include $(TOPDIR)/.config

$(TWITTER_SUPPORT)_SRC += protocols/twitter/twitter.c
$(TWITTER_SUPPORT)_SRC += protocols/twitter/twitter_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
