TOPDIR ?= ../..
include $(TOPDIR)/.config

$(LOME6_SUPPORT)_SRC += services/lome6/lome6.c
$(LOME6_SUPPORT)_ECMD_SRC += services/lome6/lome6_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
