TARGET = lib595.a
TOPDIR = ..
SRC = \
	hc595.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
