TOPDIR ?= ../..
include $(TOPDIR)/.config

SRC += hardware/sms/sms.c
SRC += hardware/sms/sms_ecmd.c
SRC += hardware/sms/sms_encoding.c


##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

