TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SMS_SUPPORT)_SRC += hardware/sms/sms.c
$(ECMD_SMS_SUPPORT)_SRC += hardware/sms/sms_ecmd.c
$(SMS_SUPPORT)_SRC += hardware/sms/sms_encoding.c


##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

