#! /bin/bash

#
# Copyright (c) 2012 by Gerd v. Egidy <gerd@egidy.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# For more information on the GPL, please go to:
# http://www.gnu.org/copyleft/gpl.html
#

DEFINE=$1

(cat <<EOF
#include <avr/pgmspace.h>
#include "config.h"
${DEFINE}
EOF
) > dummy.c || exit 1

make dummy.E >/dev/null || exit 1
tail -n 1 dummy.E

rm -f dummy.[cE]
