TOPDIR ?= ../..

$(GAME_INPUT_SUPPORT)_SRC += hardware/input/game_commons.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
