TARGET = libtftp.a
TOPDIR = ..
SRC = \
	tftp-bootload.c \
	tftp-dataflash.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
