TARGET = libtftp.a
TOPDIR = ..
SRC = \
	tftp.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
