TOPDIR ?= ..
include $(TOPDIR)/.config

$(SOAP_SUPPORT)_SRC += protocols/soap/soap.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

