TARGET = librc5.a
TOPDIR = ..
SRC = \
	rc5.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
