TOPDIR ?= ../..
include $(TOPDIR)/.config

$(IRC_SUPPORT)_SRC += protocols/irc/irc.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

