TOPDIR ?= ../..
include $(TOPDIR)/.config

$(IRC_SUPPORT)_SRC += protocols/irc/irc.c
$(IRC_SUPPORT)_ECMD_SRC += protocols/irc/irc_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

