#! /bin/bash

#
# Copyright (c) 2008 by Stefan Siegl <stesie@brokenpipe.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# For more information on the GPL, please go to:
# http://www.gnu.org/copyleft/gpl.html
#

(cat <<EOF
#include <avr/pgmspace.h>
SPM_PAGESIZE
EOF
) > dummy.c || exit 1

make dummy.E || exit 1
PAGESZ=$(tail -n 1 dummy.E)

rm -f dummy.[cE]

echo "The pagesize of current architecture is $PAGESZ."

while true; do
  fn="$1"; shift
  test "x$fn" = "x" && {
    SZ=$(stat -c %s ethersex.bin)
    echo "Final size of ethersex.bin is $SZ."
    exit 0
  }
  >/dev/null
  if [ ! -e "$fn" ]; then 
    continue
  fi
  unzipped=$(echo "$fn" | sed 's/\.gz$//')
  gzip -c  -9 "$fn" > "$fn.gz"


  echo Embedding $fn ...
  httpd/httpd-concat ethersex.bin $PAGESZ "$fn" > ethersex.embed.bin || exit 1
  mv -f ethersex.embed.bin ethersex.bin

  rm -f "$fn".gz
done

