TARGET = libhttpd.a
TOPDIR = ..
SRC = \
	httpd.c	\

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
