TARGET = libhttpd.a
TOPDIR = ..
SRC = \
	headers.c	\
	httpd.c		\
	base64_mit.c	\

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk

