TARGET = libdcf77.a
TOPDIR = ..
SRC = \
	dcf77.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
