TARGET = libsensor_rfm12.a
TOPDIR = ..
SRC = \
	sensor_rfm12.c \
	kty81.c \
	lcd.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
