TOPDIR ?= ../..
include $(TOPDIR)/.config

$(STELLA_PROTOCOL_SUPPORT)_SRC += protocols/udpstella/udpstella_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
