TOPDIR ?= ..
include $(TOPDIR)/.config

$(DATAFLASH_SUPPORT)_SRC += dataflash/df.c dataflash/fs.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
