TARGET = libdataflash.a
TOPDIR = ..
SRC = \
	df.c	\
	fs.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
