TOPDIR ?= ..
include $(TOPDIR)/.config

$(CLOCK_SUPPORT)_SRC +=	clock/clock.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
