TOPDIR ?= ../..
include $(TOPDIR)/.config

$(CW_SUPPORT)_SRC += protocols/cw/cw.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
