TARGET = libi2c_slave.a
TOPDIR = ..
SRC = \
	i2c_slave.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
