TOPDIR ?= ..
include $(TOPDIR)/.config

$(I2C_SLAVE_SUPPORT)_SRC += i2c_slave/i2c_slave.c \
	i2c_slave/i2c_slave_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
