TARGET = libvfs.a
TOPDIR = ..
SRC = \
	vfs.c  		\
	vfs_df.c	\
	vfs_sd.c


##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
