#! /bin/sh

[ -e config.in ] || {
  echo "$0: This script has to be run from the Ethersex root directory."
  exit 1
}

if [ x"$1" != x"-n" ]; then 
  git pull --quiet origin  >/dev/null  || exit 2
else
  shift
fi

total=0
failures=0

if [ x"$1" != x"" ]; then
  while [ -n "$1" ]; do

    profile=""
    if [ -e "contrib/autotest/profiles/$1" ]; then
      profile="contrib/autotest/profiles/$1"
    fi
    if [ -e "scripts/profiles/$1" ]; then
      profile="scripts/profiles/$1"
    fi
    if [ -z "$profile" ]; then
      echo "Profile $1 not found"
      shift;
      continue;
    fi

    total=$((total+1))
    echo "Trying to compile Ethersex firmware using profile '$profile' ..."
    if ./contrib/autotest/run "$profile" >/dev/null; then
      [ -e "ethersex.bin" ] && ls -l ethersex.bin
    else
      echo "FAILED: $profile"
      failures=$((failures+1))
    fi
    echo ""

    shift;

  done

else
  for A in contrib/autotest/profiles/* scripts/profiles/*; do
    echo "Trying to compile Ethersex firmware using profile '$A' ..."
    if ./contrib/autotest/run "$A" > /dev/null; then
      [ -e "ethersex.bin" ] && ls -l ethersex.bin
    else
      echo "FAILED: $A"
      failures=$((failures+1))
    fi
    total=$((total+1))
    echo ""
  done
fi

echo "$((total-failures))/$total profiles built successfully."
[ "$failures" -eq 0 ]
