#! /bin/sh

[ -e config.in ] || {
  echo "$0: This script has to be run from the Ethersex root directory."
  exit 1
}

git pull --quiet origin  >/dev/null  || exit 2

for A in contrib/autotest/profiles/* scripts/profiles/*; do
  echo "Trying to compile Ethersex firmware using profile '$A' ..."
  ./contrib/autotest/run "$A" > /dev/null
  [ -e "ethersex.bin" ] && ls -l ethersex.bin
  echo ""
done
