#! /bin/sh
unset LANG

if [ "x$CFLAGS" = "x" ]; then
  CFLAGS="-Wall -W -Wno-unused-parameter -Wno-uninitialized -Wno-pointer-sign -Wno-char-subscripts -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-label"
  export CFLAGS
fi

[ -e config.in ] || {
  echo "$0: This script has to be run from the Ethersex root directory."
  exit 1
}

[ "x$1" = "x" ] && {
  echo "$0: You have to run me with a config file as argument."
  exit 1
}

[ "x$1" = "x.config" ] || {
  # we need to copy the file first
  [ -e "$1" ] || {
    echo "$0: Cannot access file: $1"
    exit 1
  }

  cp -f "$1" .config
}

# re-generate autoconf.h
rm -f autoconf.h
/bin/echo -ne "\t\n\n" | make no_deps=t menuconfig
[ -e autoconf.h ] || {
  echo "$0: failed to generate autoconf.h file."
  exit 1
}

make no_deps=t clean 2> /dev/null

# We don't call 'make all' here to skip httpd-embedding part ...
make $MAKEOPTS ethersex
[ -e ethersex ] || {
  echo "$0: failed to generate ethersex file."
  exit 1
}

# Now (possibly) do the httpd-embedding, which writes status
# information to stderr, which isn't quite what we need for the autotester.
# Let's just see whether it works.
make $MAKEOPTS ethersex.bin > /dev/null 2> /dev/null
[ -e ethersex.bin ] || {
  echo "$0: failed to generate ethersex.bin file, i.e. httpd-embed failed."
  exit 1
}


echo ""
echo " Looks good!"
echo ""
