#!/bin/bash

if [ "$#" -lt "1" ]; then
  echo "USAGE: eeprom-usage <mcu>"
  exit 1
fi

tmp=`mktemp`

avr-gcc -mmcu=$1 -E -dM - </dev/null 2>/dev/null | grep "_AVR_AT" >$tmp.c

cat >> $tmp.c << EOF
#include <stdio.h>
#include "config.h"
#include "core/eeprom.h"
#include "avr/io.h"

int
main(void)
{
#ifdef EEPROM_SUPPORT
  int ee_size = E2END + 1;
  int ee_used = sizeof(struct eeprom_config_t);
  printf("EEPROM usage: %d/%d bytes: (%.2f%%)\n", ee_used, ee_size,
         100 * (float) ee_used / ee_size);
#else
  printf("EEPROM_SUPPORT not enabled.\n");
#endif
  return 0;
}

EOF

which gcc avr-gcc >/dev/null && avr-cpp -I. $tmp.c 2>/dev/null | gcc -x c -o $tmp - 2>/dev/null
if [ -x $tmp ]; then
  $tmp
else
  echo "EEPROM size couldn't be determined."
fi

rm -f $tmp.c $tmp

