#!/bin/bash

. scripts/osdefaults.sh

if [ "$#" -lt "2" ]; then
  echo "USAGE: eeprom-usage <CFLAGS> <CPPFLAGS>"
  exit 1
fi

tmp=`mktemp eeXXXXXX`

avr-gcc -xc $1 $2 -o $tmp - << EOF
#include <avr/io.h>
#include <avr/eeprom.h>
#include "config.h"
#include "core/eeprom.h"

#ifdef EEPROM_SUPPORT
struct eeprom_config_t eeprom_config EEMEM;
#endif

int main(void)
{
#ifdef EEPROM_SUPPORT
  (void)eeprom_read_byte((const uint8_t *)&eeprom_config);
#endif
  return 0;
}
EOF

ee_used=`avr-size -A $tmp | sed -e '/^\.eeprom/!d;s/[^0-9]*\([0-9]*\).*/\1/'`
rm -f $tmp
if [ -z "$ee_used" ]; then
  exit 0
fi

ee_size=$(echo $(( `echo -e "#include <avr/io.h>\nE2END" | avr-cpp $2 | ${SED} '$!d'` + 1 )))
ee_pct=$(${AWK} "BEGIN {printf(\"%.2f\", $ee_used.0 / $ee_size.0 * 100.0);}")

echo "EEPROM usage: $ee_used/$ee_size bytes (${ee_pct}%)"

if [ "$ee_used" -gt "$ee_size" ]; then
  echo "ERROR: EEPROM memory exhausted.";
  exit 1
fi

