#!/bin/sh

### use GNU sed from macports instead of BSD sed on MacOS X
### BSD sed does not support -r option
if [ x"$OSTYPE" = x"darwin10.0" ]; then
    SED="gsed"
else
    SED="sed"
fi

grep -e "^#define .*_SUPPORT" autoconf.h | $SED -e "s/^#define /-Dconf_/" -e "s/_SUPPORT.*//"
grep -e "^#define CONF_.*" autoconf.h |  $SED -e "s/^#define CONF_/-Dvalue_/" -re "s/( )/=/" -e "s/[ \"]//g"
