#!/bin/sh

. scripts/osdefaults.sh

grep -e "^#define .*_SUPPORT" autoconf.h | $SED -e "s/^#define /-Dconf_/" -e "s/_SUPPORT.*//"
grep -e "^#define CONF_.*" autoconf.h |  $SED -e "s/^#define CONF_/-Dvalue_/" -re "s/( )/=/" -e "s/[ \"]//g"
