#!/bin/bash

random_hex()
{
	local max="${1:-255}"	# integer
	local line seed

	# e.g.: 0x6f2d
	seed="$( dd if=/dev/urandom bs=2 count=1 2>&- | hexdump | if read line; then echo 0x${line#* }; fi )"

	printf "%02x" "$(( $seed % $max ))"
}

random_mac()
{
	local prefix="02:ca:fe"
	# http://de.wikipedia.org/wiki/MAC-Adresse#Stolperfalle:_Kennzeichnung_.E2.80.9EPRIVATE.E2.80.9C
	# http://de.wikipedia.org/wiki/Locally_Administered_Address
	# prefix: 'ac:de:48' is private, dont use!

	echo "$prefix:$( random_hex ):$( random_hex ):$( random_hex )"
}

echo "$1=\"$( random_mac )\""
