TARGET = libmysql.a
TOPDIR = ..
SRC = \
	mysql.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk

