TOPDIR ?= ..
include $(TOPDIR)/.config

$(MYSQL_SUPPORT)_SRC += mysql/mysql.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk

