TARGET = libi2c_eeprom.a
TOPDIR = ..
SRC = \
	i2c_master.c \
	i2c_24CXX.c \
	i2c_lm75.c \
	i2c_udp.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
