TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ZACWIRE_SUPPORT)_SRC += hardware/zacwire/zacwire.c
$(ZACWIRE_SUPPORT)_ECMD_SRC += hardware/zacwire/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
