TARGET = libcamera.a
TOPDIR = ..
SRC = \
	dc3840.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk

CFLAGS += -fshort-enums