TOPDIR ?= ..
include $(TOPDIR)/.config

$(DC3840_SUPPORT)_SRC += camera/dc3840.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk

CFLAGS += -fshort-enums
