TARGET = libsyslog.a
TOPDIR = ..
SRC = \
	syslog_net.c \
	syslog.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
