TOPDIR ?= ..
include $(TOPDIR)/.config

$(SYSLOG_SUPPORT)_SRC += syslog/syslog_net.c syslog/syslog.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
