TOPDIR ?= ../..
include $(TOPDIR)/.config

$(VNC_SUPPORT)_SRC += services/vnc/vnc.c 
$(VNC_SUPPORT)_SRC += services/vnc/vnc_block_factory.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
