TOPDIR ?= ../..
include $(TOPDIR)/.config

$(PAM_SUPPORT)_SRC += services/pam/$(PAM_SUBSYSTEM).c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
