TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(S1D13305_SUPPORT)_SRC += hardware/lcd/s1d13305/s1d13305.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
