TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ROTORHAMLIB_SUPPORT)_SRC += hardware/rotor/rotor.c
$(ROTORHAMLIB_SUPPORT)_ECMD_SRC += hardware/rotor/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
