TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MOTD_SUPPORT)_SRC += services/motd/motd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
