TOPDIR ?= ../..
include $(TOPDIR)/.config

$(BULBDIAL_SUPPORT)_SRC += services/bulbdial/bulbdial.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
