TOPDIR ?= ..
include $(TOPDIR)/.config

$(ONEWIRE_SUPPORT)_SRC += onewire/onewire.c

##############################################################################
# generic fluff
include $(TOPDIR)/rules.mk
