TARGET = libonewire.a
TOPDIR = ..
SRC = \
	onewire.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
