TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(ECMD_SERIAL_USART_SUPPORT)_SRC += protocols/ecmd/via_i2c/ecmd_usart.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
