TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(ECMD_SERIAL_USART_SUPPORT)_SRC += protocols/ecmd/via_usart/ecmd_usart.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
