TOPDIR ?= ../..
include $(TOPDIR)/.config

$(UPNP_SUPPORT)_SRC += services/upnp/upnp.c
$(UPNP_SUPPORT)_ECMD_SRC += services/upnp/upnp_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
