TARGET = liblcd.a
TOPDIR = ..
SRC = \
	hd44780.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
