TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(ECMD_SUPPORT)_SRC += protocols/ecmd/via_tcp/ecmd_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
