TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MOTORCURTAIN_PROTOCOL_SUPPORT)_SRC += protocols/udpcurtain/udpcurtain_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
