TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MOODLIGHT_SUPPORT)_SRC += \
	services/moodlight/moodlight.c \
	services/moodlight/moodlight_ecmd.c

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
