TOPDIR ?= ..
include $(TOPDIR)/.config

$(ECMD_SCRIPT_SUPPORT)_SRC += ecmd_parser/scripting.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
