
CC = gcc
CFLAGS = -Wall -Wstrict-prototypes -std=gnu99 -fno-inline -O2 -Werror
#LDFLAGS += -lm

all: launch-bootloader

.PHONY: clean clean-launch-bootloader

clean: clean-launch-bootloader

clean-launch-bootloader:
	rm -f launch-bootloader
