SERIAL_DEV=/dev/ttyUSB0
ISP_DEV=/dev/ttyUSB0
ISP_PROG=avr109
AVRDUDE_BAUDRATE=115200
MCU=atmega32
F_CPU=16000000
DEBUG=1
CFLAGS += -DBOOTLOADER_DDR=DDRD
CFLAGS += -DBOOTLOADER_PORT=PORTD
CFLAGS += -DBOOTLOADER_PIN=PIND
CFLAGS += -DBOOTLOADER_PINNUM=PIND7
CFLAGS += -DSEND_BOOT_MESSAGE=1
# CFLAGS += -DBOOTLOADER_JUMPER
CFLAGS += -DBOOTLOADER_CHAR
