TARGET = libcrypto.a
TOPDIR = ..
SRC = \
	cast5.c \
	md5.c \
	encrypt-llh.c \

ASRC = \
	sha1-asm.S

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
