TARGET = libcrypto.a
TOPDIR = ..
SRC = \
	cast5.c \
	md5.c \
	skipjack.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
