TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WATCHASYNC_SUPPORT)_SRC += services/watchasync/watchasync.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

