TOPDIR ?= ../..
include $(TOPDIR)/.config

$(LDAP_AUTH_SUPPORT)_SRC += protocols/ldap_auth/ldap_auth.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

