TOPDIR ?= ../..
include $(TOPDIR)/.config

$(TOWERCTL_SUPPORT)_SRC += hardware/tower/tower.c
$(TOWERCTL_SUPPORT)_ECMD_SRC += hardware/tower/tower_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
