TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(ADS7822_SUPPORT)_SRC += hardware/adc/ads7822/ads7822.c
$(ADS7822_SUPPORT)_ECMD_SRC += hardware/adc/ads7822/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
