TARGET = librfm12.a
TOPDIR = ..
SRC = \
	process.c \
	rfm12.c \
	skipjack.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
