TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MOTORCURTAIN_SUPPORT)_SRC += protocols/motorCurtain/motorCurtain.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
