TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(BUTTONS_INPUT_SUPPORT)_SRC += hardware/input/buttons/buttons.c
$(BUTTONS_INPUT_SUPPORT)_ECMD_SRC += hardware/input/buttons/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
