TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(DCF77_SUPPORT)_SRC += hardware/clock/dcf77/dcf77.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
