TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ARTNET_SUPPORT)_SRC += protocols/artnet/artnet.c protocols/artnet/artnet_net.c

# $(DMX_SUPPORT)_ECMD_SRC += \
# 	protocols/artnet/ecmd.c
##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
