TARGET = libnet.a
TOPDIR = ..
SRC = \
	bootp_net.c \
	dns_net.c \
	ecmd_net.c \
	uecmd_net.c \
	ecmd_sender_net.c \
	uecmd_sender_net.c \
	handler.c \
	i2c_net.c \
	mdns_sd_net.c \
	ntpd_net.c \
	ntp_net.c \
	rfm12_raw_net.c \
	sendmail.c \
	snmp_net.c \
	stella_net.c \
	syslog_net.c \
	tftp_net.c \
	udp_echo_net.c \
	i2c_slave_net.c \
	yport_net.c \
	modbus_net.c \
	mcuf_net.c \
	zbus_raw_net.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
