TARGET = libnet.a
TOPDIR = ..
SRC = \
	ecmd_net.c \
	uecmd_net.c \
	ecmd_sender_net.c \
	uecmd_sender_net.c \
	handler.c \
	sendmail.c \
	udp_echo_net.c \

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
