TOPDIR ?= ../..
include $(TOPDIR)/.config

SRC += core/util/fixedpoint.c
SRC += core/util/string_parsing.c
SRC += core/util/byte2bin.c
SRC += core/util/byte2hex.c
SRC += core/util/app_crc.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
