TOPDIR ?= ../..
include $(TOPDIR)/.config

SRC += core/util/fixedpoint.c
SRC += core/util/string_parsing.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
