TOPDIR ?= ../..
include $(TOPDIR)/.config

SRC += core/util/fixedpoint.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
