TOPDIR ?= ../..
include $(TOPDIR)/.config

$(USTREAM_SUPPORT)_SRC += protocols/ustream/ustream.c
$(USTREAM_SUPPORT)_SRC += protocols/ustream/vs1053.c

$(USTREAM_SUPPORT)_ECMD_SRC += protocols/ustream/ustream_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

